################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Each subdirectory must supply rules for building sources it contributes
LS0432_rtos_bmsmu/source/adc.obj: C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/source/adc.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="LS0432_rtos_bmsmu/source/$(basename $(<F)).d_raw" --obj_directory="LS0432_rtos_bmsmu/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

LS0432_rtos_bmsmu/source/can.obj: C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/source/can.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="LS0432_rtos_bmsmu/source/$(basename $(<F)).d_raw" --obj_directory="LS0432_rtos_bmsmu/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

LS0432_rtos_bmsmu/source/dabort.obj: C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/source/dabort.asm $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="LS0432_rtos_bmsmu/source/$(basename $(<F)).d_raw" --obj_directory="LS0432_rtos_bmsmu/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

LS0432_rtos_bmsmu/source/errata_SSWF021_45.obj: C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/source/errata_SSWF021_45.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="LS0432_rtos_bmsmu/source/$(basename $(<F)).d_raw" --obj_directory="LS0432_rtos_bmsmu/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

LS0432_rtos_bmsmu/source/esm.obj: C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/source/esm.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="LS0432_rtos_bmsmu/source/$(basename $(<F)).d_raw" --obj_directory="LS0432_rtos_bmsmu/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

LS0432_rtos_bmsmu/source/gio.obj: C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/source/gio.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="LS0432_rtos_bmsmu/source/$(basename $(<F)).d_raw" --obj_directory="LS0432_rtos_bmsmu/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

LS0432_rtos_bmsmu/source/het.obj: C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/source/het.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="LS0432_rtos_bmsmu/source/$(basename $(<F)).d_raw" --obj_directory="LS0432_rtos_bmsmu/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

LS0432_rtos_bmsmu/source/lin.obj: C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/source/lin.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="LS0432_rtos_bmsmu/source/$(basename $(<F)).d_raw" --obj_directory="LS0432_rtos_bmsmu/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

LS0432_rtos_bmsmu/source/notification.obj: C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/source/notification.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="LS0432_rtos_bmsmu/source/$(basename $(<F)).d_raw" --obj_directory="LS0432_rtos_bmsmu/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

LS0432_rtos_bmsmu/source/os_croutine.obj: C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/source/os_croutine.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="LS0432_rtos_bmsmu/source/$(basename $(<F)).d_raw" --obj_directory="LS0432_rtos_bmsmu/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

LS0432_rtos_bmsmu/source/os_event_groups.obj: C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/source/os_event_groups.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="LS0432_rtos_bmsmu/source/$(basename $(<F)).d_raw" --obj_directory="LS0432_rtos_bmsmu/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

LS0432_rtos_bmsmu/source/os_heap.obj: C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/source/os_heap.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="LS0432_rtos_bmsmu/source/$(basename $(<F)).d_raw" --obj_directory="LS0432_rtos_bmsmu/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

LS0432_rtos_bmsmu/source/os_list.obj: C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/source/os_list.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="LS0432_rtos_bmsmu/source/$(basename $(<F)).d_raw" --obj_directory="LS0432_rtos_bmsmu/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

LS0432_rtos_bmsmu/source/os_mpu_wrappers.obj: C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/source/os_mpu_wrappers.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="LS0432_rtos_bmsmu/source/$(basename $(<F)).d_raw" --obj_directory="LS0432_rtos_bmsmu/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

LS0432_rtos_bmsmu/source/os_port.obj: C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/source/os_port.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="LS0432_rtos_bmsmu/source/$(basename $(<F)).d_raw" --obj_directory="LS0432_rtos_bmsmu/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

LS0432_rtos_bmsmu/source/os_portasm.obj: C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/source/os_portasm.asm $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="LS0432_rtos_bmsmu/source/$(basename $(<F)).d_raw" --obj_directory="LS0432_rtos_bmsmu/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

LS0432_rtos_bmsmu/source/os_queue.obj: C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/source/os_queue.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="LS0432_rtos_bmsmu/source/$(basename $(<F)).d_raw" --obj_directory="LS0432_rtos_bmsmu/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

LS0432_rtos_bmsmu/source/os_tasks.obj: C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/source/os_tasks.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="LS0432_rtos_bmsmu/source/$(basename $(<F)).d_raw" --obj_directory="LS0432_rtos_bmsmu/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

LS0432_rtos_bmsmu/source/os_timer.obj: C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/source/os_timer.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="LS0432_rtos_bmsmu/source/$(basename $(<F)).d_raw" --obj_directory="LS0432_rtos_bmsmu/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

LS0432_rtos_bmsmu/source/pinmux.obj: C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/source/pinmux.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="LS0432_rtos_bmsmu/source/$(basename $(<F)).d_raw" --obj_directory="LS0432_rtos_bmsmu/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

LS0432_rtos_bmsmu/source/spi.obj: C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/source/spi.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="LS0432_rtos_bmsmu/source/$(basename $(<F)).d_raw" --obj_directory="LS0432_rtos_bmsmu/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

LS0432_rtos_bmsmu/source/sys_core.obj: C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/source/sys_core.asm $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="LS0432_rtos_bmsmu/source/$(basename $(<F)).d_raw" --obj_directory="LS0432_rtos_bmsmu/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

LS0432_rtos_bmsmu/source/sys_mpu.obj: C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/source/sys_mpu.asm $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="LS0432_rtos_bmsmu/source/$(basename $(<F)).d_raw" --obj_directory="LS0432_rtos_bmsmu/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

LS0432_rtos_bmsmu/source/sys_pcr.obj: C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/source/sys_pcr.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="LS0432_rtos_bmsmu/source/$(basename $(<F)).d_raw" --obj_directory="LS0432_rtos_bmsmu/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

LS0432_rtos_bmsmu/source/sys_phantom.obj: C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/source/sys_phantom.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="LS0432_rtos_bmsmu/source/$(basename $(<F)).d_raw" --obj_directory="LS0432_rtos_bmsmu/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

LS0432_rtos_bmsmu/source/sys_pmu.obj: C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/source/sys_pmu.asm $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="LS0432_rtos_bmsmu/source/$(basename $(<F)).d_raw" --obj_directory="LS0432_rtos_bmsmu/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

LS0432_rtos_bmsmu/source/sys_selftest.obj: C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/source/sys_selftest.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="LS0432_rtos_bmsmu/source/$(basename $(<F)).d_raw" --obj_directory="LS0432_rtos_bmsmu/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

LS0432_rtos_bmsmu/source/sys_startup.obj: C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/source/sys_startup.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="LS0432_rtos_bmsmu/source/$(basename $(<F)).d_raw" --obj_directory="LS0432_rtos_bmsmu/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

LS0432_rtos_bmsmu/source/sys_vim.obj: C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/source/sys_vim.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="LS0432_rtos_bmsmu/source/$(basename $(<F)).d_raw" --obj_directory="LS0432_rtos_bmsmu/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

LS0432_rtos_bmsmu/source/system.obj: C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/source/system.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="LS0432_rtos_bmsmu/source/$(basename $(<F)).d_raw" --obj_directory="LS0432_rtos_bmsmu/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '


