################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Each subdirectory must supply rules for building sources it contributes
logi/src-gen/localconfiguration/local.builtinplc/DataVer.obj: C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc/DataVer.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="logi/src-gen/localconfiguration/local.builtinplc/$(basename $(<F)).d_raw" --obj_directory="logi/src-gen/localconfiguration/local.builtinplc" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

logi/src-gen/localconfiguration/local.builtinplc/DrvDef.obj: C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc/DrvDef.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="logi/src-gen/localconfiguration/local.builtinplc/$(basename $(<F)).d_raw" --obj_directory="logi/src-gen/localconfiguration/local.builtinplc" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

logi/src-gen/localconfiguration/local.builtinplc/IOAccess.obj: C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc/IOAccess.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="logi/src-gen/localconfiguration/local.builtinplc/$(basename $(<F)).d_raw" --obj_directory="logi/src-gen/localconfiguration/local.builtinplc" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

logi/src-gen/localconfiguration/local.builtinplc/IOTab.obj: C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc/IOTab.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="logi/src-gen/localconfiguration/local.builtinplc/$(basename $(<F)).d_raw" --obj_directory="logi/src-gen/localconfiguration/local.builtinplc" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

logi/src-gen/localconfiguration/local.builtinplc/LC3AppInfo.obj: C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc/LC3AppInfo.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="logi/src-gen/localconfiguration/local.builtinplc/$(basename $(<F)).d_raw" --obj_directory="logi/src-gen/localconfiguration/local.builtinplc" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

logi/src-gen/localconfiguration/local.builtinplc/LC3GV.obj: C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc/LC3GV.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="logi/src-gen/localconfiguration/local.builtinplc/$(basename $(<F)).d_raw" --obj_directory="logi/src-gen/localconfiguration/local.builtinplc" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

logi/src-gen/localconfiguration/local.builtinplc/LC3GV_EPDB.obj: C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc/LC3GV_EPDB.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="logi/src-gen/localconfiguration/local.builtinplc/$(basename $(<F)).d_raw" --obj_directory="logi/src-gen/localconfiguration/local.builtinplc" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

logi/src-gen/localconfiguration/local.builtinplc/LC3Task.obj: C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc/LC3Task.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="logi/src-gen/localconfiguration/local.builtinplc/$(basename $(<F)).d_raw" --obj_directory="logi/src-gen/localconfiguration/local.builtinplc" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

logi/src-gen/localconfiguration/local.builtinplc/LC3_EPDB.obj: C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc/LC3_EPDB.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="logi/src-gen/localconfiguration/local.builtinplc/$(basename $(<F)).d_raw" --obj_directory="logi/src-gen/localconfiguration/local.builtinplc" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '


