################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Each subdirectory must supply rules for building sources it contributes
logi/src/srcCommon/BUF/lcfu___bufsize.obj: C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src/srcCommon/BUF/lcfu___bufsize.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="logi/src/srcCommon/BUF/$(basename $(<F)).d_raw" --obj_directory="logi/src/srcCommon/BUF" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

logi/src/srcCommon/BUF/lcfu___rbuf_byte.obj: C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src/srcCommon/BUF/lcfu___rbuf_byte.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="logi/src/srcCommon/BUF/$(basename $(<F)).d_raw" --obj_directory="logi/src/srcCommon/BUF" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

logi/src/srcCommon/BUF/lcfu___rbuf_dint.obj: C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src/srcCommon/BUF/lcfu___rbuf_dint.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="logi/src/srcCommon/BUF/$(basename $(<F)).d_raw" --obj_directory="logi/src/srcCommon/BUF" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

logi/src/srcCommon/BUF/lcfu___rbuf_int.obj: C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src/srcCommon/BUF/lcfu___rbuf_int.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="logi/src/srcCommon/BUF/$(basename $(<F)).d_raw" --obj_directory="logi/src/srcCommon/BUF" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

logi/src/srcCommon/BUF/lcfu___rbuf_lint.obj: C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src/srcCommon/BUF/lcfu___rbuf_lint.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="logi/src/srcCommon/BUF/$(basename $(<F)).d_raw" --obj_directory="logi/src/srcCommon/BUF" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

logi/src/srcCommon/BUF/lcfu___rbuf_lreal.obj: C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src/srcCommon/BUF/lcfu___rbuf_lreal.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="logi/src/srcCommon/BUF/$(basename $(<F)).d_raw" --obj_directory="logi/src/srcCommon/BUF" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

logi/src/srcCommon/BUF/lcfu___rbuf_lword.obj: C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src/srcCommon/BUF/lcfu___rbuf_lword.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="logi/src/srcCommon/BUF/$(basename $(<F)).d_raw" --obj_directory="logi/src/srcCommon/BUF" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

logi/src/srcCommon/BUF/lcfu___rbuf_real.obj: C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src/srcCommon/BUF/lcfu___rbuf_real.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="logi/src/srcCommon/BUF/$(basename $(<F)).d_raw" --obj_directory="logi/src/srcCommon/BUF" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

logi/src/srcCommon/BUF/lcfu___rbuf_sint.obj: C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src/srcCommon/BUF/lcfu___rbuf_sint.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="logi/src/srcCommon/BUF/$(basename $(<F)).d_raw" --obj_directory="logi/src/srcCommon/BUF" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

logi/src/srcCommon/BUF/lcfu___rbuf_udint.obj: C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src/srcCommon/BUF/lcfu___rbuf_udint.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="logi/src/srcCommon/BUF/$(basename $(<F)).d_raw" --obj_directory="logi/src/srcCommon/BUF" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

logi/src/srcCommon/BUF/lcfu___rbuf_uint.obj: C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src/srcCommon/BUF/lcfu___rbuf_uint.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="logi/src/srcCommon/BUF/$(basename $(<F)).d_raw" --obj_directory="logi/src/srcCommon/BUF" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

logi/src/srcCommon/BUF/lcfu___rbuf_ulint.obj: C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src/srcCommon/BUF/lcfu___rbuf_ulint.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="logi/src/srcCommon/BUF/$(basename $(<F)).d_raw" --obj_directory="logi/src/srcCommon/BUF" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

logi/src/srcCommon/BUF/lcfu___rbuf_usint.obj: C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src/srcCommon/BUF/lcfu___rbuf_usint.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="logi/src/srcCommon/BUF/$(basename $(<F)).d_raw" --obj_directory="logi/src/srcCommon/BUF" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

logi/src/srcCommon/BUF/lcfu___wbuf_byte.obj: C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src/srcCommon/BUF/lcfu___wbuf_byte.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="logi/src/srcCommon/BUF/$(basename $(<F)).d_raw" --obj_directory="logi/src/srcCommon/BUF" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

logi/src/srcCommon/BUF/lcfu___wbuf_dint.obj: C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src/srcCommon/BUF/lcfu___wbuf_dint.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="logi/src/srcCommon/BUF/$(basename $(<F)).d_raw" --obj_directory="logi/src/srcCommon/BUF" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

logi/src/srcCommon/BUF/lcfu___wbuf_int.obj: C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src/srcCommon/BUF/lcfu___wbuf_int.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="logi/src/srcCommon/BUF/$(basename $(<F)).d_raw" --obj_directory="logi/src/srcCommon/BUF" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

logi/src/srcCommon/BUF/lcfu___wbuf_lint.obj: C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src/srcCommon/BUF/lcfu___wbuf_lint.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="logi/src/srcCommon/BUF/$(basename $(<F)).d_raw" --obj_directory="logi/src/srcCommon/BUF" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

logi/src/srcCommon/BUF/lcfu___wbuf_lreal.obj: C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src/srcCommon/BUF/lcfu___wbuf_lreal.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="logi/src/srcCommon/BUF/$(basename $(<F)).d_raw" --obj_directory="logi/src/srcCommon/BUF" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

logi/src/srcCommon/BUF/lcfu___wbuf_lword.obj: C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src/srcCommon/BUF/lcfu___wbuf_lword.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="logi/src/srcCommon/BUF/$(basename $(<F)).d_raw" --obj_directory="logi/src/srcCommon/BUF" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

logi/src/srcCommon/BUF/lcfu___wbuf_real.obj: C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src/srcCommon/BUF/lcfu___wbuf_real.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="logi/src/srcCommon/BUF/$(basename $(<F)).d_raw" --obj_directory="logi/src/srcCommon/BUF" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

logi/src/srcCommon/BUF/lcfu___wbuf_sint.obj: C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src/srcCommon/BUF/lcfu___wbuf_sint.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="logi/src/srcCommon/BUF/$(basename $(<F)).d_raw" --obj_directory="logi/src/srcCommon/BUF" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

logi/src/srcCommon/BUF/lcfu___wbuf_udint.obj: C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src/srcCommon/BUF/lcfu___wbuf_udint.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="logi/src/srcCommon/BUF/$(basename $(<F)).d_raw" --obj_directory="logi/src/srcCommon/BUF" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

logi/src/srcCommon/BUF/lcfu___wbuf_uint.obj: C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src/srcCommon/BUF/lcfu___wbuf_uint.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="logi/src/srcCommon/BUF/$(basename $(<F)).d_raw" --obj_directory="logi/src/srcCommon/BUF" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

logi/src/srcCommon/BUF/lcfu___wbuf_ulint.obj: C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src/srcCommon/BUF/lcfu___wbuf_ulint.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="logi/src/srcCommon/BUF/$(basename $(<F)).d_raw" --obj_directory="logi/src/srcCommon/BUF" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

logi/src/srcCommon/BUF/lcfu___wbuf_usint.obj: C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src/srcCommon/BUF/lcfu___wbuf_usint.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="logi/src/srcCommon/BUF/$(basename $(<F)).d_raw" --obj_directory="logi/src/srcCommon/BUF" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '


