################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Each subdirectory must supply rules for building sources it contributes
logi/src/srcCommon/lcfu___anlg.obj: C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src/srcCommon/lcfu___anlg.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="logi/src/srcCommon/$(basename $(<F)).d_raw" --obj_directory="logi/src/srcCommon" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

logi/src/srcCommon/lcfu___bamtx.obj: C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src/srcCommon/lcfu___bamtx.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="logi/src/srcCommon/$(basename $(<F)).d_raw" --obj_directory="logi/src/srcCommon" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

logi/src/srcCommon/lcfu___bit64tobyte8.obj: C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src/srcCommon/lcfu___bit64tobyte8.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="logi/src/srcCommon/$(basename $(<F)).d_raw" --obj_directory="logi/src/srcCommon" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

logi/src/srcCommon/lcfu___byte8tobit64.obj: C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src/srcCommon/lcfu___byte8tobit64.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="logi/src/srcCommon/$(basename $(<F)).d_raw" --obj_directory="logi/src/srcCommon" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

logi/src/srcCommon/lcfu___canrecv.obj: C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src/srcCommon/lcfu___canrecv.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="logi/src/srcCommon/$(basename $(<F)).d_raw" --obj_directory="logi/src/srcCommon" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

logi/src/srcCommon/lcfu___cansend.obj: C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src/srcCommon/lcfu___cansend.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="logi/src/srcCommon/$(basename $(<F)).d_raw" --obj_directory="logi/src/srcCommon" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

logi/src/srcCommon/lcfu___cantx.obj: C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src/srcCommon/lcfu___cantx.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="logi/src/srcCommon/$(basename $(<F)).d_raw" --obj_directory="logi/src/srcCommon" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

logi/src/srcCommon/lcfu___hum.obj: C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src/srcCommon/lcfu___hum.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="logi/src/srcCommon/$(basename $(<F)).d_raw" --obj_directory="logi/src/srcCommon" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

logi/src/srcCommon/lcfu___iord.obj: C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src/srcCommon/lcfu___iord.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="logi/src/srcCommon/$(basename $(<F)).d_raw" --obj_directory="logi/src/srcCommon" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

logi/src/srcCommon/lcfu___iowr.obj: C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src/srcCommon/lcfu___iowr.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="logi/src/srcCommon/$(basename $(<F)).d_raw" --obj_directory="logi/src/srcCommon" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

logi/src/srcCommon/lcfu___isabelinit.obj: C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src/srcCommon/lcfu___isabelinit.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="logi/src/srcCommon/$(basename $(<F)).d_raw" --obj_directory="logi/src/srcCommon" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

logi/src/srcCommon/lcfu___ntc.obj: C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src/srcCommon/lcfu___ntc.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="logi/src/srcCommon/$(basename $(<F)).d_raw" --obj_directory="logi/src/srcCommon" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

logi/src/srcCommon/lcfu___rbits.obj: C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src/srcCommon/lcfu___rbits.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="logi/src/srcCommon/$(basename $(<F)).d_raw" --obj_directory="logi/src/srcCommon" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

logi/src/srcCommon/lcfu___rprm.obj: C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src/srcCommon/lcfu___rprm.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="logi/src/srcCommon/$(basename $(<F)).d_raw" --obj_directory="logi/src/srcCommon" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

logi/src/srcCommon/lcfu___timestamp_elapsed.obj: C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src/srcCommon/lcfu___timestamp_elapsed.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="logi/src/srcCommon/$(basename $(<F)).d_raw" --obj_directory="logi/src/srcCommon" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

logi/src/srcCommon/lcfu___wbits.obj: C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src/srcCommon/lcfu___wbits.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="logi/src/srcCommon/$(basename $(<F)).d_raw" --obj_directory="logi/src/srcCommon" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

logi/src/srcCommon/lcfu___wprm.obj: C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src/srcCommon/lcfu___wprm.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/bin/armcl" -mv7R4 --code_state=32 --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/HEMAbattery" --include_path="C:/ti/ccs1281/ccs/tools/compiler/ti-cgt-arm_20.2.7.LTS/include" --include_path="C:/TMS570_RTOS/ADC_TMS" --include_path="C:/TMS570_RTOS/BATTERY1/batt_OS" --include_path="C:/TMS570_RTOS/BATTERY1/currentTab" --include_path="C:/TMS570_RTOS/BATTERY1/PL455" --include_path="C:/TMS570_RTOS/CAN/include" --include_path="C:/TMS570_RTOS/FLASH/FLASH_IS25" --include_path="C:/TMS570_RTOS/FLASH/flashmutex" --include_path="C:/TMS570_RTOS/FLASH/flashTask" --include_path="C:/TMS570_RTOS/FLASH/MEM_OPR" --include_path="C:/TMS570_RTOS/ISABEL" --include_path="C:/TMS570_RTOS/include" --include_path="C:/TMS570_RTOS/HALCOGEN/LS0432_rtos_bmsmu/include" --include_path="C:/TMS570_RTOS/tmsOS" --include_path="C:/TMS570_RTOS/TPS" --include_path="C:/TMS570_RTOS/UART1/uart_ex" --include_path="C:/TMS570_RTOS/spicustom" --include_path="C:/TMS570_RTOS/LOGICAD/com.logicals.lc3.library.standard__3.2.2/INCLUDES" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/h" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/LCAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/uRTS3/RTSAPI/RISMD" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/RTS2/RTSAPI" --include_path="C:/TMS570_RTOS/LOGICAD/LOGI.CALS/nRTS/RTSAPI" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/h" --include_path="C:/Users/ARGE13/Documents/SIMERLIFT/logiwork_simerlift_80v/logiwork_simerlift_80v/HEMAbattery/src-gen/localconfiguration/local.builtinplc" --define=SVOLT_CV07 --define=BMSMU -g --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --gen_data_subsections=on --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="logi/src/srcCommon/$(basename $(<F)).d_raw" --obj_directory="logi/src/srcCommon" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '


