#ifndef LC_PROT_LCDT___BESSALARMS__H
#define LC_PROT_LCDT___BESSALARMS__H

#include <LC3CGBase.h>

/*                            Typedefs                         */
typedef struct _LC_TD_DataType_BESSALARMS
{
  LC_TD_BOOL LC_VD_BMUCOMINTR;
  LC_TD_BOOL LC_VD_CELLOV;
  LC_TD_BOOL LC_VD_CELLOVPROTECTION;
  LC_TD_BOOL LC_VD_CELLUV;
  LC_TD_BOOL LC_VD_CELLUVPROTECTION1;
  LC_TD_BOOL LC_VD_CELLUVPROTECTION2;
  LC_TD_BOOL LC_VD_CELLVIMBALANCE;
  LC_TD_BOOL LC_VD_CHARGECONTACTFAULT;
  LC_TD_BOOL LC_VD_CHARGEOC;
  LC_TD_BOOL LC_VD_CHARGEOCPROTECTION1;
  LC_TD_BOOL LC_VD_CHARGEOCPROTECTION2;
  LC_TD_BOOL LC_VD_CHARGEOCPROTECTION3;
  LC_TD_BOOL LC_VD_CHARGEOT;
  LC_TD_BOOL LC_VD_CHARGEOTPROTECTION;
  LC_TD_BOOL LC_VD_CHARGEUT;
  LC_TD_BOOL LC_VD_CHARGEUTPROTECTION;
  LC_TD_BOOL LC_VD_DISCHARGECONTACTFAULT;
  LC_TD_BOOL LC_VD_DISCHARGEOC;
  LC_TD_BOOL LC_VD_DISCHARGEOCPROTECTION1;
  LC_TD_BOOL LC_VD_DISCHARGEOCPROTECTION2;
  LC_TD_BOOL LC_VD_DISCHARGEOT;
  LC_TD_BOOL LC_VD_DISCHARGEOTPROTECTION;
  LC_TD_BOOL LC_VD_DISCHARGEUT;
  LC_TD_BOOL LC_VD_DISCHARGEUTPROTECTION;
  LC_TD_BOOL LC_VD_EPOSHUTDOWN;
  LC_TD_BOOL LC_VD_FIREPROTECTION;
  LC_TD_BOOL LC_VD_NEGBATVIMBALANCE;
  LC_TD_BOOL LC_VD_PARALLELADDRCONFLICT;
  LC_TD_BOOL LC_VD_PARALLELCOMEXCEPTION;
  LC_TD_BOOL LC_VD_POSBATVIMBALANCE;
  LC_TD_BOOL LC_VD_SOCLOW;
  LC_TD_BOOL LC_VD_TOTALOV;
  LC_TD_BOOL LC_VD_TOTALOVPROTECTION;
  LC_TD_BOOL LC_VD_TOTALUV;
  LC_TD_BOOL LC_VD_TOTALUVPROTECTION;
} LCCG_StructAttrib LC_TD_DataType_BESSALARMS;

/*                   ColdBoot Initialization Macro             */
#define LC_INIT_DataType_BESSALARMS(p) \
{ \
  LC_INIT_BOOL(&((p)->LC_VD_CELLUV)); \
  LC_INIT_BOOL(&((p)->LC_VD_CELLOV)); \
  LC_INIT_BOOL(&((p)->LC_VD_CHARGEOT)); \
  LC_INIT_BOOL(&((p)->LC_VD_CHARGEUT)); \
  LC_INIT_BOOL(&((p)->LC_VD_DISCHARGEOT)); \
  LC_INIT_BOOL(&((p)->LC_VD_DISCHARGEUT)); \
  LC_INIT_BOOL(&((p)->LC_VD_DISCHARGEOC)); \
  LC_INIT_BOOL(&((p)->LC_VD_CHARGEOC)); \
  LC_INIT_BOOL(&((p)->LC_VD_TOTALOV)); \
  LC_INIT_BOOL(&((p)->LC_VD_TOTALUV)); \
  LC_INIT_BOOL(&((p)->LC_VD_SOCLOW)); \
  LC_INIT_BOOL(&((p)->LC_VD_CELLVIMBALANCE)); \
  LC_INIT_BOOL(&((p)->LC_VD_POSBATVIMBALANCE)); \
  LC_INIT_BOOL(&((p)->LC_VD_NEGBATVIMBALANCE)); \
  LC_INIT_BOOL(&((p)->LC_VD_BMUCOMINTR)); \
  LC_INIT_BOOL(&((p)->LC_VD_CELLOVPROTECTION)); \
  LC_INIT_BOOL(&((p)->LC_VD_CELLUVPROTECTION1)); \
  LC_INIT_BOOL(&((p)->LC_VD_CELLUVPROTECTION2)); \
  LC_INIT_BOOL(&((p)->LC_VD_CHARGEOTPROTECTION)); \
  LC_INIT_BOOL(&((p)->LC_VD_CHARGEUTPROTECTION)); \
  LC_INIT_BOOL(&((p)->LC_VD_DISCHARGEOTPROTECTION)); \
  LC_INIT_BOOL(&((p)->LC_VD_DISCHARGEUTPROTECTION)); \
  LC_INIT_BOOL(&((p)->LC_VD_DISCHARGEOCPROTECTION1)); \
  LC_INIT_BOOL(&((p)->LC_VD_DISCHARGEOCPROTECTION2)); \
  LC_INIT_BOOL(&((p)->LC_VD_CHARGEOCPROTECTION1)); \
  LC_INIT_BOOL(&((p)->LC_VD_CHARGEOCPROTECTION2)); \
  LC_INIT_BOOL(&((p)->LC_VD_CHARGEOCPROTECTION3)); \
  LC_INIT_BOOL(&((p)->LC_VD_TOTALOVPROTECTION)); \
  LC_INIT_BOOL(&((p)->LC_VD_TOTALUVPROTECTION)); \
  LC_INIT_BOOL(&((p)->LC_VD_CHARGECONTACTFAULT)); \
  LC_INIT_BOOL(&((p)->LC_VD_DISCHARGECONTACTFAULT)); \
  LC_INIT_BOOL(&((p)->LC_VD_EPOSHUTDOWN)); \
  LC_INIT_BOOL(&((p)->LC_VD_FIREPROTECTION)); \
  LC_INIT_BOOL(&((p)->LC_VD_PARALLELCOMEXCEPTION)); \
  LC_INIT_BOOL(&((p)->LC_VD_PARALLELADDRCONFLICT)); \
}

/*                   WarmBoot Initialization Macro             */
#define LC_WINIT_DataType_BESSALARMS(p,RF) \
{ \
  LC_WINIT_BOOL(&((p)->LC_VD_CELLUV),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_CELLOV),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_CHARGEOT),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_CHARGEUT),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_DISCHARGEOT),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_DISCHARGEUT),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_DISCHARGEOC),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_CHARGEOC),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_TOTALOV),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_TOTALUV),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_SOCLOW),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_CELLVIMBALANCE),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_POSBATVIMBALANCE),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_NEGBATVIMBALANCE),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_BMUCOMINTR),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_CELLOVPROTECTION),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_CELLUVPROTECTION1),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_CELLUVPROTECTION2),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_CHARGEOTPROTECTION),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_CHARGEUTPROTECTION),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_DISCHARGEOTPROTECTION),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_DISCHARGEUTPROTECTION),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_DISCHARGEOCPROTECTION1),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_DISCHARGEOCPROTECTION2),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_CHARGEOCPROTECTION1),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_CHARGEOCPROTECTION2),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_CHARGEOCPROTECTION3),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_TOTALOVPROTECTION),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_TOTALUVPROTECTION),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_CHARGECONTACTFAULT),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_DISCHARGECONTACTFAULT),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_EPOSHUTDOWN),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_FIREPROTECTION),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_PARALLELCOMEXCEPTION),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_PARALLELADDRCONFLICT),RF); \
}

/*                ColdBoot Initialization Macro for Arrays            */
#define LC_INIT_ARRAY_OF_DataType_BESSALARMS(p,ARRAYSIZE) \
{ \
  LC_TD_DataType_BESSALARMS * ptrToElement_ArrayOf_BESSALARMS = (LC_TD_DataType_BESSALARMS*)(p);\
  LC_TD_DataType_BESSALARMS * arrayEnd = ptrToElement_ArrayOf_BESSALARMS+ARRAYSIZE;\
  for (; ptrToElement_ArrayOf_BESSALARMS < arrayEnd; ptrToElement_ArrayOf_BESSALARMS++) \
  { \
    LC_INIT_DataType_BESSALARMS(ptrToElement_ArrayOf_BESSALARMS); \
  } \
}

/*                WarmBoot Initialization Macro for Arrays            */
#define LC_WINIT_ARRAY_OF_DataType_BESSALARMS(p,ARRAYSIZE,RF) \
{ \
  if (RF==0) \
  { \
    LC_INIT_ARRAY_OF_DataType_BESSALARMS(p,ARRAYSIZE); \
  } \
}


#endif
