#ifndef LC_PROT_LCFU___BATTSTACK__H
#define LC_PROT_LCFU___BATTSTACK__H

#include <LC3CGBase.h>
#include <lcdt___battstackerr.h>
#include <lcdt___battstackfault.h>
#include <lcdt___plchannel.h>

/*                            Typedefs                         */
typedef struct _LC_TD_FunctionBlock_BATTSTACK
{
  LC_TD_BOOL LC_VD_BALENB;
  LC_TD_BOOL LC_VD_ENB;
  LC_TD_BOOL LC_VD_M_ALL_R;
  LC_TD_BOOL LC_VD_M_AUX_R;
  LC_TD_USINT LC_VD_BRD;
  LC_TD_USINT LC_VD_CELL;
  LC_TD_UDINT LC_VD_BALV;
  LC_TD_UDINT LC_VD_BAUD;
  LC_TD_UDINT LC_VD_NBOARDS;
  LC_TD_UDINT LC_VD_OVTHRES;
  LC_TD_UDINT LC_VD_UVTHRES;
  LC_TD_REAL LC_VD_NTCBETA;
  LC_TD_REAL LC_VD_NTCNOMR_OHM;
  LC_TD_REAL LC_VD_NTCNOMT_KLV;
  LC_TD_DataType_PLCHANNEL LC_VD_CH;
  LC_TD_DataType_PLCHANNEL LC_VD_CHSEL[16];
  LC_TD_USINT LC_VD_N_CELLS[16];
  LC_TD_USINT LC_VD_T_CELLS[16];
  LC_TD_BOOL LC_VD_ENO;
  LC_TD_USINT LC_VD_MAXCELLBRD;
  LC_TD_USINT LC_VD_MAXCELLNUM;
  LC_TD_USINT LC_VD_MAXTEMPBRD;
  LC_TD_USINT LC_VD_MAXTEMPCELL;
  LC_TD_USINT LC_VD_MINCELLBRD;
  LC_TD_USINT LC_VD_MINCELLNUM;
  LC_TD_USINT LC_VD_MINTEMPBRD;
  LC_TD_USINT LC_VD_MINTEMPCELL;
  LC_TD_USINT LC_VD_N_BRD;
  LC_TD_UINT LC_VD_BALREG;
  LC_TD_UDINT LC_VD_VAV;
  LC_TD_UDINT LC_VD_VCELL;
  LC_TD_UDINT LC_VD_VCH;
  LC_TD_UDINT LC_VD_VMAXCELL;
  LC_TD_UDINT LC_VD_VMINCELL;
  LC_TD_REAL LC_VD_MAXTEMP;
  LC_TD_REAL LC_VD_MINTEMP;
  LC_TD_REAL LC_VD_TEMPCELL;
  LC_TD_REAL LC_VD_VSTACK;
  LC_TD_DataType_BATTSTACKERR LC_VD_ERR;
  LC_TD_DataType_BATTSTACKFAULT LC_VD_FAULT;
  LC_TD_BOOL LC_VD_M_ALL_R_M;
  LC_TD_BOOL LC_VD_M_AUX_R_M;
  LC_TD_UDINT LC_VD_ALLTRIGCOUNT;
  LC_TD_UDINT LC_VD_AUXTRIGCOUNT;
} LCCG_StructAttrib LC_TD_FunctionBlock_BATTSTACK;

/*                   ColdBoot Initialization Macro             */
#define LC_INIT_FunctionBlock_BATTSTACK(p) \
{ \
  LC_INIT_UDINT(&((p)->LC_VD_NBOARDS)); \
  LC_INIT_UDINT(&((p)->LC_VD_BAUD)); \
  LC_INIT_UDINT(&((p)->LC_VD_OVTHRES)); \
  LC_INIT_UDINT(&((p)->LC_VD_UVTHRES)); \
  LC_INIT_BOOL(&((p)->LC_VD_M_ALL_R)); \
  LC_INIT_BOOL(&((p)->LC_VD_M_AUX_R)); \
  LC_INIT_ARRAY(&((p)->LC_VD_N_CELLS),USINT,16); \
  LC_INIT_ARRAY(&((p)->LC_VD_T_CELLS),USINT,16); \
  LC_INIT_ARRAY(&((p)->LC_VD_CHSEL),DataType_PLCHANNEL,16); \
  LC_INIT_USINT(&((p)->LC_VD_BRD)); \
  LC_INIT_USINT(&((p)->LC_VD_CELL)); \
  LC_INIT_DataType_PLCHANNEL(&((p)->LC_VD_CH)); \
  LC_INIT_UDINT(&((p)->LC_VD_BALV)); \
  LC_INIT_BOOL(&((p)->LC_VD_BALENB)); \
  LC_INIT_REAL(&((p)->LC_VD_NTCBETA)); \
  LC_INIT_REAL(&((p)->LC_VD_NTCNOMT_KLV)); \
  LC_INIT_REAL(&((p)->LC_VD_NTCNOMR_OHM)); \
  LC_INIT_BOOL(&((p)->LC_VD_ENB)); \
  LC_INIT_USINT(&((p)->LC_VD_N_BRD)); \
  LC_INIT_UDINT(&((p)->LC_VD_VCH)); \
  LC_INIT_UDINT(&((p)->LC_VD_VCELL)); \
  LC_INIT_UDINT(&((p)->LC_VD_VAV)); \
  LC_INIT_UDINT(&((p)->LC_VD_VMINCELL)); \
  LC_INIT_UDINT(&((p)->LC_VD_VMAXCELL)); \
  LC_INIT_REAL(&((p)->LC_VD_VSTACK)); \
  LC_INIT_USINT(&((p)->LC_VD_MAXCELLBRD)); \
  LC_INIT_USINT(&((p)->LC_VD_MAXCELLNUM)); \
  LC_INIT_USINT(&((p)->LC_VD_MINCELLBRD)); \
  LC_INIT_USINT(&((p)->LC_VD_MINCELLNUM)); \
  LC_INIT_UINT(&((p)->LC_VD_BALREG)); \
  LC_INIT_REAL(&((p)->LC_VD_TEMPCELL)); \
  LC_INIT_REAL(&((p)->LC_VD_MAXTEMP)); \
  LC_INIT_REAL(&((p)->LC_VD_MINTEMP)); \
  LC_INIT_USINT(&((p)->LC_VD_MAXTEMPBRD)); \
  LC_INIT_USINT(&((p)->LC_VD_MAXTEMPCELL)); \
  LC_INIT_USINT(&((p)->LC_VD_MINTEMPBRD)); \
  LC_INIT_USINT(&((p)->LC_VD_MINTEMPCELL)); \
  LC_INIT_DataType_BATTSTACKFAULT(&((p)->LC_VD_FAULT)); \
  LC_INIT_DataType_BATTSTACKERR(&((p)->LC_VD_ERR)); \
  LC_INIT_BOOL(&((p)->LC_VD_M_ALL_R_M)); \
  LC_INIT_BOOL(&((p)->LC_VD_M_AUX_R_M)); \
  LC_INIT_UDINT(&((p)->LC_VD_ALLTRIGCOUNT)); \
  LC_INIT_UDINT(&((p)->LC_VD_AUXTRIGCOUNT)); \
}

/*                   WarmBoot Initialization Macro             */
#define LC_WINIT_FunctionBlock_BATTSTACK(p,RF) \
{ \
  LC_WINIT_UDINT(&((p)->LC_VD_NBOARDS),RF); \
  LC_WINIT_UDINT(&((p)->LC_VD_BAUD),RF); \
  LC_WINIT_UDINT(&((p)->LC_VD_OVTHRES),RF); \
  LC_WINIT_UDINT(&((p)->LC_VD_UVTHRES),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_M_ALL_R),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_M_AUX_R),RF); \
  LC_WINIT_ARRAY(&((p)->LC_VD_N_CELLS),USINT,16,RF); \
  LC_WINIT_ARRAY(&((p)->LC_VD_T_CELLS),USINT,16,RF); \
  LC_WINIT_ARRAY(&((p)->LC_VD_CHSEL),DataType_PLCHANNEL,16,RF); \
  LC_WINIT_USINT(&((p)->LC_VD_BRD),RF); \
  LC_WINIT_USINT(&((p)->LC_VD_CELL),RF); \
  LC_WINIT_DataType_PLCHANNEL(&((p)->LC_VD_CH),RF); \
  LC_WINIT_UDINT(&((p)->LC_VD_BALV),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_BALENB),RF); \
  LC_WINIT_REAL(&((p)->LC_VD_NTCBETA),RF); \
  LC_WINIT_REAL(&((p)->LC_VD_NTCNOMT_KLV),RF); \
  LC_WINIT_REAL(&((p)->LC_VD_NTCNOMR_OHM),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_ENB),RF); \
  LC_WINIT_USINT(&((p)->LC_VD_N_BRD),RF); \
  LC_WINIT_UDINT(&((p)->LC_VD_VCH),RF); \
  LC_WINIT_UDINT(&((p)->LC_VD_VCELL),RF); \
  LC_WINIT_UDINT(&((p)->LC_VD_VAV),RF); \
  LC_WINIT_UDINT(&((p)->LC_VD_VMINCELL),RF); \
  LC_WINIT_UDINT(&((p)->LC_VD_VMAXCELL),RF); \
  LC_WINIT_REAL(&((p)->LC_VD_VSTACK),RF); \
  LC_WINIT_USINT(&((p)->LC_VD_MAXCELLBRD),RF); \
  LC_WINIT_USINT(&((p)->LC_VD_MAXCELLNUM),RF); \
  LC_WINIT_USINT(&((p)->LC_VD_MINCELLBRD),RF); \
  LC_WINIT_USINT(&((p)->LC_VD_MINCELLNUM),RF); \
  LC_WINIT_UINT(&((p)->LC_VD_BALREG),RF); \
  LC_WINIT_REAL(&((p)->LC_VD_TEMPCELL),RF); \
  LC_WINIT_REAL(&((p)->LC_VD_MAXTEMP),RF); \
  LC_WINIT_REAL(&((p)->LC_VD_MINTEMP),RF); \
  LC_WINIT_USINT(&((p)->LC_VD_MAXTEMPBRD),RF); \
  LC_WINIT_USINT(&((p)->LC_VD_MAXTEMPCELL),RF); \
  LC_WINIT_USINT(&((p)->LC_VD_MINTEMPBRD),RF); \
  LC_WINIT_USINT(&((p)->LC_VD_MINTEMPCELL),RF); \
  LC_WINIT_DataType_BATTSTACKFAULT(&((p)->LC_VD_FAULT),RF); \
  LC_WINIT_DataType_BATTSTACKERR(&((p)->LC_VD_ERR),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_M_ALL_R_M),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_M_AUX_R_M),RF); \
  LC_WINIT_UDINT(&((p)->LC_VD_ALLTRIGCOUNT),RF); \
  LC_WINIT_UDINT(&((p)->LC_VD_AUXTRIGCOUNT),RF); \
}

/*                            Prototype                        */
void  lcfu___BATTSTACK(LC_TD_FunctionBlock_BATTSTACK* LC_this, struct _lcoplck_epdb_1_impl* pEPDB);


#endif
