#ifndef LC_PROT_LCFU___ESSBATTSTATE__H
#define LC_PROT_LCFU___ESSBATTSTATE__H

#include <LC3CGBase.h>
#include <lcdt___battstate.h>
#include <lcfu___tbuffer.h>
#include <lcfu_iec61131__TON.h>

/*                            Typedefs                         */
typedef struct _LC_TD_FunctionBlock_ESSBATTSTATE
{
  LC_TD_BOOL LC_VD_CHARGECOMPLETE;
  LC_TD_BOOL LC_VD_CHARGERON;
  LC_TD_BOOL LC_VD_CONTACTFBK;
  LC_TD_BOOL LC_VD_DISCHARGECOMPLETE;
  LC_TD_BOOL LC_VD_FAULT;
  LC_TD_BOOL LC_VD_IGNITION;
  LC_TD_BOOL LC_VD_OUTVOLTSTATUS;
  LC_TD_BOOL LC_VD_OVFAULT;
  LC_TD_BOOL LC_VD_PRECHARGEOK;
  LC_TD_BOOL LC_VD_SHUTDOWNCOMPLETE;
  LC_TD_BOOL LC_VD_UVFAULT;
  LC_TD_REAL LC_VD_CURRENTAMP;
  LC_TD_BOOL LC_VD_CONTACT;
  LC_TD_BOOL LC_VD_CONTACTNEG;
  LC_TD_BOOL LC_VD_ENO;
  LC_TD_BOOL LC_VD_PRECHARGEON;
  LC_TD_DataType_BATTSTATE LC_VD_STATE;
  LC_TD_BOOL LC_VD_BATSTATETIMEOUT;
  LC_TD_BOOL LC_VD_CURRENTCHARGING;
  LC_TD_BOOL LC_VD_CURRENTDISCHARGING;
  LC_TD_TIME LC_VD_BATSTATEELAPSEDTIME;
  LC_TD_TIME LC_VD_BATSTATEINTERVAL;
  LC_TD_TIME LC_VD_STANDBYINTERVAL;
  LC_TD_DataType_BATTSTATE LC_VD_BATTERYSTATE;
  LC_TD_FunctionBlock_TON LC_VD_BATTIMER;
  LC_TD_FunctionBlock_TBUFFER LC_VD_CHARGEVOLTTIMER;
  LC_TD_FunctionBlock_TON LC_VD_CURRENTTIMERCHARGING;
  LC_TD_FunctionBlock_TON LC_VD_CURRENTTIMERDISCHARGING;
  LC_TD_FunctionBlock_TBUFFER LC_VD_DISCHARGEVOLTTIMER;
  LC_TD_DataType_BATTSTATE LC_VD_PREVSTATE;
} LCCG_StructAttrib LC_TD_FunctionBlock_ESSBATTSTATE;

/*                   ColdBoot Initialization Macro             */
#define LC_INIT_FunctionBlock_ESSBATTSTATE(p) \
{ \
  LC_INIT_BOOL(&((p)->LC_VD_IGNITION)); \
  LC_INIT_BOOL(&((p)->LC_VD_CHARGERON)); \
  LC_INIT_BOOL(&((p)->LC_VD_PRECHARGEOK)); \
  LC_INIT_BOOL(&((p)->LC_VD_DISCHARGECOMPLETE)); \
  LC_INIT_BOOL(&((p)->LC_VD_CHARGECOMPLETE)); \
  LC_INIT_BOOL(&((p)->LC_VD_SHUTDOWNCOMPLETE)); \
  LC_INIT_BOOL(&((p)->LC_VD_CONTACTFBK)); \
  LC_INIT_REAL(&((p)->LC_VD_CURRENTAMP)); \
  LC_INIT_BOOL(&((p)->LC_VD_OUTVOLTSTATUS)); \
  LC_INIT_BOOL(&((p)->LC_VD_OVFAULT)); \
  LC_INIT_BOOL(&((p)->LC_VD_UVFAULT)); \
  LC_INIT_BOOL(&((p)->LC_VD_FAULT)); \
  LC_INIT_DataType_BATTSTATE(&((p)->LC_VD_STATE)); \
  LC_INIT_BOOL(&((p)->LC_VD_PRECHARGEON)); \
  LC_INIT_BOOL(&((p)->LC_VD_CONTACT)); \
  LC_INIT_BOOL(&((p)->LC_VD_CONTACTNEG)); \
  LC_INIT_BOOL(&((p)->LC_VD_CURRENTCHARGING)); \
  LC_INIT_BOOL(&((p)->LC_VD_CURRENTDISCHARGING)); \
  LC_INIT_FunctionBlock_TON(&((p)->LC_VD_CURRENTTIMERCHARGING)); \
  LC_INIT_FunctionBlock_TON(&((p)->LC_VD_CURRENTTIMERDISCHARGING)); \
  LC_INIT_FunctionBlock_TBUFFER(&((p)->LC_VD_CHARGEVOLTTIMER)); \
  LC_INIT_FunctionBlock_TBUFFER(&((p)->LC_VD_DISCHARGEVOLTTIMER)); \
  (p)->LC_VD_BATTERYSTATE = LC_ED__BATTSTATE__STANDBY; \
  (p)->LC_VD_PREVSTATE = LC_ED__BATTSTATE__STANDBY; \
  LC_INIT_FunctionBlock_TON(&((p)->LC_VD_BATTIMER)); \
  (p)->LC_VD_BATSTATEINTERVAL = LC_TIME_VALUE(RT_CC_CONST_LL(10),RT_CC_CONST_LL(0)); \
  LC_INIT_BOOL(&((p)->LC_VD_BATSTATETIMEOUT)); \
  LC_INIT_TIME(&((p)->LC_VD_BATSTATEELAPSEDTIME)); \
  (p)->LC_VD_STANDBYINTERVAL = LC_TIME_VALUE(RT_CC_CONST_LL(2),RT_CC_CONST_LL(0)); \
}

/*                   WarmBoot Initialization Macro             */
#define LC_WINIT_FunctionBlock_ESSBATTSTATE(p,RF) \
{ \
  LC_WINIT_BOOL(&((p)->LC_VD_IGNITION),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_CHARGERON),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_PRECHARGEOK),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_DISCHARGECOMPLETE),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_CHARGECOMPLETE),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_SHUTDOWNCOMPLETE),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_CONTACTFBK),RF); \
  LC_WINIT_REAL(&((p)->LC_VD_CURRENTAMP),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_OUTVOLTSTATUS),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_OVFAULT),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_UVFAULT),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_FAULT),RF); \
  LC_WINIT_DataType_BATTSTATE(&((p)->LC_VD_STATE),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_PRECHARGEON),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_CONTACT),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_CONTACTNEG),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_CURRENTCHARGING),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_CURRENTDISCHARGING),RF); \
  LC_WINIT_FunctionBlock_TON(&((p)->LC_VD_CURRENTTIMERCHARGING),0); \
  LC_WINIT_FunctionBlock_TON(&((p)->LC_VD_CURRENTTIMERDISCHARGING),0); \
  LC_WINIT_FunctionBlock_TBUFFER(&((p)->LC_VD_CHARGEVOLTTIMER),0); \
  LC_WINIT_FunctionBlock_TBUFFER(&((p)->LC_VD_DISCHARGEVOLTTIMER),0); \
  if (RF==0) (p)->LC_VD_BATTERYSTATE = LC_ED__BATTSTATE__STANDBY; \
  if (RF==0) (p)->LC_VD_PREVSTATE = LC_ED__BATTSTATE__STANDBY; \
  LC_WINIT_FunctionBlock_TON(&((p)->LC_VD_BATTIMER),0); \
  if (RF==0) (p)->LC_VD_BATSTATEINTERVAL = LC_TIME_VALUE(RT_CC_CONST_LL(10),RT_CC_CONST_LL(0)); \
  LC_WINIT_BOOL(&((p)->LC_VD_BATSTATETIMEOUT),RF); \
  LC_WINIT_TIME(&((p)->LC_VD_BATSTATEELAPSEDTIME),RF); \
  if (RF==0) (p)->LC_VD_STANDBYINTERVAL = LC_TIME_VALUE(RT_CC_CONST_LL(2),RT_CC_CONST_LL(0)); \
}

/*                            Prototype                        */
void  lcfu___ESSBATTSTATE(LC_TD_FunctionBlock_ESSBATTSTATE* LC_this, struct _lcoplck_epdb_1_impl* pEPDB);


#endif
