#ifndef LC_PROT_LCPU___HEMABATTERY__H
#define LC_PROT_LCPU___HEMABATTERY__H

#include <LC3CGBase.h>
#include <lcdt___battstate.h>
#include <lcdt___bessalarms.h>
#include <lcdt___bessoprstatus.h>
#include <lcdt___besssystemstatus.h>
#include <lcdt___bessworkmode.h>
#include <lcdt___plchannel.h>
#include <lcdt___tms570_can.h>
#include <lcdt___tms570_gio.h>
#include <lcdt___tmsadc.h>
#include <lcdt___tmsadcgrp.h>
#include <lcfu___ampmulttemp.h>
#include <lcfu___ampmulttempdis.h>
#include <lcfu___ampmultvoltchar.h>
#include <lcfu___ampmultvoltdisc.h>
#include <lcfu___anlg.h>
#include <lcfu___arr2val.h>
#include <lcfu___balance_isz.h>
#include <lcfu___battstack.h>
#include <lcfu___bcu_battery_status.h>
#include <lcfu___bcu_cell_status.h>
#include <lcfu___bcu_fault_codes.h>
#include <lcfu___bcu_id.h>
#include <lcfu___bcu_state_message.h>
#include <lcfu___bcu_status2.h>
#include <lcfu___buffer.h>
#include <lcfu___can_test.h>
#include <lcfu___chargestate.h>
#include <lcfu___cms_ivt.h>
#include <lcfu___dgtin.h>
#include <lcfu___essstate1.h>
#include <lcfu___flash.h>
#include <lcfu___gui.h>
#include <lcfu___guicfg_int.h>
#include <lcfu___guicfg_real.h>
#include <lcfu___hvcu_config.h>
#include <lcfu___hvcu_control_state.h>
#include <lcfu___iord.h>
#include <lcfu___iowr.h>
#include <lcfu___isabelinit.h>
#include <lcfu___max_min_voltage_status.h>
#include <lcfu___ntc.h>
#include <lcfu___numofcells.h>
#include <lcfu___prechargecan.h>
#include <lcfu___safety_power.h>
#include <lcfu___socisz.h>
#include <lcfu___tbuffer.h>
#include <lcfu___updowncnttim.h>
#include <lcfu_iec61131__ABS.h>
#include <lcfu_iec61131__ADD.h>
#include <lcfu_iec61131__AND.h>
#include <lcfu_iec61131__CONVERT.h>
#include <lcfu_iec61131__CTU.h>
#include <lcfu_iec61131__DIV.h>
#include <lcfu_iec61131__DIV_TIME.h>
#include <lcfu_iec61131__EQ.h>
#include <lcfu_iec61131__F_TRIG.h>
#include <lcfu_iec61131__GE.h>
#include <lcfu_iec61131__GT.h>
#include <lcfu_iec61131__LE.h>
#include <lcfu_iec61131__LIMIT.h>
#include <lcfu_iec61131__LT.h>
#include <lcfu_iec61131__MAX.h>
#include <lcfu_iec61131__MIN.h>
#include <lcfu_iec61131__MUL.h>
#include <lcfu_iec61131__MUX_ANY.h>
#include <lcfu_iec61131__NE.h>
#include <lcfu_iec61131__NOT.h>
#include <lcfu_iec61131__OR.h>
#include <lcfu_iec61131__R_TRIG.h>
#include <lcfu_iec61131__SEL_ANY.h>
#include <lcfu_iec61131__SR.h>
#include <lcfu_iec61131__SUB.h>
#include <lcfu_iec61131__TOF.h>
#include <lcfu_iec61131__TON.h>

/*                            Typedefs                         */
typedef struct _LC_TD_Program_HEMABATTERY
{
  LC_TD_BOOL LC_VD_ENO;
  LC_TD_BOOL LC_VD_ADDRBIT0;
  LC_TD_BOOL LC_VD_ADDRBIT1;
  LC_TD_BOOL LC_VD_ALLCONTACSTENABLE;
  LC_TD_BOOL LC_VD_BALANCESTATEENB;
  LC_TD_BOOL LC_VD_BALANCE_ENABLE_RQ;
  LC_TD_BOOL LC_VD_BATTERYCHARGING;
  LC_TD_BOOL LC_VD_BATTERYDISCHARGING;
  LC_TD_BOOL LC_VD_BATTERYINCHARGE;
  LC_TD_BOOL LC_VD_BATTSTACK_DISABLE;
  LC_TD_BOOL LC_VD_BCU_CHARGE_COMPLETE;
  LC_TD_BOOL LC_VD_BCU_FAULT_DANGER;
  LC_TD_BOOL LC_VD_BCU_FAULT_WARNING;
  LC_TD_BOOL LC_VD_CAN_DISABLE;
  LC_TD_BOOL LC_VD_CAN_FAULT_02;
  LC_TD_BOOL LC_VD_CAN_FAULT_03;
  LC_TD_BOOL LC_VD_CAN_FAULT_04;
  LC_TD_BOOL LC_VD_CAN_FAULT_05;
  LC_TD_BOOL LC_VD_CAN_FAULT_06;
  LC_TD_BOOL LC_VD_CAN_FAULT_07;
  LC_TD_BOOL LC_VD_CHARGEAMPENB;
  LC_TD_BOOL LC_VD_CHARGECMD;
  LC_TD_BOOL LC_VD_CHARGEENB;
  LC_TD_BOOL LC_VD_CHARGEOFF;
  LC_TD_BOOL LC_VD_CHARGEPROTECT;
  LC_TD_BOOL LC_VD_CMDTMT;
  LC_TD_BOOL LC_VD_CONTACTENABLE;
  LC_TD_BOOL LC_VD_CONTACTENABLECHARGE;
  LC_TD_BOOL LC_VD_CONTACTENABLECHARGE_BATT;
  LC_TD_BOOL LC_VD_CONTACTENABLE_BATT;
  LC_TD_BOOL LC_VD_CONTACTFBK;
  LC_TD_BOOL LC_VD_CONTACTFBKCHARGE;
  LC_TD_BOOL LC_VD_CONTACTFBKDISCHARGE;
  LC_TD_BOOL LC_VD_CONTACTNEGENABLE;
  LC_TD_BOOL LC_VD_CONTACTNEGENABLE_BATT;
  LC_TD_BOOL LC_VD_CURRENTPROTECTION;
  LC_TD_BOOL LC_VD_DECREASECHARGEAMP;
  LC_TD_BOOL LC_VD_DECREASEDISCHARGEAMP;
  LC_TD_BOOL LC_VD_DISCHARGEAMPENB;
  LC_TD_BOOL LC_VD_DISCHARGECMD;
  LC_TD_BOOL LC_VD_DISCHARGECOMPLETE;
  LC_TD_BOOL LC_VD_DISCHARGEENB;
  LC_TD_BOOL LC_VD_DISCHARGEOFF;
  LC_TD_BOOL LC_VD_DISCHARGEPROTECT;
  LC_TD_BOOL LC_VD_DISCHARGETERMINATE;
  LC_TD_BOOL LC_VD_EMERGENCYBTN;
  LC_TD_BOOL LC_VD_EPCSREQDATA;
  LC_TD_BOOL LC_VD_FAULTFORSTATE;
  LC_TD_BOOL LC_VD_FAULTMDLBALT;
  LC_TD_BOOL LC_VD_FAULT_CAN_COMMUNICATION;
  LC_TD_BOOL LC_VD_FAULT_CELL_OVER_TEMP_DANGER;
  LC_TD_BOOL LC_VD_FAULT_CELL_OVER_TEMP_WARNING;
  LC_TD_BOOL LC_VD_FAULT_CELL_OVER_VOLTAGE_DANGER;
  LC_TD_BOOL LC_VD_FAULT_CELL_OVER_VOLTAGE_WARNING;
  LC_TD_BOOL LC_VD_FAULT_CELL_UNDER_TEMP_DANGER;
  LC_TD_BOOL LC_VD_FAULT_CELL_UNDER_TEMP_WARNING;
  LC_TD_BOOL LC_VD_FAULT_CELL_UNDER_VOLTAGE_DANGER;
  LC_TD_BOOL LC_VD_FAULT_CELL_UNDER_VOLTAGE_WARNING;
  LC_TD_BOOL LC_VD_FAULT_DMCC_EXCEED;
  LC_TD_BOOL LC_VD_FAULT_DMDC_EXCEED;
  LC_TD_BOOL LC_VD_FAULT_PACK_BMU;
  LC_TD_BOOL LC_VD_FAULT_PACK_CHARGE_CONTACTOR;
  LC_TD_BOOL LC_VD_FAULT_PACK_CMS;
  LC_TD_BOOL LC_VD_FAULT_PACK_DISCHARGE_CONTACTOR;
  LC_TD_BOOL LC_VD_FAULT_PACK_HVIL_1;
  LC_TD_BOOL LC_VD_FAULT_PACK_HVIL_2;
  LC_TD_BOOL LC_VD_FAULT_PACK_NEGATIVE_CONTACTOR;
  LC_TD_BOOL LC_VD_FORCECHARGE;
  LC_TD_BOOL LC_VD_FORCEDISCHARGE;
  LC_TD_BOOL LC_VD_FORCENEGATIVE;
  LC_TD_BOOL LC_VD_HKM_DISCHARGECONTACT;
  LC_TD_BOOL LC_VD_HVIL1_STATUS;
  LC_TD_BOOL LC_VD_HVIL2_STATUS;
  LC_TD_BOOL LC_VD_IGNITION;
  LC_TD_BOOL LC_VD_IGNITION_KL15;
  LC_TD_BOOL LC_VD_IMDENABLE;
  LC_TD_BOOL LC_VD_INCREASECHARGEAMP;
  LC_TD_BOOL LC_VD_INCREASEDISCHARGEAMP;
  LC_TD_BOOL LC_VD_INPUTSGN1;
  LC_TD_BOOL LC_VD_INPUTSGN2;
  LC_TD_BOOL LC_VD_INPUTSGN3;
  LC_TD_BOOL LC_VD_MAINCHARGECOMPLETE;
  LC_TD_BOOL LC_VD_MEASURE_ALL;
  LC_TD_BOOL LC_VD_MEASURE_AUX;
  LC_TD_BOOL LC_VD_NEWBMU_RESET;
  LC_TD_BOOL LC_VD_NEW_CHG_CONTACT;
  LC_TD_BOOL LC_VD_NEW_CONTACTFBK1;
  LC_TD_BOOL LC_VD_NEW_CONTACTFBK2;
  LC_TD_BOOL LC_VD_NEW_DCHG_CONTACT;
  LC_TD_BOOL LC_VD_OC_FAULT;
  LC_TD_BOOL LC_VD_OC_WARNING;
  LC_TD_BOOL LC_VD_OT_DANGER;
  LC_TD_BOOL LC_VD_OT_DANGER_RISK;
  LC_TD_BOOL LC_VD_OUTPUTSGN1;
  LC_TD_BOOL LC_VD_OUTPUTSGN2;
  LC_TD_BOOL LC_VD_OV_DANGER;
  LC_TD_BOOL LC_VD_OV_DANGER_RISK;
  LC_TD_BOOL LC_VD_OV_FAULT;
  LC_TD_BOOL LC_VD_PDULED;
  LC_TD_BOOL LC_VD_PRECHARGEBOARDERR;
  LC_TD_BOOL LC_VD_PRECHARGECANERR;
  LC_TD_BOOL LC_VD_PRECHARGECOMPLETE;
  LC_TD_BOOL LC_VD_PRECHARGECOMPLETECHARGE;
  LC_TD_BOOL LC_VD_PRECHARGEENABLE;
  LC_TD_BOOL LC_VD_PRECHARGEENABLECHARGE;
  LC_TD_BOOL LC_VD_PRECHARGEERROR;
  LC_TD_BOOL LC_VD_RDY_TO_SLEEP;
  LC_TD_BOOL LC_VD_SELCLOCK;
  LC_TD_BOOL LC_VD_SELECTLASTONE;
  LC_TD_BOOL LC_VD_SHUTDOWNCMD;
  LC_TD_BOOL LC_VD_SHUTDOWNCOMPLETE;
  LC_TD_BOOL LC_VD_SHUTDOWNENB;
  LC_TD_BOOL LC_VD_SIM100NOTFOUND;
  LC_TD_BOOL LC_VD_SLAVEMODE;
  LC_TD_BOOL LC_VD_UT_DANGER;
  LC_TD_BOOL LC_VD_UT_DANGER_RISK;
  LC_TD_BOOL LC_VD_UV_DANGER;
  LC_TD_BOOL LC_VD_UV_DANGER_RISK;
  LC_TD_BOOL LC_VD_UV_FAULT;
  LC_TD_BOOL LC_VD_WARNINGMDLBALT;
  LC_TD_BOOL LC_VD___175_EQ;
  LC_TD_BOOL LC_VD___223_OR;
  LC_TD_BOOL LC_VD___243_NE;
  LC_TD_BOOL LC_VD___246_LT;
  LC_TD_BOOL LC_VD___259_OR;
  LC_TD_BOOL LC_VD___279_GE;
  LC_TD_BOOL LC_VD___286_LE;
  LC_TD_BOOL LC_VD___288_GE;
  LC_TD_BOOL LC_VD___303_EQ;
  LC_TD_BOOL LC_VD___328_AND;
  LC_TD_BOOL LC_VD___341_LT;
  LC_TD_BOOL LC_VD___364_GE;
  LC_TD_BOOL LC_VD___384_EQ;
  LC_TD_BOOL LC_VD___404_LE;
  LC_TD_BOOL LC_VD___510_NOT;
  LC_TD_BOOL LC_VD___542_OR;
  LC_TD_BOOL LC_VD___543_SEL;
  LC_TD_BOOL LC_VD___544_GE;
  LC_TD_BOOL LC_VD___657_GT;
  LC_TD_BOOL LC_VD___659_SEL;
  LC_TD_BOOL LC_VD___672_AND;
  LC_TD_BOOL LC_VD___742_GT;
  LC_TD_BOOL LC_VD___753_LT;
  LC_TD_BOOL LC_VD___755_GT;
  LC_TD_BOOL LC_VD___757_GE;
  LC_TD_BOOL LC_VD___793_EQ;
  LC_TD_BOOL LC_VD___803_LT;
  LC_TD_BOOL LC_VD___833_OR;
  LC_TD_BOOL LC_VD___850_EQ;
  LC_TD_BOOL LC_VD___859_EQ;
  LC_TD_BOOL LC_VD___874_GE;
  LC_TD_BOOL LC_VD___887_GE;
  LC_TD_BOOL LC_VD___897_GE;
  LC_TD_BOOL LC_VD___904_AND;
  LC_TD_BOOL LC_VD___906_OR;
  LC_TD_BOOL LC_VD___908_OR;
  LC_TD_BOOL LC_VD___917_GE;
  LC_TD_BOOL LC_VD___919_LE;
  LC_TD_BOOL LC_VD___920_GE;
  LC_TD_BOOL LC_VD___926_GT;
  LC_TD_BOOL LC_VD___932_NE;
  LC_TD_BOOL LC_VD___1073_LE;
  LC_TD_BOOL LC_VD___1082_SEL;
  LC_TD_BOOL LC_VD___1083_AND;
  LC_TD_BOOL LC_VD___1092_NE;
  LC_TD_BOOL LC_VD___1109_NE;
  LC_TD_BOOL LC_VD___1139_EQ;
  LC_TD_BOOL LC_VD___1226_OR;
  LC_TD_BOOL LC_VD___1227_TO_BOOL;
  LC_TD_BOOL LC_VD___1233_TO_BOOL;
  LC_TD_BOOL LC_VD___1239_TO_BOOL;
  LC_TD_BOOL LC_VD___1243_OR;
  LC_TD_BOOL LC_VD___1259_LT;
  LC_TD_BOOL LC_VD___1274_LT;
  LC_TD_BOOL LC_VD___1278_OR;
  LC_TD_BOOL LC_VD___1282_OR;
  LC_TD_BOOL LC_VD___1283_LT;
  LC_TD_BOOL LC_VD___1291_AND;
  LC_TD_BOOL LC_VD___1296_GT;
  LC_TD_BOOL LC_VD___1300_AND;
  LC_TD_BOOL LC_VD___1304_OR;
  LC_TD_BOOL LC_VD___1313_AND;
  LC_TD_BOOL LC_VD___1315_OR;
  LC_TD_BOOL LC_VD___1319_LE;
  LC_TD_BOOL LC_VD___1324_LT;
  LC_TD_BOOL LC_VD___1375_AND;
  LC_TD_BOOL LC_VD___1379_GT;
  LC_TD_BOOL LC_VD___1450_OR;
  LC_TD_BOOL LC_VD___1580_GE;
  LC_TD_BOOL LC_VD___1582_LE;
  LC_TD_BOOL LC_VD___1640_AND;
  LC_TD_BOOL LC_VD___1642_SEL;
  LC_TD_BOOL LC_VD___1646_AND;
  LC_TD_BOOL LC_VD___1648_SEL;
  LC_TD_BOOL LC_VD___1658_EQ;
  LC_TD_BOOL LC_VD___1669_LT;
  LC_TD_BOOL LC_VD___1684_GT;
  LC_TD_BOOL LC_VD___1702_AND;
  LC_TD_BOOL LC_VD___1706_OR;
  LC_TD_BOOL LC_VD___1709_OR;
  LC_TD_BOOL LC_VD___1713_EQ;
  LC_TD_BOOL LC_VD___1719_OR;
  LC_TD_BOOL LC_VD___1795_EQ;
  LC_TD_BOOL LC_VD___1813_OR;
  LC_TD_BOOL LC_VD___1819_OR;
  LC_TD_BOOL LC_VD___1825_GT;
  LC_TD_BOOL LC_VD___1847_LE;
  LC_TD_BOOL LC_VD___1864_AND;
  LC_TD_BOOL LC_VD___1887_OR;
  LC_TD_BOOL LC_VD___1957_EQ;
  LC_TD_BOOL LC_VD___1958_SEL;
  LC_TD_BOOL LC_VD___2011_OR;
  LC_TD_BOOL LC_VD___2028_GE;
  LC_TD_BOOL LC_VD___2030_OR;
  LC_TD_BOOL LC_VD___2056_OR;
  LC_TD_BOOL LC_VD___2092_GT;
  LC_TD_BOOL LC_VD___2101_OR;
  LC_TD_BOOL LC_VD___2103_AND;
  LC_TD_BOOL LC_VD___2110_OR;
  LC_TD_BOOL LC_VD___2154_NOT;
  LC_TD_BOOL LC_VD___2185_SEL;
  LC_TD_BOOL LC_VD___2322_OR;
  LC_TD_BOOL LC_VD___2358_AND;
  LC_TD_BOOL LC_VD___2595_GE;
  LC_TD_BOOL LC_VD___2605_LE;
  LC_TD_BOOL LC_VD___2618_AND;
  LC_TD_BOOL LC_VD___2624_OR;
  LC_TD_BOOL LC_VD___2630_AND;
  LC_TD_BOOL LC_VD___3227_AND;
  LC_TD_BOOL LC_VD___3228_GT;
  LC_TD_BOOL LC_VD___3232_LT;
  LC_TD_BOOL LC_VD___3233_GT;
  LC_TD_BOOL LC_VD___3234_AND;
  LC_TD_BOOL LC_VD___3237_LT;
  LC_TD_SINT LC_VD_BMUMAXCELLT;
  LC_TD_SINT LC_VD_BMUMINCELLT;
  LC_TD_USINT LC_VD_BALCHARGEST;
  LC_TD_USINT LC_VD_CELL_SERIES_CONNECTION;
  LC_TD_USINT LC_VD_CELL_TEMP_MAX_BMU_LOC;
  LC_TD_USINT LC_VD_CELL_TEMP_MAX_CELL_LOC;
  LC_TD_USINT LC_VD_CELL_TEMP_MIN_BMU_LOC;
  LC_TD_USINT LC_VD_CELL_TEMP_MIN_CELL_LOC;
  LC_TD_USINT LC_VD_CELL_VOLTAGE_MAX_BMU_LOC;
  LC_TD_USINT LC_VD_CELL_VOLTAGE_MAX_CELL_LOC;
  LC_TD_USINT LC_VD_CELL_VOLTAGE_MIN_BMU_LOC;
  LC_TD_USINT LC_VD_CELL_VOLTAGE_MIN_CELL_LOC;
  LC_TD_USINT LC_VD_CMDBCU;
  LC_TD_USINT LC_VD_HVCU_STATE;
  LC_TD_USINT LC_VD_INPUTSGN1STATUS;
  LC_TD_USINT LC_VD_INPUTSGN2STATUS;
  LC_TD_USINT LC_VD_ISOLATIONSTATUS;
  LC_TD_USINT LC_VD_NUMBER_OF_BMU;
  LC_TD_USINT LC_VD_NUMBER_OF_BMU_CFG;
  LC_TD_USINT LC_VD_NUMBER_OF_MAXCELL2;
  LC_TD_USINT LC_VD_NUMBER_OF_PARALLEL_CELL;
  LC_TD_USINT LC_VD_PRECHARGESTATUS;
  LC_TD_USINT LC_VD_SELECTED_BMU_LOC;
  LC_TD_USINT LC_VD_SELECTED_CELL_LOC;
  LC_TD_USINT LC_VD_SELECTED_PACK_NUMBER;
  LC_TD_USINT LC_VD_SOC_CC;
  LC_TD_USINT LC_VD_SOH;
  LC_TD_USINT LC_VD_TESTSOCSTATE;
  LC_TD_USINT LC_VD___61_TO_USINT;
  LC_TD_USINT LC_VD___91_MUX_USINT;
  LC_TD_USINT LC_VD___765_TO_USINT;
  LC_TD_USINT LC_VD___766_TO_USINT;
  LC_TD_USINT LC_VD___933_TO_USINT;
  LC_TD_USINT LC_VD___1002_TO_USINT;
  LC_TD_USINT LC_VD___1079_TO_USINT;
  LC_TD_USINT LC_VD___1981_TO_USINT;
  LC_TD_USINT LC_VD___1995_TO_USINT;
  LC_TD_USINT LC_VD___2255_MUX_USINT;
  LC_TD_BYTE LC_VD_BATTERYID;
  LC_TD_BYTE LC_VD_HW_VERSION;
  LC_TD_BYTE LC_VD_MASTERID;
  LC_TD_BYTE LC_VD_SIM100_ERRBYTE;
  LC_TD_INT LC_VD___1771_TO_INT;
  LC_TD_INT LC_VD___1772_TO_INT;
  LC_TD_UINT LC_VD_AN_KL15;
  LC_TD_UINT LC_VD_BALANCE_REGISTER;
  LC_TD_UINT LC_VD_BMUMAXCELLV;
  LC_TD_UINT LC_VD_BMUMINCELLV;
  LC_TD_UINT LC_VD_CELLVOLT_BALTHRES;
  LC_TD_UINT LC_VD_CELLVOLT_CHARGEOK;
  LC_TD_UINT LC_VD_CELLVOLT_CUTOFFHIGH;
  LC_TD_UINT LC_VD_CELLVOLT_CUTOFFLOW;
  LC_TD_UINT LC_VD_CELLVOLT_DISCHARGEOK;
  LC_TD_UINT LC_VD_CELLVOLT_MAX;
  LC_TD_UINT LC_VD_CELLVOLT_MAXCHARGE;
  LC_TD_UINT LC_VD_CELLVOLT_MIN;
  LC_TD_UINT LC_VD_CELLVOLT_MINDISCHARGE;
  LC_TD_UINT LC_VD_CELLVOLT_WARNINGOV;
  LC_TD_UINT LC_VD_CELLVOLT_WARNINGUV;
  LC_TD_UINT LC_VD_CELL_VOLTAGE_MAX_CHARGE;
  LC_TD_UINT LC_VD_CELL_VOLTAGE_MIN_DISHARGE;
  LC_TD_UINT LC_VD_CHARGE_CURRENT;
  LC_TD_UINT LC_VD_CYCLESPERSOH;
  LC_TD_UINT LC_VD_DUTY_CYCLE;
  LC_TD_UINT LC_VD_MAXCHARGEAMPRCFG;
  LC_TD_UINT LC_VD_MAXDISCHARGEAMPRCFG;
  LC_TD_UINT LC_VD_NUMBER_OF_CELL;
  LC_TD_UINT LC_VD_NUMBER_OF_MAXCELL;
  LC_TD_UINT LC_VD_OCFAULTAMPR;
  LC_TD_UINT LC_VD_OCWARNINGAMPR;
  LC_TD_UINT LC_VD_PACK_DMCC;
  LC_TD_UINT LC_VD_PACK_DMDC;
  LC_TD_UINT LC_VD___23_TO_UINT;
  LC_TD_UINT LC_VD___415_TO_UINT;
  LC_TD_UINT LC_VD___419_TO_UINT;
  LC_TD_UINT LC_VD___420_TO_UINT;
  LC_TD_UINT LC_VD___421_TO_UINT;
  LC_TD_UINT LC_VD___422_TO_UINT;
  LC_TD_UINT LC_VD___423_TO_UINT;
  LC_TD_UINT LC_VD___424_TO_UINT;
  LC_TD_UINT LC_VD___425_TO_UINT;
  LC_TD_UINT LC_VD___868_MIN;
  LC_TD_UINT LC_VD___869_TO_UINT;
  LC_TD_UINT LC_VD___998_TO_UINT;
  LC_TD_UINT LC_VD___1169_TO_UINT;
  LC_TD_UINT LC_VD___1184_MIN;
  LC_TD_UINT LC_VD___1194_MIN;
  LC_TD_UINT LC_VD___1401_TO_UINT;
  LC_TD_UINT LC_VD___1426_TO_UINT;
  LC_TD_UINT LC_VD___1466_TO_UINT;
  LC_TD_UINT LC_VD___1477_TO_UINT;
  LC_TD_UINT LC_VD___1486_TO_UINT;
  LC_TD_UINT LC_VD___1497_TO_UINT;
  LC_TD_UINT LC_VD___1509_TO_UINT;
  LC_TD_UINT LC_VD___1534_TO_UINT;
  LC_TD_UINT LC_VD___1538_TO_UINT;
  LC_TD_UINT LC_VD___1567_TO_UINT;
  LC_TD_UINT LC_VD___1574_TO_UINT;
  LC_TD_UINT LC_VD___1731_TO_UINT;
  LC_TD_UINT LC_VD___1745_TO_UINT;
  LC_TD_UINT LC_VD___1788_TO_UINT;
  LC_TD_UINT LC_VD___1789_TO_UINT;
  LC_TD_UINT LC_VD___1799_TO_UINT;
  LC_TD_UINT LC_VD___1985_DIV;
  LC_TD_UINT LC_VD___1990_SUB;
  LC_TD_UINT LC_VD___1993_LIMIT;
  LC_TD_UINT LC_VD___2096_TO_UINT;
  LC_TD_UDINT LC_VD_BALANCEDIFF_THRESHOLD;
  LC_TD_UDINT LC_VD_BALANCE_VOLTAGE;
  LC_TD_UDINT LC_VD_BOARD_ERROR_MESSAGES;
  LC_TD_UDINT LC_VD_BOARD_FAULT_MESSAGES;
  LC_TD_UDINT LC_VD_CAN_ID_10;
  LC_TD_UDINT LC_VD_CAN_ID_11;
  LC_TD_UDINT LC_VD_CAN_ID_12;
  LC_TD_UDINT LC_VD_CAN_ID_13;
  LC_TD_UDINT LC_VD_CAN_ID_14;
  LC_TD_UDINT LC_VD_CAN_ID_15;
  LC_TD_UDINT LC_VD_CAN_ID_16;
  LC_TD_UDINT LC_VD_CELLVOLT_NOMINAL;
  LC_TD_UDINT LC_VD_CELL_CURRENT_NOMINAL;
  LC_TD_UDINT LC_VD_CELL_VOLTAGE;
  LC_TD_UDINT LC_VD_CELL_VOLTAGE_AVERAGE;
  LC_TD_UDINT LC_VD_CELL_VOLTAGE_MAX;
  LC_TD_UDINT LC_VD_CELL_VOLTAGE_MIN;
  LC_TD_UDINT LC_VD_GUI_FAULT;
  LC_TD_UDINT LC_VD_ISOOHMPERV;
  LC_TD_UDINT LC_VD_ISORN;
  LC_TD_UDINT LC_VD_ISORP;
  LC_TD_UDINT LC_VD_NTCBETA;
  LC_TD_UDINT LC_VD_PRECHARGEINTERVAL;
  LC_TD_UDINT LC_VD___74_MUL;
  LC_TD_UDINT LC_VD___733_TO_UDINT;
  LC_TD_UDINT LC_VD___2174_TO_UDINT;
  LC_TD_UDINT LC_VD___2201_TO_UDINT;
  LC_TD_DWORD LC_VD___934_AND;
  LC_TD_DWORD LC_VD___1213_TO_DWORD;
  LC_TD_DWORD LC_VD___1215_AND;
  LC_TD_DWORD LC_VD___1229_AND;
  LC_TD_REAL LC_VD_BATTERYCURRENT;
  LC_TD_REAL LC_VD_BATTERYVOLTAGE;
  LC_TD_REAL LC_VD_BATTERYWATT;
  LC_TD_REAL LC_VD_BMSDMCC_FINAL;
  LC_TD_REAL LC_VD_BMSDMCC_MAIN;
  LC_TD_REAL LC_VD_BMSDMDC_FINAL;
  LC_TD_REAL LC_VD_CELLTEMP_MAXLIM;
  LC_TD_REAL LC_VD_CELLTEMP_MINLIM;
  LC_TD_REAL LC_VD_CELLTEMP_WARNINGOT;
  LC_TD_REAL LC_VD_CELLTEMP_WARNINGUT;
  LC_TD_REAL LC_VD_CELL_TEMP;
  LC_TD_REAL LC_VD_CELL_TEMP_MAX;
  LC_TD_REAL LC_VD_CELL_TEMP_MIN;
  LC_TD_REAL LC_VD_CHARGEINVOLTAGE;
  LC_TD_REAL LC_VD_CHARGEOK_VOLTAGE_PACK;
  LC_TD_REAL LC_VD_CHARGEUNITAMP;
  LC_TD_REAL LC_VD_CMD_COUNTER_CURRENT;
  LC_TD_REAL LC_VD_CMD_CURRENT_SENSE;
  LC_TD_REAL LC_VD_CMD_CURRENT_SENSE_AMP;
  LC_TD_REAL LC_VD_CMD_POWER;
  LC_TD_REAL LC_VD_CMD_TEMP;
  LC_TD_REAL LC_VD_CMD_VOLTAGE_SENSE1_VOLT;
  LC_TD_REAL LC_VD_CMD_VOLTAGE_SENSE2_VOLT;
  LC_TD_REAL LC_VD_CMD_VOLTAGE_SENSE_1;
  LC_TD_REAL LC_VD_CMD_VOLTAGE_SENSE_2;
  LC_TD_REAL LC_VD_CMD_VOLTAGE_SENSE_3;
  LC_TD_REAL LC_VD_CMS0VOLT1;
  LC_TD_REAL LC_VD_CMS1VOLT1;
  LC_TD_REAL LC_VD_DICHARGEOK_VOLTAGE_PACK;
  LC_TD_REAL LC_VD_DISCHARGEINVOLTAGE;
  LC_TD_REAL LC_VD_DISCHARGEUNITAMP;
  LC_TD_REAL LC_VD_DOD_RATE;
  LC_TD_REAL LC_VD_HKM_DISCHARGEINVOLTAGE;
  LC_TD_REAL LC_VD_INSTANTPOWER;
  LC_TD_REAL LC_VD_KWHCAPACITY;
  LC_TD_REAL LC_VD_MAXCHARGEAMP;
  LC_TD_REAL LC_VD_MAXDISCHARGEAMP;
  LC_TD_REAL LC_VD_MULTAMPCHAR;
  LC_TD_REAL LC_VD_MULTAMPDISCH;
  LC_TD_REAL LC_VD_OUTPUTVOLTAGE;
  LC_TD_REAL LC_VD_PACKREMCAP_KWH;
  LC_TD_REAL LC_VD_PACK_CHARGE_VOLTAGE;
  LC_TD_REAL LC_VD_PACK_CUTOFFHIGH_VOLTAGE;
  LC_TD_REAL LC_VD_PACK_CUTOFFLOW_VOLTAGE;
  LC_TD_REAL LC_VD_PACK_CUTOFFV_LOW;
  LC_TD_REAL LC_VD_PACK_DISCHARGE_VOLTAGE;
  LC_TD_REAL LC_VD_PACK_TEMPERATURE;
  LC_TD_REAL LC_VD_SOCCHCOMP;
  LC_TD_REAL LC_VD_SOCDCHCOMP;
  LC_TD_REAL LC_VD_SOCREAL;
  LC_TD_REAL LC_VD_TESTREMWH;
  LC_TD_REAL LC_VD_TOTAL_VOLTAGE;
  LC_TD_REAL LC_VD_USABLECAPKWH;
  LC_TD_REAL LC_VD_USABLECAPWH;
  LC_TD_REAL LC_VD_USABLEREMKWH;
  LC_TD_REAL LC_VD_USABLEREMWH;
  LC_TD_REAL LC_VD_VOLTSAMPLE1;
  LC_TD_REAL LC_VD_VOLTSAMPLE2;
  LC_TD_REAL LC_VD_WHCAPACITY;
  LC_TD_REAL LC_VD_WHINSTANT;
  LC_TD_REAL LC_VD___43_DIV;
  LC_TD_REAL LC_VD___64_MAX;
  LC_TD_REAL LC_VD___73_TO_REAL;
  LC_TD_REAL LC_VD___75_DIV;
  LC_TD_REAL LC_VD___77_MUL;
  LC_TD_REAL LC_VD___265_TO_REAL;
  LC_TD_REAL LC_VD___276_SUB;
  LC_TD_REAL LC_VD___277_ADD;
  LC_TD_REAL LC_VD___336_DIV;
  LC_TD_REAL LC_VD___435_SEL;
  LC_TD_REAL LC_VD___459_DIV;
  LC_TD_REAL LC_VD___479_MUL;
  LC_TD_REAL LC_VD___502_MUL;
  LC_TD_REAL LC_VD___509_DIV;
  LC_TD_REAL LC_VD___517_MUL;
  LC_TD_REAL LC_VD___582_SUB;
  LC_TD_REAL LC_VD___778_DIV;
  LC_TD_REAL LC_VD___816_DIV;
  LC_TD_REAL LC_VD___838_MIN;
  LC_TD_REAL LC_VD___861_SEL;
  LC_TD_REAL LC_VD___944_SUB;
  LC_TD_REAL LC_VD___958_MUL;
  LC_TD_REAL LC_VD___959_DIV;
  LC_TD_REAL LC_VD___962_TO_REAL;
  LC_TD_REAL LC_VD___971_MUL;
  LC_TD_REAL LC_VD___972_TO_REAL;
  LC_TD_REAL LC_VD___975_DIV;
  LC_TD_REAL LC_VD___1016_MUL;
  LC_TD_REAL LC_VD___1195_MIN;
  LC_TD_REAL LC_VD___1201_MUL;
  LC_TD_REAL LC_VD___1258_ABS;
  LC_TD_REAL LC_VD___1352_DIV;
  LC_TD_REAL LC_VD___1353_MUL;
  LC_TD_REAL LC_VD___1367_MUL;
  LC_TD_REAL LC_VD___1520_DIV;
  LC_TD_REAL LC_VD___1613_TO_REAL;
  LC_TD_REAL LC_VD___1616_TO_REAL;
  LC_TD_REAL LC_VD___1623_TO_REAL;
  LC_TD_REAL LC_VD___1630_TO_REAL;
  LC_TD_REAL LC_VD___1762_DIV;
  LC_TD_REAL LC_VD___1770_DIV;
  LC_TD_REAL LC_VD___1780_TO_REAL;
  LC_TD_REAL LC_VD___1781_TO_REAL;
  LC_TD_REAL LC_VD___1782_MUL;
  LC_TD_REAL LC_VD___1783_MUL;
  LC_TD_REAL LC_VD___1787_SEL;
  LC_TD_REAL LC_VD___1790_SEL;
  LC_TD_REAL LC_VD___1848_MAX;
  LC_TD_REAL LC_VD___1872_MUL;
  LC_TD_REAL LC_VD___1880_DIV;
  LC_TD_REAL LC_VD___1889_MUL;
  LC_TD_REAL LC_VD___2073_MUL;
  LC_TD_REAL LC_VD___2077_DIV;
  LC_TD_REAL LC_VD___2251_ABS;
  LC_TD_REAL LC_VD___3229_ABS;
  LC_TD_REAL LC_VD___3231_SUB;
  LC_TD_REAL LC_VD___3235_ABS;
  LC_TD_REAL LC_VD___3236_SUB;
  LC_TD_LWORD LC_VD_FAULTSWORD;
  LC_TD_LREAL LC_VD_CMD_OVERALL_POWER;
  LC_TD_LREAL LC_VD___1978_DIV;
  LC_TD_TIME LC_VD_TESTVALUE0;
  LC_TD_TIME LC_VD___1172_TO_TIME;
  LC_TD_TIME LC_VD___1176_DIV_TIME;
  LC_TD_TIME LC_VD___3224_TO_TIME;
  LC_TD_TIME LC_VD___3225_DIV_TIME;
  LC_TD_FunctionBlock_AMPMULTTEMP LC_VD_AMPMULTTEMP1;
  LC_TD_FunctionBlock_AMPMULTTEMP LC_VD_AMPMULTTEMP2;
  LC_TD_FunctionBlock_AMPMULTTEMPDIS LC_VD_AMPMULTTEMPDIS1;
  LC_TD_FunctionBlock_AMPMULTTEMPDIS LC_VD_AMPMULTTEMPDIS2;
  LC_TD_FunctionBlock_AMPMULTVOLTCHAR LC_VD_AMPMULTVOLTCHAR1;
  LC_TD_FunctionBlock_AMPMULTVOLTDISC LC_VD_AMPMULTVOLTDISC1;
  LC_TD_FunctionBlock_ANLG LC_VD_ANLG1;
  LC_TD_FunctionBlock_ANLG LC_VD_ANLG2;
  LC_TD_FunctionBlock_ANLG LC_VD_ANLG3;
  LC_TD_FunctionBlock_ANLG LC_VD_ANLG4;
  LC_TD_FunctionBlock_ANLG LC_VD_ANLG8;
  LC_TD_FunctionBlock_ANLG LC_VD_ANLG14;
  LC_TD_FunctionBlock_ARR2VAL LC_VD_ARR2VAL2;
  LC_TD_FunctionBlock_BALANCE_ISZ LC_VD_BALANCE_ISZ1;
  LC_TD_DataType_BESSALARMS LC_VD_BATEPCSALARM;
  LC_TD_FunctionBlock_BATTSTACK LC_VD_BATTSTACK1;
  LC_TD_FunctionBlock_BCU_BATTERY_STATUS LC_VD_BCU_BATTERY_STATUS1;
  LC_TD_DataType_TMS570_CAN LC_VD_BCU_CAN_CH;
  LC_TD_FunctionBlock_BCU_CELL_STATUS LC_VD_BCU_CELL_STATUS1;
  LC_TD_FunctionBlock_BCU_FAULT_CODES LC_VD_BCU_FAULT_CODES1;
  LC_TD_FunctionBlock_BCU_ID LC_VD_BCU_ID1;
  LC_TD_FunctionBlock_BCU_STATE_MESSAGE LC_VD_BCU_STATE_MESSAGE1;
  LC_TD_FunctionBlock_BCU_STATUS2 LC_VD_BCU_STATUS21;
  LC_TD_DataType_BESSOPRSTATUS LC_VD_BESSOPERATINGSTATUS;
  LC_TD_DataType_BESSSYSTEMSTATUS LC_VD_BESSSTATUS;
  LC_TD_DataType_BESSWORKMODE LC_VD_BESSWORKINGMODE;
  LC_TD_DataType_BATTSTATE LC_VD_BMS_STATE;
  LC_TD_SINT LC_VD_BMUCELLTEMP[16];
  LC_TD_UINT LC_VD_BMUCELLVOLT[16];
  LC_TD_FunctionBlock_BUFFER LC_VD_BUFFER1;
  LC_TD_FunctionBlock_BUFFER LC_VD_BUFFER2;
  LC_TD_FunctionBlock_BUFFER LC_VD_BUFFER3;
  LC_TD_FunctionBlock_BUFFER LC_VD_BUFFER4;
  LC_TD_FunctionBlock_BUFFER LC_VD_BUFFER9;
  LC_TD_FunctionBlock_BUFFER LC_VD_BUFFER10;
  LC_TD_FunctionBlock_BUFFER LC_VD_BUFFER11;
  LC_TD_FunctionBlock_BUFFER LC_VD_BUFFER12;
  LC_TD_FunctionBlock_BUFFER LC_VD_BUFFER13;
  LC_TD_FunctionBlock_BUFFER LC_VD_BUFFER19;
  LC_TD_FunctionBlock_BUFFER LC_VD_BUFFER21;
  LC_TD_FunctionBlock_BUFFER LC_VD_BUFFER22;
  LC_TD_FunctionBlock_BUFFER LC_VD_BUFFER23;
  LC_TD_FunctionBlock_CAN_TEST LC_VD_CAN_TEST1;
  LC_TD_FunctionBlock_CAN_TEST LC_VD_CAN_TEST2;
  LC_TD_DataType_PLCHANNEL LC_VD_CHANNELSELECT[16];
  LC_TD_DataType_PLCHANNEL LC_VD_CHANNELSELECT2[16];
  LC_TD_FunctionBlock_CHARGESTATE LC_VD_CHARGESTATE1;
  LC_TD_FunctionBlock_CMS_IVT LC_VD_CMS_IVT1;
  LC_TD_FunctionBlock_CTU LC_VD_CTU1;
  LC_TD_FunctionBlock_CTU LC_VD_CTU2;
  LC_TD_FunctionBlock_DGTIN LC_VD_DGTIN3;
  LC_TD_FunctionBlock_DGTIN LC_VD_DGTIN4;
  LC_TD_FunctionBlock_DGTIN LC_VD_DGTIN8;
  LC_TD_DataType_TMS570_CAN LC_VD_EPCS_CAN_CH;
  LC_TD_FunctionBlock_ESSSTATE1 LC_VD_ESSSTATE11;
  LC_TD_FunctionBlock_FLASH LC_VD_FLASH1;
  LC_TD_FunctionBlock_FLASH LC_VD_FLASH3;
  LC_TD_FunctionBlock_FLASH LC_VD_FLASH4;
  LC_TD_FunctionBlock_F_TRIG LC_VD_F_TRIG1;
  LC_TD_FunctionBlock_F_TRIG LC_VD_F_TRIG2;
  LC_TD_FunctionBlock_F_TRIG LC_VD_F_TRIG3;
  LC_TD_FunctionBlock_F_TRIG LC_VD_F_TRIG4;
  LC_TD_FunctionBlock_GUI LC_VD_GUI1;
  LC_TD_FunctionBlock_GUICFG_INT LC_VD_GUICFG_INT1;
  LC_TD_FunctionBlock_GUICFG_INT LC_VD_GUICFG_INT2;
  LC_TD_FunctionBlock_GUICFG_INT LC_VD_GUICFG_INT3;
  LC_TD_FunctionBlock_GUICFG_INT LC_VD_GUICFG_INT4;
  LC_TD_FunctionBlock_GUICFG_INT LC_VD_GUICFG_INT5;
  LC_TD_FunctionBlock_GUICFG_INT LC_VD_GUICFG_INT6;
  LC_TD_FunctionBlock_GUICFG_INT LC_VD_GUICFG_INT7;
  LC_TD_FunctionBlock_GUICFG_INT LC_VD_GUICFG_INT8;
  LC_TD_FunctionBlock_GUICFG_INT LC_VD_GUICFG_INT9;
  LC_TD_FunctionBlock_GUICFG_INT LC_VD_GUICFG_INT10;
  LC_TD_FunctionBlock_GUICFG_INT LC_VD_GUICFG_INT11;
  LC_TD_FunctionBlock_GUICFG_INT LC_VD_GUICFG_INT12;
  LC_TD_FunctionBlock_GUICFG_INT LC_VD_GUICFG_INT13;
  LC_TD_FunctionBlock_GUICFG_INT LC_VD_GUICFG_INT14;
  LC_TD_FunctionBlock_GUICFG_INT LC_VD_GUICFG_INT15;
  LC_TD_FunctionBlock_GUICFG_INT LC_VD_GUICFG_INT16;
  LC_TD_FunctionBlock_GUICFG_INT LC_VD_GUICFG_INT17;
  LC_TD_FunctionBlock_GUICFG_INT LC_VD_GUICFG_INT18;
  LC_TD_FunctionBlock_GUICFG_INT LC_VD_GUICFG_INT19;
  LC_TD_FunctionBlock_GUICFG_INT LC_VD_GUICFG_INT20;
  LC_TD_FunctionBlock_GUICFG_INT LC_VD_GUICFG_INT21;
  LC_TD_FunctionBlock_GUICFG_INT LC_VD_GUICFG_INT22;
  LC_TD_FunctionBlock_GUICFG_INT LC_VD_GUICFG_INT23;
  LC_TD_FunctionBlock_GUICFG_INT LC_VD_GUICFG_INT24;
  LC_TD_FunctionBlock_GUICFG_INT LC_VD_GUICFG_INT25;
  LC_TD_FunctionBlock_GUICFG_INT LC_VD_GUICFG_INT26;
  LC_TD_FunctionBlock_GUICFG_INT LC_VD_GUICFG_INT27;
  LC_TD_FunctionBlock_GUICFG_INT LC_VD_GUICFG_INT28;
  LC_TD_FunctionBlock_GUICFG_REAL LC_VD_GUICFG_REAL1;
  LC_TD_FunctionBlock_HVCU_CONFIG LC_VD_HVCU_CONFIG1;
  LC_TD_FunctionBlock_HVCU_CONTROL_STATE LC_VD_HVCU_CONTROL_STATE2;
  LC_TD_FunctionBlock_IORD LC_VD_IORD1;
  LC_TD_FunctionBlock_IORD LC_VD_IORD2;
  LC_TD_FunctionBlock_IORD LC_VD_IORD3;
  LC_TD_FunctionBlock_IORD LC_VD_IORD4;
  LC_TD_FunctionBlock_IORD LC_VD_IORD5;
  LC_TD_FunctionBlock_IOWR LC_VD_IOWR1;
  LC_TD_FunctionBlock_IOWR LC_VD_IOWR2;
  LC_TD_FunctionBlock_IOWR LC_VD_IOWR4;
  LC_TD_FunctionBlock_IOWR LC_VD_IOWR5;
  LC_TD_FunctionBlock_IOWR LC_VD_IOWR6;
  LC_TD_FunctionBlock_IOWR LC_VD_IOWR7;
  LC_TD_FunctionBlock_IOWR LC_VD_IOWR9;
  LC_TD_FunctionBlock_IOWR LC_VD_IOWR10;
  LC_TD_FunctionBlock_IOWR LC_VD_IOWR13;
  LC_TD_FunctionBlock_IOWR LC_VD_IOWR18;
  LC_TD_FunctionBlock_IOWR LC_VD_IOWR19;
  LC_TD_FunctionBlock_IOWR LC_VD_IOWR20;
  LC_TD_FunctionBlock_IOWR LC_VD_IOWR21;
  LC_TD_FunctionBlock_IOWR LC_VD_IOWR22;
  LC_TD_FunctionBlock_IOWR LC_VD_IOWR23;
  LC_TD_FunctionBlock_IOWR LC_VD_IOWR24;
  LC_TD_FunctionBlock_ISABELINIT LC_VD_ISABELINIT1;
  LC_TD_FunctionBlock_MAX_MIN_VOLTAGE_STATUS LC_VD_MAX_MIN_VOLTAGE_STATUS1;
  LC_TD_FunctionBlock_NTC LC_VD_NTC2;
  LC_TD_USINT LC_VD_NUMOFCELLS[16];
  LC_TD_FunctionBlock_NUMOFCELLS LC_VD_NUMOFCELLS1;
  LC_TD_DataType_TMS570_CAN LC_VD_PDUCAN;
  LC_TD_FunctionBlock_PRECHARGECAN LC_VD_PRECHARGECAN1;
  LC_TD_FunctionBlock_R_TRIG LC_VD_R_TRIG2;
  LC_TD_FunctionBlock_R_TRIG LC_VD_R_TRIG3;
  LC_TD_FunctionBlock_R_TRIG LC_VD_R_TRIG8;
  LC_TD_FunctionBlock_R_TRIG LC_VD_R_TRIG9;
  LC_TD_FunctionBlock_SAFETY_POWER LC_VD_SAFETY_POWER1;
  LC_TD_FunctionBlock_SOCISZ LC_VD_SOCISZ1;
  LC_TD_FunctionBlock_SR LC_VD_SR1;
  LC_TD_FunctionBlock_SR LC_VD_SR2;
  LC_TD_FunctionBlock_SR LC_VD_SR5;
  LC_TD_USINT LC_VD_TAUXCELLS[16];
  LC_TD_FunctionBlock_TBUFFER LC_VD_TBUFFER1;
  LC_TD_FunctionBlock_TBUFFER LC_VD_TBUFFER2;
  LC_TD_FunctionBlock_TBUFFER LC_VD_TBUFFER4;
  LC_TD_FunctionBlock_TBUFFER LC_VD_TBUFFER6;
  LC_TD_FunctionBlock_TBUFFER LC_VD_TBUFFER7;
  LC_TD_FunctionBlock_TBUFFER LC_VD_TBUFFER15;
  LC_TD_FunctionBlock_TBUFFER LC_VD_TBUFFER16;
  LC_TD_FunctionBlock_TBUFFER LC_VD_TBUFFER19;
  LC_TD_FunctionBlock_TBUFFER LC_VD_TBUFFER20;
  LC_TD_FunctionBlock_TOF LC_VD_TOF1;
  LC_TD_FunctionBlock_TOF LC_VD_TOF2;
  LC_TD_FunctionBlock_TOF LC_VD_TOF3;
  LC_TD_FunctionBlock_TOF LC_VD_TOF4;
  LC_TD_FunctionBlock_TOF LC_VD_TOF5;
  LC_TD_FunctionBlock_TOF LC_VD_TOF6;
  LC_TD_FunctionBlock_TOF LC_VD_TOF7;
  LC_TD_FunctionBlock_TOF LC_VD_TOF8;
  LC_TD_FunctionBlock_TOF LC_VD_TOF9;
  LC_TD_FunctionBlock_TOF LC_VD_TOF10;
  LC_TD_FunctionBlock_TOF LC_VD_TOF12;
  LC_TD_FunctionBlock_TOF LC_VD_TOF13;
  LC_TD_FunctionBlock_TOF LC_VD_TOF14;
  LC_TD_FunctionBlock_TOF LC_VD_TOF15;
  LC_TD_FunctionBlock_TON LC_VD_TON1;
  LC_TD_FunctionBlock_TON LC_VD_TON2;
  LC_TD_FunctionBlock_TON LC_VD_TON4;
  LC_TD_FunctionBlock_TON LC_VD_TON5;
  LC_TD_FunctionBlock_TON LC_VD_TON6;
  LC_TD_FunctionBlock_TON LC_VD_TON7;
  LC_TD_FunctionBlock_TON LC_VD_TON8;
  LC_TD_FunctionBlock_TON LC_VD_TON9;
  LC_TD_FunctionBlock_TON LC_VD_TON10;
  LC_TD_FunctionBlock_TON LC_VD_TON11;
  LC_TD_FunctionBlock_TON LC_VD_TON12;
  LC_TD_FunctionBlock_TON LC_VD_TON13;
  LC_TD_FunctionBlock_TON LC_VD_TON16;
  LC_TD_FunctionBlock_TON LC_VD_TON17;
  LC_TD_FunctionBlock_TON LC_VD_TON18;
  LC_TD_FunctionBlock_TON LC_VD_TON19;
  LC_TD_FunctionBlock_TON LC_VD_TON21;
  LC_TD_FunctionBlock_TON LC_VD_TON22;
  LC_TD_FunctionBlock_TON LC_VD_TON26;
  LC_TD_FunctionBlock_TON LC_VD_TON27;
  LC_TD_FunctionBlock_UPDOWNCNTTIM LC_VD_UPDOWNCNTTIM1;
  LC_TD_FunctionBlock_UPDOWNCNTTIM LC_VD_UPDOWNCNTTIM2;
} LCCG_StructAttrib LC_TD_Program_HEMABATTERY;

/*                   ColdBoot Initialization Macro             */
#define LC_INIT_NONDMA_Program_HEMABATTERY(p) \
  LC_INIT_FunctionBlock_BATTSTACK(&((p)->LC_VD_BATTSTACK1)); \
  LC_INIT_FunctionBlock_GUICFG_INT(&((p)->LC_VD_GUICFG_INT3)); \
  LC_INIT_FunctionBlock_NUMOFCELLS(&((p)->LC_VD_NUMOFCELLS1)); \
  LC_INIT_FunctionBlock_IOWR(&((p)->LC_VD_IOWR2)); \
  LC_INIT_FunctionBlock_IOWR(&((p)->LC_VD_IOWR1)); \
  LC_INIT_FunctionBlock_MAX_MIN_VOLTAGE_STATUS(&((p)->LC_VD_MAX_MIN_VOLTAGE_STATUS1)); \
  LC_INIT_FunctionBlock_CHARGESTATE(&((p)->LC_VD_CHARGESTATE1)); \
  LC_INIT_FunctionBlock_SOCISZ(&((p)->LC_VD_SOCISZ1)); \
  LC_INIT_FunctionBlock_TON(&((p)->LC_VD_TON6)); \
  LC_INIT_FunctionBlock_GUI(&((p)->LC_VD_GUI1)); \
  LC_INIT_FunctionBlock_TON(&((p)->LC_VD_TON7)); \
  LC_INIT_FunctionBlock_TOF(&((p)->LC_VD_TOF12)); \
  LC_INIT_FunctionBlock_TOF(&((p)->LC_VD_TOF13)); \
  LC_INIT_FunctionBlock_TOF(&((p)->LC_VD_TOF14)); \
  LC_INIT_FunctionBlock_TOF(&((p)->LC_VD_TOF7)); \
  LC_INIT_FunctionBlock_BUFFER(&((p)->LC_VD_BUFFER21)); \
  LC_INIT_FunctionBlock_TOF(&((p)->LC_VD_TOF5)); \
  LC_INIT_FunctionBlock_TOF(&((p)->LC_VD_TOF4)); \
  LC_INIT_FunctionBlock_TOF(&((p)->LC_VD_TOF3)); \
  LC_INIT_FunctionBlock_BALANCE_ISZ(&((p)->LC_VD_BALANCE_ISZ1)); \
  LC_INIT_FunctionBlock_TOF(&((p)->LC_VD_TOF2)); \
  LC_INIT_FunctionBlock_CAN_TEST(&((p)->LC_VD_CAN_TEST2)); \
  LC_INIT_FunctionBlock_BUFFER(&((p)->LC_VD_BUFFER12)); \
  LC_INIT_FunctionBlock_TOF(&((p)->LC_VD_TOF1)); \
  LC_INIT_FunctionBlock_CAN_TEST(&((p)->LC_VD_CAN_TEST1)); \
  LC_INIT_FunctionBlock_CMS_IVT(&((p)->LC_VD_CMS_IVT1)); \
  LC_INIT_FunctionBlock_TON(&((p)->LC_VD_TON16)); \
  LC_INIT_FunctionBlock_BCU_FAULT_CODES(&((p)->LC_VD_BCU_FAULT_CODES1)); \
  LC_INIT_FunctionBlock_CTU(&((p)->LC_VD_CTU2)); \
  LC_INIT_FunctionBlock_CTU(&((p)->LC_VD_CTU1)); \
  LC_INIT_FunctionBlock_FLASH(&((p)->LC_VD_FLASH1)); \
  LC_INIT_FunctionBlock_BUFFER(&((p)->LC_VD_BUFFER11)); \
  LC_INIT_FunctionBlock_BUFFER(&((p)->LC_VD_BUFFER9)); \
  LC_INIT_FunctionBlock_ISABELINIT(&((p)->LC_VD_ISABELINIT1)); \
  LC_INIT_FunctionBlock_F_TRIG(&((p)->LC_VD_F_TRIG1)); \
  LC_INIT_FunctionBlock_SR(&((p)->LC_VD_SR1)); \
  LC_INIT_FunctionBlock_TON(&((p)->LC_VD_TON10)); \
  LC_INIT_FunctionBlock_BCU_CELL_STATUS(&((p)->LC_VD_BCU_CELL_STATUS1)); \
  LC_INIT_FunctionBlock_BUFFER(&((p)->LC_VD_BUFFER1)); \
  LC_INIT_FunctionBlock_BCU_ID(&((p)->LC_VD_BCU_ID1)); \
  LC_INIT_FunctionBlock_BUFFER(&((p)->LC_VD_BUFFER19)); \
  LC_INIT_FunctionBlock_TON(&((p)->LC_VD_TON11)); \
  LC_INIT_FunctionBlock_TON(&((p)->LC_VD_TON12)); \
  LC_INIT_FunctionBlock_TON(&((p)->LC_VD_TON13)); \
  LC_INIT_FunctionBlock_GUICFG_INT(&((p)->LC_VD_GUICFG_INT2)); \
  LC_INIT_FunctionBlock_TON(&((p)->LC_VD_TON9)); \
  LC_INIT_FunctionBlock_TON(&((p)->LC_VD_TON8)); \
  LC_INIT_FunctionBlock_R_TRIG(&((p)->LC_VD_R_TRIG8)); \
  LC_INIT_FunctionBlock_BUFFER(&((p)->LC_VD_BUFFER2)); \
  LC_INIT_FunctionBlock_BUFFER(&((p)->LC_VD_BUFFER4)); \
  LC_INIT_FunctionBlock_BUFFER(&((p)->LC_VD_BUFFER3)); \
  (p)->LC_VD_CELL_VOLTAGE_MAX_BMU_LOC = (LC_TD_USINT)0; \
  (p)->LC_VD_CELL_VOLTAGE_MAX_CELL_LOC = (LC_TD_USINT)0; \
  (p)->LC_VD_CELL_VOLTAGE_MIN_BMU_LOC = (LC_TD_USINT)0; \
  (p)->LC_VD_CELL_VOLTAGE_MIN_CELL_LOC = (LC_TD_USINT)0; \
  (p)->LC_VD_CELL_VOLTAGE_MAX = (LC_TD_UDINT)0UL; \
  LC_INIT_USINT(&((p)->LC_VD_NUMBER_OF_BMU_CFG)); \
  (p)->LC_VD_CELL_VOLTAGE = (LC_TD_UDINT)0UL; \
  (p)->LC_VD_CELL_TEMP = (LC_TD_REAL)0; \
  LC_INIT_ARRAY(&((p)->LC_VD_NUMOFCELLS),USINT,16); \
  LC_INIT_ARRAY_START(&((p)->LC_VD_NUMOFCELLS),LC_TD_USINT);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)15);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)10);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)0);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)0);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)0);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)0);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)0);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)0);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)0);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)0);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)0);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)0);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)0);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)0);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)0);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)0);\
  LC_INIT_ARRAY_END();\
  LC_INIT_ARRAY(&((p)->LC_VD_CHANNELSELECT),DataType_PLCHANNEL,16); \
  LC_INIT_ARRAY_START(&((p)->LC_VD_CHANNELSELECT),LC_TD_UDINT);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)3840UL);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)3840UL);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)256UL);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)256UL);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)256UL);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)256UL);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)256UL);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)256UL);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)256UL);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)256UL);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)256UL);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)256UL);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)3840UL);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)256UL);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)256UL);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)256UL);\
  LC_INIT_ARRAY_END();\
  (p)->LC_VD_TOTAL_VOLTAGE = (LC_TD_REAL)0; \
  LC_INIT_UINT(&((p)->LC_VD_NUMBER_OF_CELL)); \
  (p)->LC_VD_CELL_VOLTAGE_MIN = (LC_TD_UDINT)0UL; \
  (p)->LC_VD_CELL_VOLTAGE_AVERAGE = (LC_TD_UDINT)0UL; \
  LC_INIT_BOOL(&((p)->LC_VD_MAINCHARGECOMPLETE)); \
  (p)->LC_VD_BALANCE_REGISTER = (LC_TD_UINT)0; \
  LC_INIT_REAL(&((p)->LC_VD_OUTPUTVOLTAGE)); \
  LC_INIT_REAL(&((p)->LC_VD_BATTERYVOLTAGE)); \
  (p)->LC_VD_PACK_DMDC = (LC_TD_UINT)0; \
  (p)->LC_VD_PACK_DMCC = (LC_TD_UINT)0; \
  LC_INIT_BOOL(&((p)->LC_VD_FORCECHARGE)); \
  (p)->LC_VD_CMDBCU = (LC_TD_USINT)0; \
  LC_INIT_BOOL(&((p)->LC_VD_FORCEDISCHARGE)); \
  LC_INIT_REAL(&((p)->LC_VD_WHINSTANT)); \
  (p)->LC_VD_SELECTED_BMU_LOC = (LC_TD_USINT)0; \
  LC_INIT_UINT(&((p)->LC_VD_CELLVOLT_CHARGEOK)); \
  (p)->LC_VD_CAN_ID_10 = (LC_TD_UDINT)0UL; \
  (p)->LC_VD_KWHCAPACITY = (LC_TD_REAL)0; \
  LC_INIT_REAL(&((p)->LC_VD_VOLTSAMPLE1)); \
  LC_INIT_REAL(&((p)->LC_VD_WHCAPACITY)); \
  (p)->LC_VD_BMS_STATE = (LC_TD_USINT)0; \
  (p)->LC_VD_SOH = (LC_TD_USINT)0; \
  (p)->LC_VD_NUMBER_OF_PARALLEL_CELL = (LC_TD_USINT)3; \
  (p)->LC_VD_CELLVOLT_NOMINAL = (LC_TD_UDINT)0UL; \
  (p)->LC_VD_CELL_CURRENT_NOMINAL = (LC_TD_UDINT)0UL; \
  (p)->LC_VD_NUMBER_OF_BMU = (LC_TD_USINT)0; \
  LC_INIT_REAL(&((p)->LC_VD_BATTERYCURRENT)); \
  LC_INIT_BOOL(&((p)->LC_VD_SELECTLASTONE)); \
  (p)->LC_VD_CELLVOLT_MAX = (LC_TD_UINT)3500; \
  LC_INIT_REAL(&((p)->LC_VD_VOLTSAMPLE2)); \
  (p)->LC_VD_BCU_CHARGE_COMPLETE = LC_EL_false; \
  (p)->LC_VD_SOC_CC = (LC_TD_USINT)0; \
  (p)->LC_VD_CELL_VOLTAGE_MIN_DISHARGE = (LC_TD_UINT)0; \
  (p)->LC_VD_CELL_VOLTAGE_MAX_CHARGE = (LC_TD_UINT)0; \
  LC_INIT_UINT(&((p)->LC_VD_CELLVOLT_DISCHARGEOK)); \
  LC_INIT_BOOL(&((p)->LC_VD_OV_DANGER)); \
  LC_INIT_BOOL(&((p)->LC_VD_UV_DANGER)); \
  (p)->LC_VD_CAN_ID_12 = (LC_TD_UDINT)0UL; \
  (p)->LC_VD_CAN_ID_11 = (LC_TD_UDINT)0UL; \
  LC_INIT_BOOL(&((p)->LC_VD_DISCHARGECOMPLETE)); \
  LC_INIT_BOOL(&((p)->LC_VD_CONTACTENABLE_BATT)); \
  (p)->LC_VD_CELL_TEMP_MIN_CELL_LOC = (LC_TD_USINT)0; \
  (p)->LC_VD_BALANCE_ENABLE_RQ = LC_EL_false; \
  (p)->LC_VD_CELL_TEMP_MAX_BMU_LOC = (LC_TD_USINT)0; \
  (p)->LC_VD_CELL_TEMP_MAX_CELL_LOC = (LC_TD_USINT)0; \
  (p)->LC_VD_FAULT_CELL_UNDER_TEMP_DANGER = LC_EL_false; \
  (p)->LC_VD_FAULT_PACK_DISCHARGE_CONTACTOR = LC_EL_false; \
  (p)->LC_VD_FAULT_CELL_OVER_TEMP_DANGER = LC_EL_false; \
  LC_INIT_BOOL(&((p)->LC_VD_CONTACTENABLE)); \
  (p)->LC_VD_CAN_ID_13 = (LC_TD_UDINT)0UL; \
  (p)->LC_VD_CELL_TEMP_MAX = (LC_TD_REAL)0; \
  (p)->LC_VD_CELL_TEMP_MIN = (LC_TD_REAL)0; \
  (p)->LC_VD_CELL_TEMP_MIN_BMU_LOC = (LC_TD_USINT)0; \
  LC_INIT_UINT(&((p)->LC_VD_CELLVOLT_MAXCHARGE)); \
  LC_INIT_REAL(&((p)->LC_VD_PACK_CHARGE_VOLTAGE)); \
  (p)->LC_VD_SELECTED_CELL_LOC = (LC_TD_USINT)0; \
  LC_INIT_BOOL(&((p)->LC_VD_CONTACTFBK)); \
  (p)->LC_VD_CELLVOLT_CUTOFFLOW = (LC_TD_UINT)2600; \
  (p)->LC_VD_CELLVOLT_BALTHRES = (LC_TD_UINT)0; \
  (p)->LC_VD_CELLTEMP_MAXLIM = (LC_TD_REAL)55; \
  LC_INIT_REAL(&((p)->LC_VD_PACK_DISCHARGE_VOLTAGE)); \
  (p)->LC_VD_CELLTEMP_WARNINGOT = (LC_TD_REAL)0; \
  (p)->LC_VD_CELLTEMP_WARNINGUT = (LC_TD_REAL)0; \
  LC_INIT_BOOL(&((p)->LC_VD_UV_FAULT)); \
  LC_INIT_BOOL(&((p)->LC_VD_UV_DANGER_RISK)); \
  LC_INIT_BOOL(&((p)->LC_VD_OV_DANGER_RISK)); \
  LC_INIT_BOOL(&((p)->LC_VD_OT_DANGER)); \
  LC_INIT_UINT(&((p)->LC_VD_CELLVOLT_MINDISCHARGE)); \
  LC_INIT_BOOL(&((p)->LC_VD_CHARGECMD)); \
  (p)->LC_VD_CELLTEMP_MINLIM = (LC_TD_REAL)-5; \
  (p)->LC_VD_FAULT_CELL_UNDER_TEMP_WARNING = LC_EL_false; \
  (p)->LC_VD_FAULT_CELL_OVER_TEMP_WARNING = LC_EL_false; \
  (p)->LC_VD_FAULT_CELL_UNDER_VOLTAGE_WARNING = LC_EL_false; \
  (p)->LC_VD_FAULT_CELL_OVER_VOLTAGE_WARNING = LC_EL_false; \
  (p)->LC_VD_BOARD_FAULT_MESSAGES = (LC_TD_UDINT)0UL; \
  (p)->LC_VD_CHARGEOK_VOLTAGE_PACK = (LC_TD_REAL)0; \
  (p)->LC_VD_FAULT_PACK_HVIL_1 = LC_EL_false; \
  (p)->LC_VD_BCU_CAN_CH = LC_ED__TMS570_CAN__L1; \
  LC_INIT_REAL(&((p)->LC_VD_BMSDMCC_MAIN)); \
  (p)->LC_VD_CAN_ID_14 = (LC_TD_UDINT)0UL; \
  (p)->LC_VD_BALANCE_VOLTAGE = (LC_TD_UDINT)0UL; \
  (p)->LC_VD_FAULT_PACK_CMS = LC_EL_false; \
  (p)->LC_VD_PACK_TEMPERATURE = (LC_TD_REAL)0; \
  LC_INIT_BOOL(&((p)->LC_VD_EMERGENCYBTN)); \
  LC_INIT_BOOL(&((p)->LC_VD_BALANCESTATEENB)); \
  (p)->LC_VD_CAN_FAULT_07 = LC_EL_false; \
  (p)->LC_VD_FAULT_CAN_COMMUNICATION = LC_EL_false; \
  LC_INIT_USINT(&((p)->LC_VD_ISOLATIONSTATUS)); \
  (p)->LC_VD_BCU_FAULT_WARNING = LC_EL_false; \
  LC_INIT_UDINT(&((p)->LC_VD_CAN_ID_16)); \
  (p)->LC_VD_FAULT_PACK_BMU = LC_EL_false; \
  (p)->LC_VD_CELLVOLT_MIN = (LC_TD_UINT)2800; \
  (p)->LC_VD_CMD_VOLTAGE_SENSE_2 = (LC_TD_REAL)0; \
  (p)->LC_VD_CMD_VOLTAGE_SENSE_3 = (LC_TD_REAL)0; \
  (p)->LC_VD_CHARGE_CURRENT = (LC_TD_UINT)0; \
  (p)->LC_VD_CMD_VOLTAGE_SENSE_1 = (LC_TD_REAL)0; \
  (p)->LC_VD_MEASURE_ALL = LC_EL_false; \
  (p)->LC_VD_MEASURE_AUX = LC_EL_false; \
  LC_INIT_ARRAY(&((p)->LC_VD_TAUXCELLS),USINT,16); \
  LC_INIT_ARRAY_START(&((p)->LC_VD_TAUXCELLS),LC_TD_USINT);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)0);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)0);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)0);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)0);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)1);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)1);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)1);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)1);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)2);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)2);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)2);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)2);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)3);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)3);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)3);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)3);\
  LC_INIT_ARRAY_END();\
  (p)->LC_VD_BCU_FAULT_DANGER = LC_EL_false; \
  (p)->LC_VD_CMD_CURRENT_SENSE = (LC_TD_REAL)0; \
  (p)->LC_VD_FAULT_DMDC_EXCEED = LC_EL_false; \
  (p)->LC_VD_FAULT_DMCC_EXCEED = LC_EL_false; \
  (p)->LC_VD_FAULT_PACK_CHARGE_CONTACTOR = LC_EL_false; \
  (p)->LC_VD_BOARD_ERROR_MESSAGES = (LC_TD_UDINT)0UL; \
  (p)->LC_VD_CMD_COUNTER_CURRENT = (LC_TD_REAL)0; \
  (p)->LC_VD_SELECTED_PACK_NUMBER = (LC_TD_USINT)0; \
  (p)->LC_VD_CMD_POWER = (LC_TD_REAL)0; \
  (p)->LC_VD_FAULT_PACK_HVIL_2 = LC_EL_false; \
  (p)->LC_VD_CMD_TEMP = (LC_TD_REAL)0; \
  (p)->LC_VD_CAN_FAULT_05 = LC_EL_false; \
  (p)->LC_VD_CAN_FAULT_04 = LC_EL_false; \
  (p)->LC_VD_CAN_FAULT_02 = LC_EL_false; \
  LC_INIT_BOOL(&((p)->LC_VD_IGNITION)); \
  LC_INIT_USINT(&((p)->LC_VD_BALCHARGEST)); \
  (p)->LC_VD_CAN_FAULT_06 = LC_EL_false; \
  (p)->LC_VD_CELL_SERIES_CONNECTION = (LC_TD_USINT)0; \
  (p)->LC_VD_GUI_FAULT = (LC_TD_UDINT)0UL; \
  (p)->LC_VD_CELLVOLT_CUTOFFHIGH = (LC_TD_UINT)3600; \
  (p)->LC_VD_EPCS_CAN_CH = LC_ED__TMS570_CAN__L3; \
  (p)->LC_VD_DICHARGEOK_VOLTAGE_PACK = (LC_TD_REAL)0; \
  (p)->LC_VD_BATTERYID = (LC_TD_BYTE)1; \
  (p)->LC_VD_FAULT_CELL_OVER_VOLTAGE_DANGER = LC_EL_false; \
  (p)->LC_VD_FAULT_CELL_UNDER_VOLTAGE_DANGER = LC_EL_false; \
  (p)->LC_VD_CAN_ID_15 = (LC_TD_UDINT)0UL; \
  (p)->LC_VD_DUTY_CYCLE = (LC_TD_UINT)0; \
  (p)->LC_VD_CMD_OVERALL_POWER = (LC_TD_LREAL)0; \
  LC_INIT_BOOL(&((p)->LC_VD_UT_DANGER)); \
  LC_INIT_REAL(&((p)->LC_VD_CMS0VOLT1)); \
  LC_INIT_BOOL(&((p)->LC_VD_PRECHARGECOMPLETE)); \
  LC_INIT_REAL(&((p)->LC_VD_CMS1VOLT1)); \
  LC_INIT_BOOL(&((p)->LC_VD_PRECHARGEENABLE)); \
  LC_INIT_BOOL(&((p)->LC_VD_PRECHARGEERROR)); \
  LC_INIT_BOOL(&((p)->LC_VD_PRECHARGECANERR)); \
  LC_INIT_USINT(&((p)->LC_VD_PRECHARGESTATUS)); \
  LC_INIT_BYTE(&((p)->LC_VD_SIM100_ERRBYTE)); \
  LC_INIT_REAL(&((p)->LC_VD_PACK_CUTOFFLOW_VOLTAGE)); \
  LC_INIT_REAL(&((p)->LC_VD_INSTANTPOWER)); \
  LC_INIT_LWORD(&((p)->LC_VD_FAULTSWORD)); \
  (p)->LC_VD_CAN_FAULT_03 = LC_EL_false; \
  (p)->LC_VD_MASTERID = (LC_TD_BYTE)128; \
  (p)->LC_VD_HVCU_STATE = (LC_TD_USINT)0; \
  LC_INIT_BOOL(&((p)->LC_VD_DISCHARGETERMINATE)); \
  LC_INIT_BOOL(&((p)->LC_VD_OV_FAULT)); \
  LC_INIT_BOOL(&((p)->LC_VD_UT_DANGER_RISK)); \
  LC_INIT_BOOL(&((p)->LC_VD_OT_DANGER_RISK)); \
  LC_INIT_REAL(&((p)->LC_VD_BMSDMDC_FINAL)); \
  LC_INIT_REAL(&((p)->LC_VD_BMSDMCC_FINAL)); \
  LC_INIT_REAL(&((p)->LC_VD_TESTREMWH)); \
  LC_INIT_USINT(&((p)->LC_VD_TESTSOCSTATE)); \
  LC_INIT_BOOL(&((p)->LC_VD_INPUTSGN1)); \
  LC_INIT_BOOL(&((p)->LC_VD_INPUTSGN2)); \
  LC_INIT_BOOL(&((p)->LC_VD_INPUTSGN3)); \
  LC_INIT_BOOL(&((p)->LC_VD_OUTPUTSGN1)); \
  LC_INIT_BOOL(&((p)->LC_VD_OUTPUTSGN2)); \
  LC_INIT_FunctionBlock_IOWR(&((p)->LC_VD_IOWR13)); \
  LC_INIT_FunctionBlock_ANLG(&((p)->LC_VD_ANLG8)); \
  (p)->LC_VD_DOD_RATE = (LC_TD_REAL)0; \
  LC_INIT_REAL(&((p)->LC_VD_USABLECAPKWH)); \
  LC_INIT_REAL(&((p)->LC_VD_SOCREAL)); \
  LC_INIT_REAL(&((p)->LC_VD_USABLECAPWH)); \
  LC_INIT_REAL(&((p)->LC_VD_PACKREMCAP_KWH)); \
  LC_INIT_REAL(&((p)->LC_VD_USABLEREMWH)); \
  LC_INIT_REAL(&((p)->LC_VD_USABLEREMKWH)); \
  LC_INIT_BOOL(&((p)->LC_VD_HVIL1_STATUS)); \
  LC_INIT_FunctionBlock_BUFFER(&((p)->LC_VD_BUFFER10)); \
  LC_INIT_FunctionBlock_TOF(&((p)->LC_VD_TOF6)); \
  LC_INIT_REAL(&((p)->LC_VD_PACK_CUTOFFHIGH_VOLTAGE)); \
  LC_INIT_FunctionBlock_GUICFG_INT(&((p)->LC_VD_GUICFG_INT4)); \
  LC_INIT_FunctionBlock_GUICFG_INT(&((p)->LC_VD_GUICFG_INT5)); \
  LC_INIT_UINT(&((p)->LC_VD_MAXDISCHARGEAMPRCFG)); \
  LC_INIT_FunctionBlock_TBUFFER(&((p)->LC_VD_TBUFFER2)); \
  LC_INIT_FunctionBlock_TBUFFER(&((p)->LC_VD_TBUFFER7)); \
  LC_INIT_REAL(&((p)->LC_VD_PACK_CUTOFFV_LOW)); \
  LC_INIT_REAL(&((p)->LC_VD_CMD_VOLTAGE_SENSE1_VOLT)); \
  LC_INIT_REAL(&((p)->LC_VD_CMD_VOLTAGE_SENSE2_VOLT)); \
  LC_INIT_UINT(&((p)->LC_VD_CELLVOLT_WARNINGOV)); \
  LC_INIT_UINT(&((p)->LC_VD_CELLVOLT_WARNINGUV)); \
  (p)->LC_VD_PDUCAN = LC_ED__TMS570_CAN__L2; \
  LC_INIT_FunctionBlock_GUICFG_INT(&((p)->LC_VD_GUICFG_INT6)); \
  LC_INIT_UINT(&((p)->LC_VD_OCWARNINGAMPR)); \
  LC_INIT_FunctionBlock_TBUFFER(&((p)->LC_VD_TBUFFER1)); \
  LC_INIT_BOOL(&((p)->LC_VD_OC_WARNING)); \
  LC_INIT_FunctionBlock_TBUFFER(&((p)->LC_VD_TBUFFER4)); \
  LC_INIT_BOOL(&((p)->LC_VD_OC_FAULT)); \
  LC_INIT_BOOL(&((p)->LC_VD_CONTACTNEGENABLE_BATT)); \
  LC_INIT_BOOL(&((p)->LC_VD_CONTACTENABLECHARGE_BATT)); \
  LC_INIT_REAL(&((p)->LC_VD_CHARGEINVOLTAGE)); \
  LC_INIT_BOOL(&((p)->LC_VD_CONTACTFBKDISCHARGE)); \
  LC_INIT_BOOL(&((p)->LC_VD_CONTACTFBKCHARGE)); \
  LC_INIT_FunctionBlock_TOF(&((p)->LC_VD_TOF8)); \
  LC_INIT_FunctionBlock_BUFFER(&((p)->LC_VD_BUFFER22)); \
  LC_INIT_FunctionBlock_TOF(&((p)->LC_VD_TOF9)); \
  LC_INIT_FunctionBlock_BUFFER(&((p)->LC_VD_BUFFER23)); \
  LC_INIT_BOOL(&((p)->LC_VD_FAULT_PACK_NEGATIVE_CONTACTOR)); \
  LC_INIT_BOOL(&((p)->LC_VD_DISCHARGECMD)); \
  LC_INIT_BOOL(&((p)->LC_VD_PRECHARGECOMPLETECHARGE)); \
  LC_INIT_BOOL(&((p)->LC_VD_PRECHARGEENABLECHARGE)); \
  LC_INIT_BOOL(&((p)->LC_VD_SHUTDOWNCOMPLETE)); \
  LC_INIT_BOOL(&((p)->LC_VD_SHUTDOWNCMD)); \
  LC_INIT_BOOL(&((p)->LC_VD_DISCHARGEOFF)); \
  LC_INIT_BOOL(&((p)->LC_VD_CHARGEOFF)); \
  LC_INIT_FunctionBlock_TBUFFER(&((p)->LC_VD_TBUFFER6)); \
  LC_INIT_FunctionBlock_SR(&((p)->LC_VD_SR2)); \
  LC_INIT_BOOL(&((p)->LC_VD_PDULED)); \
  LC_INIT_USINT(&((p)->LC_VD_INPUTSGN1STATUS)); \
  LC_INIT_USINT(&((p)->LC_VD_INPUTSGN2STATUS)); \
  LC_INIT_FunctionBlock_GUICFG_INT(&((p)->LC_VD_GUICFG_INT7)); \
  LC_INIT_FunctionBlock_GUICFG_INT(&((p)->LC_VD_GUICFG_INT8)); \
  LC_INIT_FunctionBlock_GUICFG_INT(&((p)->LC_VD_GUICFG_INT9)); \
  LC_INIT_FunctionBlock_GUICFG_INT(&((p)->LC_VD_GUICFG_INT10)); \
  LC_INIT_FunctionBlock_GUICFG_INT(&((p)->LC_VD_GUICFG_INT11)); \
  LC_INIT_FunctionBlock_GUICFG_INT(&((p)->LC_VD_GUICFG_INT12)); \
  LC_INIT_FunctionBlock_GUICFG_INT(&((p)->LC_VD_GUICFG_INT13)); \
  LC_INIT_FunctionBlock_GUICFG_INT(&((p)->LC_VD_GUICFG_INT14)); \
  LC_INIT_FunctionBlock_GUICFG_INT(&((p)->LC_VD_GUICFG_INT15)); \
  LC_INIT_FunctionBlock_GUICFG_INT(&((p)->LC_VD_GUICFG_INT16)); \
  LC_INIT_FunctionBlock_GUICFG_INT(&((p)->LC_VD_GUICFG_INT17)); \
  LC_INIT_FunctionBlock_GUICFG_INT(&((p)->LC_VD_GUICFG_INT18)); \
  LC_INIT_FunctionBlock_GUICFG_INT(&((p)->LC_VD_GUICFG_INT19)); \
  LC_INIT_FunctionBlock_GUICFG_INT(&((p)->LC_VD_GUICFG_INT20)); \
  LC_INIT_FunctionBlock_GUICFG_INT(&((p)->LC_VD_GUICFG_INT21)); \
  LC_INIT_FunctionBlock_GUICFG_INT(&((p)->LC_VD_GUICFG_INT22)); \
  LC_INIT_FunctionBlock_GUICFG_INT(&((p)->LC_VD_GUICFG_INT23)); \
  LC_INIT_UDINT(&((p)->LC_VD_BALANCEDIFF_THRESHOLD)); \
  LC_INIT_FunctionBlock_GUICFG_REAL(&((p)->LC_VD_GUICFG_REAL1)); \
  LC_INIT_FunctionBlock_GUICFG_INT(&((p)->LC_VD_GUICFG_INT24)); \
  LC_INIT_UINT(&((p)->LC_VD_CYCLESPERSOH)); \
  LC_INIT_BOOL(&((p)->LC_VD_SELCLOCK)); \
  LC_INIT_ARRAY(&((p)->LC_VD_BMUCELLVOLT),UINT,16); \
  LC_INIT_ARRAY(&((p)->LC_VD_BMUCELLTEMP),SINT,16); \
  LC_INIT_UINT(&((p)->LC_VD_BMUMAXCELLV)); \
  LC_INIT_UINT(&((p)->LC_VD_BMUMINCELLV)); \
  LC_INIT_SINT(&((p)->LC_VD_BMUMINCELLT)); \
  LC_INIT_SINT(&((p)->LC_VD_BMUMAXCELLT)); \
  LC_INIT_BOOL(&((p)->LC_VD_WARNINGMDLBALT)); \
  LC_INIT_BOOL(&((p)->LC_VD_FAULTMDLBALT)); \
  LC_INIT_BOOL(&((p)->LC_VD_FAULTFORSTATE)); \
  LC_INIT_UINT(&((p)->LC_VD_MAXCHARGEAMPRCFG)); \
  LC_INIT_BOOL(&((p)->LC_VD_HVIL2_STATUS)); \
  LC_INIT_FunctionBlock_TOF(&((p)->LC_VD_TOF10)); \
  LC_INIT_FunctionBlock_BUFFER(&((p)->LC_VD_BUFFER13)); \
  LC_INIT_BOOL(&((p)->LC_VD_IMDENABLE)); \
  LC_INIT_UDINT(&((p)->LC_VD_ISORP)); \
  LC_INIT_UDINT(&((p)->LC_VD_ISORN)); \
  LC_INIT_UDINT(&((p)->LC_VD_ISOOHMPERV)); \
  LC_INIT_FunctionBlock_GUICFG_INT(&((p)->LC_VD_GUICFG_INT25)); \
  LC_INIT_UDINT(&((p)->LC_VD_PRECHARGEINTERVAL)); \
  LC_INIT_BOOL(&((p)->LC_VD_FORCENEGATIVE)); \
  LC_INIT_BOOL(&((p)->LC_VD_CONTACTNEGENABLE)); \
  LC_INIT_BOOL(&((p)->LC_VD_CONTACTENABLECHARGE)); \
  LC_INIT_FunctionBlock_GUICFG_INT(&((p)->LC_VD_GUICFG_INT26)); \
  LC_INIT_UDINT(&((p)->LC_VD_NTCBETA)); \
  LC_INIT_FunctionBlock_GUICFG_INT(&((p)->LC_VD_GUICFG_INT27)); \
  LC_INIT_UINT(&((p)->LC_VD_OCFAULTAMPR)); \
  LC_INIT_FunctionBlock_TBUFFER(&((p)->LC_VD_TBUFFER15)); \
  LC_INIT_FunctionBlock_TBUFFER(&((p)->LC_VD_TBUFFER16)); \
  LC_INIT_FunctionBlock_SR(&((p)->LC_VD_SR5)); \
  LC_INIT_BOOL(&((p)->LC_VD_BATTERYINCHARGE)); \
  LC_INIT_FunctionBlock_HVCU_CONTROL_STATE(&((p)->LC_VD_HVCU_CONTROL_STATE2)); \
  (p)->LC_VD_SLAVEMODE = LC_EL_true; \
  LC_INIT_BOOL(&((p)->LC_VD_DISCHARGEENB)); \
  LC_INIT_BOOL(&((p)->LC_VD_CHARGEENB)); \
  LC_INIT_DataType_BESSSYSTEMSTATUS(&((p)->LC_VD_BESSSTATUS)); \
  LC_INIT_DataType_BESSOPRSTATUS(&((p)->LC_VD_BESSOPERATINGSTATUS)); \
  LC_INIT_DataType_BESSWORKMODE(&((p)->LC_VD_BESSWORKINGMODE)); \
  LC_INIT_DataType_BESSALARMS(&((p)->LC_VD_BATEPCSALARM)); \
  LC_INIT_REAL(&((p)->LC_VD_CMD_CURRENT_SENSE_AMP)); \
  LC_INIT_BOOL(&((p)->LC_VD_BATTERYCHARGING)); \
  LC_INIT_BOOL(&((p)->LC_VD_BATTERYDISCHARGING)); \
  LC_INIT_BOOL(&((p)->LC_VD_CURRENTPROTECTION)); \
  LC_INIT_FunctionBlock_TBUFFER(&((p)->LC_VD_TBUFFER20)); \
  LC_INIT_FunctionBlock_TBUFFER(&((p)->LC_VD_TBUFFER19)); \
  LC_INIT_FunctionBlock_TON(&((p)->LC_VD_TON17)); \
  LC_INIT_FunctionBlock_TON(&((p)->LC_VD_TON2)); \
  LC_INIT_FunctionBlock_TON(&((p)->LC_VD_TON19)); \
  LC_INIT_FunctionBlock_TON(&((p)->LC_VD_TON18)); \
  LC_INIT_BOOL(&((p)->LC_VD_CHARGEPROTECT)); \
  LC_INIT_BOOL(&((p)->LC_VD_DISCHARGEPROTECT)); \
  LC_INIT_FunctionBlock_ESSSTATE1(&((p)->LC_VD_ESSSTATE11)); \
  (p)->LC_VD_SHUTDOWNENB = LC_EL_false; \
  LC_INIT_BOOL(&((p)->LC_VD_PRECHARGEBOARDERR)); \
  LC_INIT_BOOL(&((p)->LC_VD_SIM100NOTFOUND)); \
  LC_INIT_REAL(&((p)->LC_VD_BATTERYWATT)); \
  LC_INIT_BOOL(&((p)->LC_VD_EPCSREQDATA)); \
  LC_INIT_FunctionBlock_F_TRIG(&((p)->LC_VD_F_TRIG3)); \
  LC_INIT_FunctionBlock_F_TRIG(&((p)->LC_VD_F_TRIG4)); \
  LC_INIT_FunctionBlock_R_TRIG(&((p)->LC_VD_R_TRIG9)); \
  LC_INIT_REAL(&((p)->LC_VD_SOCCHCOMP)); \
  LC_INIT_FunctionBlock_R_TRIG(&((p)->LC_VD_R_TRIG2)); \
  LC_INIT_REAL(&((p)->LC_VD_SOCDCHCOMP)); \
  LC_INIT_FunctionBlock_R_TRIG(&((p)->LC_VD_R_TRIG3)); \
  LC_INIT_FunctionBlock_HVCU_CONFIG(&((p)->LC_VD_HVCU_CONFIG1)); \
  LC_INIT_BOOL(&((p)->LC_VD_CMDTMT)); \
  LC_INIT_BOOL(&((p)->LC_VD_ADDRBIT0)); \
  LC_INIT_BOOL(&((p)->LC_VD_ADDRBIT1)); \
  LC_INIT_REAL(&((p)->LC_VD_MULTAMPCHAR)); \
  LC_INIT_REAL(&((p)->LC_VD_MULTAMPDISCH)); \
  LC_INIT_FunctionBlock_AMPMULTTEMP(&((p)->LC_VD_AMPMULTTEMP1)); \
  LC_INIT_FunctionBlock_AMPMULTTEMP(&((p)->LC_VD_AMPMULTTEMP2)); \
  LC_INIT_FunctionBlock_AMPMULTTEMPDIS(&((p)->LC_VD_AMPMULTTEMPDIS1)); \
  LC_INIT_FunctionBlock_AMPMULTTEMPDIS(&((p)->LC_VD_AMPMULTTEMPDIS2)); \
  LC_INIT_FunctionBlock_AMPMULTVOLTDISC(&((p)->LC_VD_AMPMULTVOLTDISC1)); \
  LC_INIT_FunctionBlock_AMPMULTVOLTCHAR(&((p)->LC_VD_AMPMULTVOLTCHAR1)); \
  LC_INIT_BOOL(&((p)->LC_VD_INCREASECHARGEAMP)); \
  LC_INIT_BOOL(&((p)->LC_VD_INCREASEDISCHARGEAMP)); \
  LC_INIT_BOOL(&((p)->LC_VD_DECREASECHARGEAMP)); \
  LC_INIT_BOOL(&((p)->LC_VD_DECREASEDISCHARGEAMP)); \
  LC_INIT_FunctionBlock_TON(&((p)->LC_VD_TON21)); \
  LC_INIT_BOOL(&((p)->LC_VD_DISCHARGEAMPENB)); \
  (p)->LC_VD_DISCHARGEUNITAMP = (LC_TD_REAL)0.25; \
  LC_INIT_BOOL(&((p)->LC_VD_CHARGEAMPENB)); \
  LC_INIT_FunctionBlock_TON(&((p)->LC_VD_TON22)); \
  (p)->LC_VD_CHARGEUNITAMP = (LC_TD_REAL)0.25; \
  LC_INIT_REAL(&((p)->LC_VD_MAXCHARGEAMP)); \
  LC_INIT_REAL(&((p)->LC_VD_MAXDISCHARGEAMP)); \
  LC_INIT_FunctionBlock_UPDOWNCNTTIM(&((p)->LC_VD_UPDOWNCNTTIM1)); \
  LC_INIT_FunctionBlock_UPDOWNCNTTIM(&((p)->LC_VD_UPDOWNCNTTIM2)); \
  LC_INIT_FunctionBlock_BCU_STATUS2(&((p)->LC_VD_BCU_STATUS21)); \
  LC_INIT_FunctionBlock_BCU_STATE_MESSAGE(&((p)->LC_VD_BCU_STATE_MESSAGE1)); \
  LC_INIT_FunctionBlock_BCU_BATTERY_STATUS(&((p)->LC_VD_BCU_BATTERY_STATUS1)); \
  LC_INIT_FunctionBlock_GUICFG_INT(&((p)->LC_VD_GUICFG_INT28)); \
  LC_INIT_TIME(&((p)->LC_VD_TESTVALUE0)); \
  LC_INIT_FunctionBlock_TON(&((p)->LC_VD_TON4)); \
  LC_INIT_FunctionBlock_TON(&((p)->LC_VD_TON5)); \
  LC_INIT_FunctionBlock_IOWR(&((p)->LC_VD_IOWR4)); \
  LC_INIT_FunctionBlock_FLASH(&((p)->LC_VD_FLASH3)); \
  LC_INIT_FunctionBlock_SAFETY_POWER(&((p)->LC_VD_SAFETY_POWER1)); \
  LC_INIT_FunctionBlock_ANLG(&((p)->LC_VD_ANLG14)); \
  LC_INIT_FunctionBlock_TON(&((p)->LC_VD_TON1)); \
  LC_INIT_FunctionBlock_TOF(&((p)->LC_VD_TOF15)); \
  LC_INIT_BOOL(&((p)->LC_VD_BATTSTACK_DISABLE)); \
  LC_INIT_BOOL(&((p)->LC_VD_CAN_DISABLE)); \
  LC_INIT_BOOL(&((p)->LC_VD_RDY_TO_SLEEP)); \
  LC_INIT_UINT(&((p)->LC_VD_AN_KL15)); \
  LC_INIT_FunctionBlock_IOWR(&((p)->LC_VD_IOWR19)); \
  LC_INIT_FunctionBlock_IOWR(&((p)->LC_VD_IOWR6)); \
  LC_INIT_FunctionBlock_IOWR(&((p)->LC_VD_IOWR5)); \
  LC_INIT_FunctionBlock_IOWR(&((p)->LC_VD_IOWR18)); \
  LC_INIT_FunctionBlock_IOWR(&((p)->LC_VD_IOWR20)); \
  LC_INIT_FunctionBlock_IOWR(&((p)->LC_VD_IOWR21)); \
  LC_INIT_FunctionBlock_FLASH(&((p)->LC_VD_FLASH4)); \
  LC_INIT_BYTE(&((p)->LC_VD_HW_VERSION)); \
  LC_INIT_FunctionBlock_IOWR(&((p)->LC_VD_IOWR9)); \
  LC_INIT_FunctionBlock_IOWR(&((p)->LC_VD_IOWR7)); \
  LC_INIT_FunctionBlock_IOWR(&((p)->LC_VD_IOWR22)); \
  LC_INIT_FunctionBlock_IOWR(&((p)->LC_VD_IOWR23)); \
  LC_INIT_FunctionBlock_IOWR(&((p)->LC_VD_IOWR10)); \
  LC_INIT_FunctionBlock_IOWR(&((p)->LC_VD_IOWR24)); \
  LC_INIT_FunctionBlock_ANLG(&((p)->LC_VD_ANLG4)); \
  LC_INIT_FunctionBlock_ANLG(&((p)->LC_VD_ANLG3)); \
  LC_INIT_FunctionBlock_ANLG(&((p)->LC_VD_ANLG1)); \
  LC_INIT_FunctionBlock_ANLG(&((p)->LC_VD_ANLG2)); \
  LC_INIT_FunctionBlock_IORD(&((p)->LC_VD_IORD5)); \
  LC_INIT_FunctionBlock_IORD(&((p)->LC_VD_IORD4)); \
  LC_INIT_FunctionBlock_IORD(&((p)->LC_VD_IORD1)); \
  LC_INIT_FunctionBlock_DGTIN(&((p)->LC_VD_DGTIN8)); \
  LC_INIT_FunctionBlock_DGTIN(&((p)->LC_VD_DGTIN3)); \
  LC_INIT_FunctionBlock_DGTIN(&((p)->LC_VD_DGTIN4)); \
  LC_INIT_FunctionBlock_IORD(&((p)->LC_VD_IORD2)); \
  LC_INIT_FunctionBlock_IORD(&((p)->LC_VD_IORD3)); \
  LC_INIT_BOOL(&((p)->LC_VD_IGNITION_KL15)); \
  LC_INIT_FunctionBlock_F_TRIG(&((p)->LC_VD_F_TRIG2)); \
  LC_INIT_FunctionBlock_NTC(&((p)->LC_VD_NTC2)); \
  (p)->LC_VD_NEW_CHG_CONTACT = LC_EL_true; \
  (p)->LC_VD_NEW_DCHG_CONTACT = LC_EL_true; \
  LC_INIT_BOOL(&((p)->LC_VD_NEW_CONTACTFBK1)); \
  LC_INIT_BOOL(&((p)->LC_VD_NEW_CONTACTFBK2)); \
  LC_INIT_BOOL(&((p)->LC_VD_HKM_DISCHARGECONTACT)); \
  LC_INIT_REAL(&((p)->LC_VD_HKM_DISCHARGEINVOLTAGE)); \
  LC_INIT_REAL(&((p)->LC_VD_DISCHARGEINVOLTAGE)); \
  LC_INIT_UINT(&((p)->LC_VD_NUMBER_OF_MAXCELL)); \
  LC_INIT_USINT(&((p)->LC_VD_NUMBER_OF_MAXCELL2)); \
  LC_INIT_FunctionBlock_ARR2VAL(&((p)->LC_VD_ARR2VAL2)); \
  (p)->LC_VD_NEWBMU_RESET = LC_EL_false; \
  LC_INIT_FunctionBlock_PRECHARGECAN(&((p)->LC_VD_PRECHARGECAN1)); \
  LC_INIT_FunctionBlock_TON(&((p)->LC_VD_TON26)); \
  LC_INIT_FunctionBlock_TON(&((p)->LC_VD_TON27)); \
  LC_INIT_ARRAY(&((p)->LC_VD_CHANNELSELECT2),DataType_PLCHANNEL,16); \
  LC_INIT_ARRAY_START(&((p)->LC_VD_CHANNELSELECT2),LC_TD_UDINT);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)1792UL);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)1792UL);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)1792UL);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)1792UL);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)1792UL);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)1792UL);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)1792UL);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)1792UL);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)1792UL);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)1792UL);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)1792UL);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)1792UL);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)1792UL);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)1792UL);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)1792UL);\
  LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)1792UL);\
  LC_INIT_ARRAY_END();\
  LC_INIT_BOOL(&((p)->LC_VD_ALLCONTACSTENABLE)); \
  LC_INIT_FunctionBlock_GUICFG_INT(&((p)->LC_VD_GUICFG_INT1)); \

#define LC_INIT_Program_HEMABATTERY(p) \
{ \
  LC_INIT_NONDMA_Program_HEMABATTERY(p) \
}

/*                   WarmBoot Initialization Macro             */
#define LC_WINIT_NONDMA_Program_HEMABATTERY(p,RF) \
  LC_WINIT_FunctionBlock_BATTSTACK(&((p)->LC_VD_BATTSTACK1),0); \
  LC_WINIT_FunctionBlock_GUICFG_INT(&((p)->LC_VD_GUICFG_INT3),0); \
  LC_WINIT_FunctionBlock_NUMOFCELLS(&((p)->LC_VD_NUMOFCELLS1),0); \
  LC_WINIT_FunctionBlock_IOWR(&((p)->LC_VD_IOWR2),0); \
  LC_WINIT_FunctionBlock_IOWR(&((p)->LC_VD_IOWR1),0); \
  LC_WINIT_FunctionBlock_MAX_MIN_VOLTAGE_STATUS(&((p)->LC_VD_MAX_MIN_VOLTAGE_STATUS1),0); \
  LC_WINIT_FunctionBlock_CHARGESTATE(&((p)->LC_VD_CHARGESTATE1),0); \
  LC_WINIT_FunctionBlock_SOCISZ(&((p)->LC_VD_SOCISZ1),0); \
  LC_WINIT_FunctionBlock_TON(&((p)->LC_VD_TON6),0); \
  LC_WINIT_FunctionBlock_GUI(&((p)->LC_VD_GUI1),0); \
  LC_WINIT_FunctionBlock_TON(&((p)->LC_VD_TON7),0); \
  LC_WINIT_FunctionBlock_TOF(&((p)->LC_VD_TOF12),0); \
  LC_WINIT_FunctionBlock_TOF(&((p)->LC_VD_TOF13),0); \
  LC_WINIT_FunctionBlock_TOF(&((p)->LC_VD_TOF14),0); \
  LC_WINIT_FunctionBlock_TOF(&((p)->LC_VD_TOF7),0); \
  LC_WINIT_FunctionBlock_BUFFER(&((p)->LC_VD_BUFFER21),0); \
  LC_WINIT_FunctionBlock_TOF(&((p)->LC_VD_TOF5),0); \
  LC_WINIT_FunctionBlock_TOF(&((p)->LC_VD_TOF4),0); \
  LC_WINIT_FunctionBlock_TOF(&((p)->LC_VD_TOF3),0); \
  LC_WINIT_FunctionBlock_BALANCE_ISZ(&((p)->LC_VD_BALANCE_ISZ1),0); \
  LC_WINIT_FunctionBlock_TOF(&((p)->LC_VD_TOF2),0); \
  LC_WINIT_FunctionBlock_CAN_TEST(&((p)->LC_VD_CAN_TEST2),0); \
  LC_WINIT_FunctionBlock_BUFFER(&((p)->LC_VD_BUFFER12),0); \
  LC_WINIT_FunctionBlock_TOF(&((p)->LC_VD_TOF1),0); \
  LC_WINIT_FunctionBlock_CAN_TEST(&((p)->LC_VD_CAN_TEST1),0); \
  LC_WINIT_FunctionBlock_CMS_IVT(&((p)->LC_VD_CMS_IVT1),0); \
  LC_WINIT_FunctionBlock_TON(&((p)->LC_VD_TON16),0); \
  LC_WINIT_FunctionBlock_BCU_FAULT_CODES(&((p)->LC_VD_BCU_FAULT_CODES1),0); \
  LC_WINIT_FunctionBlock_CTU(&((p)->LC_VD_CTU2),0); \
  LC_WINIT_FunctionBlock_CTU(&((p)->LC_VD_CTU1),0); \
  LC_WINIT_FunctionBlock_FLASH(&((p)->LC_VD_FLASH1),0); \
  LC_WINIT_FunctionBlock_BUFFER(&((p)->LC_VD_BUFFER11),0); \
  LC_WINIT_FunctionBlock_BUFFER(&((p)->LC_VD_BUFFER9),0); \
  LC_WINIT_FunctionBlock_ISABELINIT(&((p)->LC_VD_ISABELINIT1),0); \
  LC_WINIT_FunctionBlock_F_TRIG(&((p)->LC_VD_F_TRIG1),0); \
  LC_WINIT_FunctionBlock_SR(&((p)->LC_VD_SR1),0); \
  LC_WINIT_FunctionBlock_TON(&((p)->LC_VD_TON10),0); \
  LC_WINIT_FunctionBlock_BCU_CELL_STATUS(&((p)->LC_VD_BCU_CELL_STATUS1),0); \
  LC_WINIT_FunctionBlock_BUFFER(&((p)->LC_VD_BUFFER1),0); \
  LC_WINIT_FunctionBlock_BCU_ID(&((p)->LC_VD_BCU_ID1),0); \
  LC_WINIT_FunctionBlock_BUFFER(&((p)->LC_VD_BUFFER19),0); \
  LC_WINIT_FunctionBlock_TON(&((p)->LC_VD_TON11),0); \
  LC_WINIT_FunctionBlock_TON(&((p)->LC_VD_TON12),0); \
  LC_WINIT_FunctionBlock_TON(&((p)->LC_VD_TON13),0); \
  LC_WINIT_FunctionBlock_GUICFG_INT(&((p)->LC_VD_GUICFG_INT2),0); \
  LC_WINIT_FunctionBlock_TON(&((p)->LC_VD_TON9),0); \
  LC_WINIT_FunctionBlock_TON(&((p)->LC_VD_TON8),0); \
  LC_WINIT_FunctionBlock_R_TRIG(&((p)->LC_VD_R_TRIG8),0); \
  LC_WINIT_FunctionBlock_BUFFER(&((p)->LC_VD_BUFFER2),0); \
  LC_WINIT_FunctionBlock_BUFFER(&((p)->LC_VD_BUFFER4),0); \
  LC_WINIT_FunctionBlock_BUFFER(&((p)->LC_VD_BUFFER3),0); \
  if (RF==0) (p)->LC_VD_CELL_VOLTAGE_MAX_BMU_LOC = (LC_TD_USINT)0; \
  if (RF==0) (p)->LC_VD_CELL_VOLTAGE_MAX_CELL_LOC = (LC_TD_USINT)0; \
  if (RF==0) (p)->LC_VD_CELL_VOLTAGE_MIN_BMU_LOC = (LC_TD_USINT)0; \
  if (RF==0) (p)->LC_VD_CELL_VOLTAGE_MIN_CELL_LOC = (LC_TD_USINT)0; \
  if (RF==0) (p)->LC_VD_CELL_VOLTAGE_MAX = (LC_TD_UDINT)0UL; \
  LC_WINIT_USINT(&((p)->LC_VD_NUMBER_OF_BMU_CFG),RF); \
  if (RF==0) (p)->LC_VD_CELL_VOLTAGE = (LC_TD_UDINT)0UL; \
  if (RF==0) (p)->LC_VD_CELL_TEMP = (LC_TD_REAL)0; \
  if (RF==0) \
    { \
    LC_WINIT_ARRAY(&((p)->LC_VD_NUMOFCELLS),USINT,16,RF); \
    LC_INIT_ARRAY_START(&((p)->LC_VD_NUMOFCELLS),LC_TD_USINT);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)15);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)10);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)0);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)0);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)0);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)0);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)0);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)0);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)0);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)0);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)0);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)0);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)0);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)0);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)0);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)0);\
    LC_INIT_ARRAY_END();\
    } \
  if (RF==0) \
    { \
    LC_WINIT_ARRAY(&((p)->LC_VD_CHANNELSELECT),DataType_PLCHANNEL,16,RF); \
    LC_INIT_ARRAY_START(&((p)->LC_VD_CHANNELSELECT),LC_TD_UDINT);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)3840UL);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)3840UL);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)256UL);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)256UL);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)256UL);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)256UL);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)256UL);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)256UL);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)256UL);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)256UL);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)256UL);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)256UL);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)3840UL);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)256UL);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)256UL);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)256UL);\
    LC_INIT_ARRAY_END();\
    } \
  if (RF==0) (p)->LC_VD_TOTAL_VOLTAGE = (LC_TD_REAL)0; \
  LC_WINIT_UINT(&((p)->LC_VD_NUMBER_OF_CELL),RF); \
  if (RF==0) (p)->LC_VD_CELL_VOLTAGE_MIN = (LC_TD_UDINT)0UL; \
  if (RF==0) (p)->LC_VD_CELL_VOLTAGE_AVERAGE = (LC_TD_UDINT)0UL; \
  LC_WINIT_BOOL(&((p)->LC_VD_MAINCHARGECOMPLETE),RF); \
  if (RF==0) (p)->LC_VD_BALANCE_REGISTER = (LC_TD_UINT)0; \
  LC_WINIT_REAL(&((p)->LC_VD_OUTPUTVOLTAGE),RF); \
  LC_WINIT_REAL(&((p)->LC_VD_BATTERYVOLTAGE),RF); \
  if (RF==0) (p)->LC_VD_PACK_DMDC = (LC_TD_UINT)0; \
  if (RF==0) (p)->LC_VD_PACK_DMCC = (LC_TD_UINT)0; \
  LC_WINIT_BOOL(&((p)->LC_VD_FORCECHARGE),RF); \
  if (RF==0) (p)->LC_VD_CMDBCU = (LC_TD_USINT)0; \
  LC_WINIT_BOOL(&((p)->LC_VD_FORCEDISCHARGE),RF); \
  LC_WINIT_REAL(&((p)->LC_VD_WHINSTANT),RF); \
  if (RF==0) (p)->LC_VD_SELECTED_BMU_LOC = (LC_TD_USINT)0; \
  LC_WINIT_UINT(&((p)->LC_VD_CELLVOLT_CHARGEOK),RF); \
  if (RF==0) (p)->LC_VD_CAN_ID_10 = (LC_TD_UDINT)0UL; \
  if (RF==0) (p)->LC_VD_KWHCAPACITY = (LC_TD_REAL)0; \
  LC_WINIT_REAL(&((p)->LC_VD_VOLTSAMPLE1),RF); \
  LC_WINIT_REAL(&((p)->LC_VD_WHCAPACITY),RF); \
  if (RF==0) (p)->LC_VD_BMS_STATE = (LC_TD_USINT)0; \
  if (RF==0) (p)->LC_VD_SOH = (LC_TD_USINT)0; \
  if (RF==0) (p)->LC_VD_NUMBER_OF_PARALLEL_CELL = (LC_TD_USINT)3; \
  if (RF==0) (p)->LC_VD_CELLVOLT_NOMINAL = (LC_TD_UDINT)0UL; \
  if (RF==0) (p)->LC_VD_CELL_CURRENT_NOMINAL = (LC_TD_UDINT)0UL; \
  if (RF==0) (p)->LC_VD_NUMBER_OF_BMU = (LC_TD_USINT)0; \
  LC_WINIT_REAL(&((p)->LC_VD_BATTERYCURRENT),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_SELECTLASTONE),RF); \
  if (RF==0) (p)->LC_VD_CELLVOLT_MAX = (LC_TD_UINT)3500; \
  LC_WINIT_REAL(&((p)->LC_VD_VOLTSAMPLE2),RF); \
  if (RF==0) (p)->LC_VD_BCU_CHARGE_COMPLETE = LC_EL_false; \
  if (RF==0) (p)->LC_VD_SOC_CC = (LC_TD_USINT)0; \
  if (RF==0) (p)->LC_VD_CELL_VOLTAGE_MIN_DISHARGE = (LC_TD_UINT)0; \
  if (RF==0) (p)->LC_VD_CELL_VOLTAGE_MAX_CHARGE = (LC_TD_UINT)0; \
  LC_WINIT_UINT(&((p)->LC_VD_CELLVOLT_DISCHARGEOK),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_OV_DANGER),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_UV_DANGER),RF); \
  if (RF==0) (p)->LC_VD_CAN_ID_12 = (LC_TD_UDINT)0UL; \
  if (RF==0) (p)->LC_VD_CAN_ID_11 = (LC_TD_UDINT)0UL; \
  LC_WINIT_BOOL(&((p)->LC_VD_DISCHARGECOMPLETE),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_CONTACTENABLE_BATT),RF); \
  if (RF==0) (p)->LC_VD_CELL_TEMP_MIN_CELL_LOC = (LC_TD_USINT)0; \
  if (RF==0) (p)->LC_VD_BALANCE_ENABLE_RQ = LC_EL_false; \
  if (RF==0) (p)->LC_VD_CELL_TEMP_MAX_BMU_LOC = (LC_TD_USINT)0; \
  if (RF==0) (p)->LC_VD_CELL_TEMP_MAX_CELL_LOC = (LC_TD_USINT)0; \
  if (RF==0) (p)->LC_VD_FAULT_CELL_UNDER_TEMP_DANGER = LC_EL_false; \
  if (RF==0) (p)->LC_VD_FAULT_PACK_DISCHARGE_CONTACTOR = LC_EL_false; \
  if (RF==0) (p)->LC_VD_FAULT_CELL_OVER_TEMP_DANGER = LC_EL_false; \
  LC_WINIT_BOOL(&((p)->LC_VD_CONTACTENABLE),RF); \
  if (RF==0) (p)->LC_VD_CAN_ID_13 = (LC_TD_UDINT)0UL; \
  if (RF==0) (p)->LC_VD_CELL_TEMP_MAX = (LC_TD_REAL)0; \
  if (RF==0) (p)->LC_VD_CELL_TEMP_MIN = (LC_TD_REAL)0; \
  if (RF==0) (p)->LC_VD_CELL_TEMP_MIN_BMU_LOC = (LC_TD_USINT)0; \
  LC_WINIT_UINT(&((p)->LC_VD_CELLVOLT_MAXCHARGE),RF); \
  LC_WINIT_REAL(&((p)->LC_VD_PACK_CHARGE_VOLTAGE),RF); \
  if (RF==0) (p)->LC_VD_SELECTED_CELL_LOC = (LC_TD_USINT)0; \
  LC_WINIT_BOOL(&((p)->LC_VD_CONTACTFBK),RF); \
  if (RF==0) (p)->LC_VD_CELLVOLT_CUTOFFLOW = (LC_TD_UINT)2600; \
  if (RF==0) (p)->LC_VD_CELLVOLT_BALTHRES = (LC_TD_UINT)0; \
  if (RF==0) (p)->LC_VD_CELLTEMP_MAXLIM = (LC_TD_REAL)55; \
  LC_WINIT_REAL(&((p)->LC_VD_PACK_DISCHARGE_VOLTAGE),RF); \
  if (RF==0) (p)->LC_VD_CELLTEMP_WARNINGOT = (LC_TD_REAL)0; \
  if (RF==0) (p)->LC_VD_CELLTEMP_WARNINGUT = (LC_TD_REAL)0; \
  LC_WINIT_BOOL(&((p)->LC_VD_UV_FAULT),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_UV_DANGER_RISK),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_OV_DANGER_RISK),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_OT_DANGER),RF); \
  LC_WINIT_UINT(&((p)->LC_VD_CELLVOLT_MINDISCHARGE),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_CHARGECMD),RF); \
  if (RF==0) (p)->LC_VD_CELLTEMP_MINLIM = (LC_TD_REAL)-5; \
  if (RF==0) (p)->LC_VD_FAULT_CELL_UNDER_TEMP_WARNING = LC_EL_false; \
  if (RF==0) (p)->LC_VD_FAULT_CELL_OVER_TEMP_WARNING = LC_EL_false; \
  if (RF==0) (p)->LC_VD_FAULT_CELL_UNDER_VOLTAGE_WARNING = LC_EL_false; \
  if (RF==0) (p)->LC_VD_FAULT_CELL_OVER_VOLTAGE_WARNING = LC_EL_false; \
  if (RF==0) (p)->LC_VD_BOARD_FAULT_MESSAGES = (LC_TD_UDINT)0UL; \
  if (RF==0) (p)->LC_VD_CHARGEOK_VOLTAGE_PACK = (LC_TD_REAL)0; \
  if (RF==0) (p)->LC_VD_FAULT_PACK_HVIL_1 = LC_EL_false; \
  if (RF==0) (p)->LC_VD_BCU_CAN_CH = LC_ED__TMS570_CAN__L1; \
  LC_WINIT_REAL(&((p)->LC_VD_BMSDMCC_MAIN),RF); \
  if (RF==0) (p)->LC_VD_CAN_ID_14 = (LC_TD_UDINT)0UL; \
  if (RF==0) (p)->LC_VD_BALANCE_VOLTAGE = (LC_TD_UDINT)0UL; \
  if (RF==0) (p)->LC_VD_FAULT_PACK_CMS = LC_EL_false; \
  if (RF==0) (p)->LC_VD_PACK_TEMPERATURE = (LC_TD_REAL)0; \
  LC_WINIT_BOOL(&((p)->LC_VD_EMERGENCYBTN),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_BALANCESTATEENB),RF); \
  if (RF==0) (p)->LC_VD_CAN_FAULT_07 = LC_EL_false; \
  if (RF==0) (p)->LC_VD_FAULT_CAN_COMMUNICATION = LC_EL_false; \
  LC_WINIT_USINT(&((p)->LC_VD_ISOLATIONSTATUS),RF); \
  if (RF==0) (p)->LC_VD_BCU_FAULT_WARNING = LC_EL_false; \
  LC_WINIT_UDINT(&((p)->LC_VD_CAN_ID_16),RF); \
  if (RF==0) (p)->LC_VD_FAULT_PACK_BMU = LC_EL_false; \
  if (RF==0) (p)->LC_VD_CELLVOLT_MIN = (LC_TD_UINT)2800; \
  if (RF==0) (p)->LC_VD_CMD_VOLTAGE_SENSE_2 = (LC_TD_REAL)0; \
  if (RF==0) (p)->LC_VD_CMD_VOLTAGE_SENSE_3 = (LC_TD_REAL)0; \
  if (RF==0) (p)->LC_VD_CHARGE_CURRENT = (LC_TD_UINT)0; \
  if (RF==0) (p)->LC_VD_CMD_VOLTAGE_SENSE_1 = (LC_TD_REAL)0; \
  if (RF==0) (p)->LC_VD_MEASURE_ALL = LC_EL_false; \
  if (RF==0) (p)->LC_VD_MEASURE_AUX = LC_EL_false; \
  if (RF==0) \
    { \
    LC_WINIT_ARRAY(&((p)->LC_VD_TAUXCELLS),USINT,16,RF); \
    LC_INIT_ARRAY_START(&((p)->LC_VD_TAUXCELLS),LC_TD_USINT);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)0);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)0);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)0);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)0);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)1);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)1);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)1);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)1);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)2);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)2);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)2);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)2);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)3);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)3);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)3);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_USINT)3);\
    LC_INIT_ARRAY_END();\
    } \
  if (RF==0) (p)->LC_VD_BCU_FAULT_DANGER = LC_EL_false; \
  if (RF==0) (p)->LC_VD_CMD_CURRENT_SENSE = (LC_TD_REAL)0; \
  if (RF==0) (p)->LC_VD_FAULT_DMDC_EXCEED = LC_EL_false; \
  if (RF==0) (p)->LC_VD_FAULT_DMCC_EXCEED = LC_EL_false; \
  if (RF==0) (p)->LC_VD_FAULT_PACK_CHARGE_CONTACTOR = LC_EL_false; \
  if (RF==0) (p)->LC_VD_BOARD_ERROR_MESSAGES = (LC_TD_UDINT)0UL; \
  if (RF==0) (p)->LC_VD_CMD_COUNTER_CURRENT = (LC_TD_REAL)0; \
  if (RF==0) (p)->LC_VD_SELECTED_PACK_NUMBER = (LC_TD_USINT)0; \
  if (RF==0) (p)->LC_VD_CMD_POWER = (LC_TD_REAL)0; \
  if (RF==0) (p)->LC_VD_FAULT_PACK_HVIL_2 = LC_EL_false; \
  if (RF==0) (p)->LC_VD_CMD_TEMP = (LC_TD_REAL)0; \
  if (RF==0) (p)->LC_VD_CAN_FAULT_05 = LC_EL_false; \
  if (RF==0) (p)->LC_VD_CAN_FAULT_04 = LC_EL_false; \
  if (RF==0) (p)->LC_VD_CAN_FAULT_02 = LC_EL_false; \
  LC_WINIT_BOOL(&((p)->LC_VD_IGNITION),RF); \
  LC_WINIT_USINT(&((p)->LC_VD_BALCHARGEST),RF); \
  if (RF==0) (p)->LC_VD_CAN_FAULT_06 = LC_EL_false; \
  if (RF==0) (p)->LC_VD_CELL_SERIES_CONNECTION = (LC_TD_USINT)0; \
  if (RF==0) (p)->LC_VD_GUI_FAULT = (LC_TD_UDINT)0UL; \
  if (RF==0) (p)->LC_VD_CELLVOLT_CUTOFFHIGH = (LC_TD_UINT)3600; \
  if (RF==0) (p)->LC_VD_EPCS_CAN_CH = LC_ED__TMS570_CAN__L3; \
  if (RF==0) (p)->LC_VD_DICHARGEOK_VOLTAGE_PACK = (LC_TD_REAL)0; \
  if (RF==0) (p)->LC_VD_BATTERYID = (LC_TD_BYTE)1; \
  if (RF==0) (p)->LC_VD_FAULT_CELL_OVER_VOLTAGE_DANGER = LC_EL_false; \
  if (RF==0) (p)->LC_VD_FAULT_CELL_UNDER_VOLTAGE_DANGER = LC_EL_false; \
  if (RF==0) (p)->LC_VD_CAN_ID_15 = (LC_TD_UDINT)0UL; \
  if (RF==0) (p)->LC_VD_DUTY_CYCLE = (LC_TD_UINT)0; \
  if (RF==0) (p)->LC_VD_CMD_OVERALL_POWER = (LC_TD_LREAL)0; \
  LC_WINIT_BOOL(&((p)->LC_VD_UT_DANGER),RF); \
  LC_WINIT_REAL(&((p)->LC_VD_CMS0VOLT1),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_PRECHARGECOMPLETE),RF); \
  LC_WINIT_REAL(&((p)->LC_VD_CMS1VOLT1),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_PRECHARGEENABLE),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_PRECHARGEERROR),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_PRECHARGECANERR),RF); \
  LC_WINIT_USINT(&((p)->LC_VD_PRECHARGESTATUS),RF); \
  LC_WINIT_BYTE(&((p)->LC_VD_SIM100_ERRBYTE),RF); \
  LC_WINIT_REAL(&((p)->LC_VD_PACK_CUTOFFLOW_VOLTAGE),RF); \
  LC_WINIT_REAL(&((p)->LC_VD_INSTANTPOWER),RF); \
  LC_WINIT_LWORD(&((p)->LC_VD_FAULTSWORD),RF); \
  if (RF==0) (p)->LC_VD_CAN_FAULT_03 = LC_EL_false; \
  if (RF==0) (p)->LC_VD_MASTERID = (LC_TD_BYTE)128; \
  if (RF==0) (p)->LC_VD_HVCU_STATE = (LC_TD_USINT)0; \
  LC_WINIT_BOOL(&((p)->LC_VD_DISCHARGETERMINATE),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_OV_FAULT),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_UT_DANGER_RISK),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_OT_DANGER_RISK),RF); \
  LC_WINIT_REAL(&((p)->LC_VD_BMSDMDC_FINAL),RF); \
  LC_WINIT_REAL(&((p)->LC_VD_BMSDMCC_FINAL),RF); \
  LC_WINIT_REAL(&((p)->LC_VD_TESTREMWH),RF); \
  LC_WINIT_USINT(&((p)->LC_VD_TESTSOCSTATE),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_INPUTSGN1),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_INPUTSGN2),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_INPUTSGN3),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_OUTPUTSGN1),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_OUTPUTSGN2),RF); \
  LC_WINIT_FunctionBlock_IOWR(&((p)->LC_VD_IOWR13),0); \
  LC_WINIT_FunctionBlock_ANLG(&((p)->LC_VD_ANLG8),0); \
  if (RF==0) (p)->LC_VD_DOD_RATE = (LC_TD_REAL)0; \
  LC_WINIT_REAL(&((p)->LC_VD_USABLECAPKWH),RF); \
  LC_WINIT_REAL(&((p)->LC_VD_SOCREAL),RF); \
  LC_WINIT_REAL(&((p)->LC_VD_USABLECAPWH),RF); \
  LC_WINIT_REAL(&((p)->LC_VD_PACKREMCAP_KWH),RF); \
  LC_WINIT_REAL(&((p)->LC_VD_USABLEREMWH),RF); \
  LC_WINIT_REAL(&((p)->LC_VD_USABLEREMKWH),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_HVIL1_STATUS),RF); \
  LC_WINIT_FunctionBlock_BUFFER(&((p)->LC_VD_BUFFER10),0); \
  LC_WINIT_FunctionBlock_TOF(&((p)->LC_VD_TOF6),0); \
  LC_WINIT_REAL(&((p)->LC_VD_PACK_CUTOFFHIGH_VOLTAGE),RF); \
  LC_WINIT_FunctionBlock_GUICFG_INT(&((p)->LC_VD_GUICFG_INT4),0); \
  LC_WINIT_FunctionBlock_GUICFG_INT(&((p)->LC_VD_GUICFG_INT5),0); \
  LC_WINIT_UINT(&((p)->LC_VD_MAXDISCHARGEAMPRCFG),RF); \
  LC_WINIT_FunctionBlock_TBUFFER(&((p)->LC_VD_TBUFFER2),0); \
  LC_WINIT_FunctionBlock_TBUFFER(&((p)->LC_VD_TBUFFER7),0); \
  LC_WINIT_REAL(&((p)->LC_VD_PACK_CUTOFFV_LOW),RF); \
  LC_WINIT_REAL(&((p)->LC_VD_CMD_VOLTAGE_SENSE1_VOLT),RF); \
  LC_WINIT_REAL(&((p)->LC_VD_CMD_VOLTAGE_SENSE2_VOLT),RF); \
  LC_WINIT_UINT(&((p)->LC_VD_CELLVOLT_WARNINGOV),RF); \
  LC_WINIT_UINT(&((p)->LC_VD_CELLVOLT_WARNINGUV),RF); \
  if (RF==0) (p)->LC_VD_PDUCAN = LC_ED__TMS570_CAN__L2; \
  LC_WINIT_FunctionBlock_GUICFG_INT(&((p)->LC_VD_GUICFG_INT6),0); \
  LC_WINIT_UINT(&((p)->LC_VD_OCWARNINGAMPR),RF); \
  LC_WINIT_FunctionBlock_TBUFFER(&((p)->LC_VD_TBUFFER1),0); \
  LC_WINIT_BOOL(&((p)->LC_VD_OC_WARNING),RF); \
  LC_WINIT_FunctionBlock_TBUFFER(&((p)->LC_VD_TBUFFER4),0); \
  LC_WINIT_BOOL(&((p)->LC_VD_OC_FAULT),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_CONTACTNEGENABLE_BATT),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_CONTACTENABLECHARGE_BATT),RF); \
  LC_WINIT_REAL(&((p)->LC_VD_CHARGEINVOLTAGE),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_CONTACTFBKDISCHARGE),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_CONTACTFBKCHARGE),RF); \
  LC_WINIT_FunctionBlock_TOF(&((p)->LC_VD_TOF8),0); \
  LC_WINIT_FunctionBlock_BUFFER(&((p)->LC_VD_BUFFER22),0); \
  LC_WINIT_FunctionBlock_TOF(&((p)->LC_VD_TOF9),0); \
  LC_WINIT_FunctionBlock_BUFFER(&((p)->LC_VD_BUFFER23),0); \
  LC_WINIT_BOOL(&((p)->LC_VD_FAULT_PACK_NEGATIVE_CONTACTOR),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_DISCHARGECMD),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_PRECHARGECOMPLETECHARGE),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_PRECHARGEENABLECHARGE),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_SHUTDOWNCOMPLETE),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_SHUTDOWNCMD),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_DISCHARGEOFF),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_CHARGEOFF),RF); \
  LC_WINIT_FunctionBlock_TBUFFER(&((p)->LC_VD_TBUFFER6),0); \
  LC_WINIT_FunctionBlock_SR(&((p)->LC_VD_SR2),0); \
  LC_WINIT_BOOL(&((p)->LC_VD_PDULED),RF); \
  LC_WINIT_USINT(&((p)->LC_VD_INPUTSGN1STATUS),RF); \
  LC_WINIT_USINT(&((p)->LC_VD_INPUTSGN2STATUS),RF); \
  LC_WINIT_FunctionBlock_GUICFG_INT(&((p)->LC_VD_GUICFG_INT7),0); \
  LC_WINIT_FunctionBlock_GUICFG_INT(&((p)->LC_VD_GUICFG_INT8),0); \
  LC_WINIT_FunctionBlock_GUICFG_INT(&((p)->LC_VD_GUICFG_INT9),0); \
  LC_WINIT_FunctionBlock_GUICFG_INT(&((p)->LC_VD_GUICFG_INT10),0); \
  LC_WINIT_FunctionBlock_GUICFG_INT(&((p)->LC_VD_GUICFG_INT11),0); \
  LC_WINIT_FunctionBlock_GUICFG_INT(&((p)->LC_VD_GUICFG_INT12),0); \
  LC_WINIT_FunctionBlock_GUICFG_INT(&((p)->LC_VD_GUICFG_INT13),0); \
  LC_WINIT_FunctionBlock_GUICFG_INT(&((p)->LC_VD_GUICFG_INT14),0); \
  LC_WINIT_FunctionBlock_GUICFG_INT(&((p)->LC_VD_GUICFG_INT15),0); \
  LC_WINIT_FunctionBlock_GUICFG_INT(&((p)->LC_VD_GUICFG_INT16),0); \
  LC_WINIT_FunctionBlock_GUICFG_INT(&((p)->LC_VD_GUICFG_INT17),0); \
  LC_WINIT_FunctionBlock_GUICFG_INT(&((p)->LC_VD_GUICFG_INT18),0); \
  LC_WINIT_FunctionBlock_GUICFG_INT(&((p)->LC_VD_GUICFG_INT19),0); \
  LC_WINIT_FunctionBlock_GUICFG_INT(&((p)->LC_VD_GUICFG_INT20),0); \
  LC_WINIT_FunctionBlock_GUICFG_INT(&((p)->LC_VD_GUICFG_INT21),0); \
  LC_WINIT_FunctionBlock_GUICFG_INT(&((p)->LC_VD_GUICFG_INT22),0); \
  LC_WINIT_FunctionBlock_GUICFG_INT(&((p)->LC_VD_GUICFG_INT23),0); \
  LC_WINIT_UDINT(&((p)->LC_VD_BALANCEDIFF_THRESHOLD),RF); \
  LC_WINIT_FunctionBlock_GUICFG_REAL(&((p)->LC_VD_GUICFG_REAL1),0); \
  LC_WINIT_FunctionBlock_GUICFG_INT(&((p)->LC_VD_GUICFG_INT24),0); \
  LC_WINIT_UINT(&((p)->LC_VD_CYCLESPERSOH),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_SELCLOCK),RF); \
  LC_WINIT_ARRAY(&((p)->LC_VD_BMUCELLVOLT),UINT,16,RF); \
  LC_WINIT_ARRAY(&((p)->LC_VD_BMUCELLTEMP),SINT,16,RF); \
  LC_WINIT_UINT(&((p)->LC_VD_BMUMAXCELLV),RF); \
  LC_WINIT_UINT(&((p)->LC_VD_BMUMINCELLV),RF); \
  LC_WINIT_SINT(&((p)->LC_VD_BMUMINCELLT),RF); \
  LC_WINIT_SINT(&((p)->LC_VD_BMUMAXCELLT),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_WARNINGMDLBALT),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_FAULTMDLBALT),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_FAULTFORSTATE),RF); \
  LC_WINIT_UINT(&((p)->LC_VD_MAXCHARGEAMPRCFG),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_HVIL2_STATUS),RF); \
  LC_WINIT_FunctionBlock_TOF(&((p)->LC_VD_TOF10),0); \
  LC_WINIT_FunctionBlock_BUFFER(&((p)->LC_VD_BUFFER13),0); \
  LC_WINIT_BOOL(&((p)->LC_VD_IMDENABLE),RF); \
  LC_WINIT_UDINT(&((p)->LC_VD_ISORP),RF); \
  LC_WINIT_UDINT(&((p)->LC_VD_ISORN),RF); \
  LC_WINIT_UDINT(&((p)->LC_VD_ISOOHMPERV),RF); \
  LC_WINIT_FunctionBlock_GUICFG_INT(&((p)->LC_VD_GUICFG_INT25),0); \
  LC_WINIT_UDINT(&((p)->LC_VD_PRECHARGEINTERVAL),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_FORCENEGATIVE),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_CONTACTNEGENABLE),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_CONTACTENABLECHARGE),RF); \
  LC_WINIT_FunctionBlock_GUICFG_INT(&((p)->LC_VD_GUICFG_INT26),0); \
  LC_WINIT_UDINT(&((p)->LC_VD_NTCBETA),RF); \
  LC_WINIT_FunctionBlock_GUICFG_INT(&((p)->LC_VD_GUICFG_INT27),0); \
  LC_WINIT_UINT(&((p)->LC_VD_OCFAULTAMPR),RF); \
  LC_WINIT_FunctionBlock_TBUFFER(&((p)->LC_VD_TBUFFER15),0); \
  LC_WINIT_FunctionBlock_TBUFFER(&((p)->LC_VD_TBUFFER16),0); \
  LC_WINIT_FunctionBlock_SR(&((p)->LC_VD_SR5),0); \
  LC_WINIT_BOOL(&((p)->LC_VD_BATTERYINCHARGE),RF); \
  LC_WINIT_FunctionBlock_HVCU_CONTROL_STATE(&((p)->LC_VD_HVCU_CONTROL_STATE2),0); \
  if (RF==0) (p)->LC_VD_SLAVEMODE = LC_EL_true; \
  LC_WINIT_BOOL(&((p)->LC_VD_DISCHARGEENB),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_CHARGEENB),RF); \
  LC_WINIT_DataType_BESSSYSTEMSTATUS(&((p)->LC_VD_BESSSTATUS),RF); \
  LC_WINIT_DataType_BESSOPRSTATUS(&((p)->LC_VD_BESSOPERATINGSTATUS),RF); \
  LC_WINIT_DataType_BESSWORKMODE(&((p)->LC_VD_BESSWORKINGMODE),RF); \
  LC_WINIT_DataType_BESSALARMS(&((p)->LC_VD_BATEPCSALARM),RF); \
  LC_WINIT_REAL(&((p)->LC_VD_CMD_CURRENT_SENSE_AMP),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_BATTERYCHARGING),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_BATTERYDISCHARGING),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_CURRENTPROTECTION),RF); \
  LC_WINIT_FunctionBlock_TBUFFER(&((p)->LC_VD_TBUFFER20),0); \
  LC_WINIT_FunctionBlock_TBUFFER(&((p)->LC_VD_TBUFFER19),0); \
  LC_WINIT_FunctionBlock_TON(&((p)->LC_VD_TON17),0); \
  LC_WINIT_FunctionBlock_TON(&((p)->LC_VD_TON2),0); \
  LC_WINIT_FunctionBlock_TON(&((p)->LC_VD_TON19),0); \
  LC_WINIT_FunctionBlock_TON(&((p)->LC_VD_TON18),0); \
  LC_WINIT_BOOL(&((p)->LC_VD_CHARGEPROTECT),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_DISCHARGEPROTECT),RF); \
  LC_WINIT_FunctionBlock_ESSSTATE1(&((p)->LC_VD_ESSSTATE11),0); \
  if (RF==0) (p)->LC_VD_SHUTDOWNENB = LC_EL_false; \
  LC_WINIT_BOOL(&((p)->LC_VD_PRECHARGEBOARDERR),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_SIM100NOTFOUND),RF); \
  LC_WINIT_REAL(&((p)->LC_VD_BATTERYWATT),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_EPCSREQDATA),RF); \
  LC_WINIT_FunctionBlock_F_TRIG(&((p)->LC_VD_F_TRIG3),0); \
  LC_WINIT_FunctionBlock_F_TRIG(&((p)->LC_VD_F_TRIG4),0); \
  LC_WINIT_FunctionBlock_R_TRIG(&((p)->LC_VD_R_TRIG9),0); \
  LC_WINIT_REAL(&((p)->LC_VD_SOCCHCOMP),RF); \
  LC_WINIT_FunctionBlock_R_TRIG(&((p)->LC_VD_R_TRIG2),0); \
  LC_WINIT_REAL(&((p)->LC_VD_SOCDCHCOMP),RF); \
  LC_WINIT_FunctionBlock_R_TRIG(&((p)->LC_VD_R_TRIG3),0); \
  LC_WINIT_FunctionBlock_HVCU_CONFIG(&((p)->LC_VD_HVCU_CONFIG1),0); \
  LC_WINIT_BOOL(&((p)->LC_VD_CMDTMT),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_ADDRBIT0),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_ADDRBIT1),RF); \
  LC_WINIT_REAL(&((p)->LC_VD_MULTAMPCHAR),RF); \
  LC_WINIT_REAL(&((p)->LC_VD_MULTAMPDISCH),RF); \
  LC_WINIT_FunctionBlock_AMPMULTTEMP(&((p)->LC_VD_AMPMULTTEMP1),0); \
  LC_WINIT_FunctionBlock_AMPMULTTEMP(&((p)->LC_VD_AMPMULTTEMP2),0); \
  LC_WINIT_FunctionBlock_AMPMULTTEMPDIS(&((p)->LC_VD_AMPMULTTEMPDIS1),0); \
  LC_WINIT_FunctionBlock_AMPMULTTEMPDIS(&((p)->LC_VD_AMPMULTTEMPDIS2),0); \
  LC_WINIT_FunctionBlock_AMPMULTVOLTDISC(&((p)->LC_VD_AMPMULTVOLTDISC1),0); \
  LC_WINIT_FunctionBlock_AMPMULTVOLTCHAR(&((p)->LC_VD_AMPMULTVOLTCHAR1),0); \
  LC_WINIT_BOOL(&((p)->LC_VD_INCREASECHARGEAMP),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_INCREASEDISCHARGEAMP),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_DECREASECHARGEAMP),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_DECREASEDISCHARGEAMP),RF); \
  LC_WINIT_FunctionBlock_TON(&((p)->LC_VD_TON21),0); \
  LC_WINIT_BOOL(&((p)->LC_VD_DISCHARGEAMPENB),RF); \
  if (RF==0) (p)->LC_VD_DISCHARGEUNITAMP = (LC_TD_REAL)0.25; \
  LC_WINIT_BOOL(&((p)->LC_VD_CHARGEAMPENB),RF); \
  LC_WINIT_FunctionBlock_TON(&((p)->LC_VD_TON22),0); \
  if (RF==0) (p)->LC_VD_CHARGEUNITAMP = (LC_TD_REAL)0.25; \
  LC_WINIT_REAL(&((p)->LC_VD_MAXCHARGEAMP),RF); \
  LC_WINIT_REAL(&((p)->LC_VD_MAXDISCHARGEAMP),RF); \
  LC_WINIT_FunctionBlock_UPDOWNCNTTIM(&((p)->LC_VD_UPDOWNCNTTIM1),0); \
  LC_WINIT_FunctionBlock_UPDOWNCNTTIM(&((p)->LC_VD_UPDOWNCNTTIM2),0); \
  LC_WINIT_FunctionBlock_BCU_STATUS2(&((p)->LC_VD_BCU_STATUS21),0); \
  LC_WINIT_FunctionBlock_BCU_STATE_MESSAGE(&((p)->LC_VD_BCU_STATE_MESSAGE1),0); \
  LC_WINIT_FunctionBlock_BCU_BATTERY_STATUS(&((p)->LC_VD_BCU_BATTERY_STATUS1),0); \
  LC_WINIT_FunctionBlock_GUICFG_INT(&((p)->LC_VD_GUICFG_INT28),0); \
  LC_WINIT_TIME(&((p)->LC_VD_TESTVALUE0),RF); \
  LC_WINIT_FunctionBlock_TON(&((p)->LC_VD_TON4),0); \
  LC_WINIT_FunctionBlock_TON(&((p)->LC_VD_TON5),0); \
  LC_WINIT_FunctionBlock_IOWR(&((p)->LC_VD_IOWR4),0); \
  LC_WINIT_FunctionBlock_FLASH(&((p)->LC_VD_FLASH3),0); \
  LC_WINIT_FunctionBlock_SAFETY_POWER(&((p)->LC_VD_SAFETY_POWER1),0); \
  LC_WINIT_FunctionBlock_ANLG(&((p)->LC_VD_ANLG14),0); \
  LC_WINIT_FunctionBlock_TON(&((p)->LC_VD_TON1),0); \
  LC_WINIT_FunctionBlock_TOF(&((p)->LC_VD_TOF15),0); \
  LC_WINIT_BOOL(&((p)->LC_VD_BATTSTACK_DISABLE),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_CAN_DISABLE),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_RDY_TO_SLEEP),RF); \
  LC_WINIT_UINT(&((p)->LC_VD_AN_KL15),RF); \
  LC_WINIT_FunctionBlock_IOWR(&((p)->LC_VD_IOWR19),0); \
  LC_WINIT_FunctionBlock_IOWR(&((p)->LC_VD_IOWR6),0); \
  LC_WINIT_FunctionBlock_IOWR(&((p)->LC_VD_IOWR5),0); \
  LC_WINIT_FunctionBlock_IOWR(&((p)->LC_VD_IOWR18),0); \
  LC_WINIT_FunctionBlock_IOWR(&((p)->LC_VD_IOWR20),0); \
  LC_WINIT_FunctionBlock_IOWR(&((p)->LC_VD_IOWR21),0); \
  LC_WINIT_FunctionBlock_FLASH(&((p)->LC_VD_FLASH4),0); \
  LC_WINIT_BYTE(&((p)->LC_VD_HW_VERSION),RF); \
  LC_WINIT_FunctionBlock_IOWR(&((p)->LC_VD_IOWR9),0); \
  LC_WINIT_FunctionBlock_IOWR(&((p)->LC_VD_IOWR7),0); \
  LC_WINIT_FunctionBlock_IOWR(&((p)->LC_VD_IOWR22),0); \
  LC_WINIT_FunctionBlock_IOWR(&((p)->LC_VD_IOWR23),0); \
  LC_WINIT_FunctionBlock_IOWR(&((p)->LC_VD_IOWR10),0); \
  LC_WINIT_FunctionBlock_IOWR(&((p)->LC_VD_IOWR24),0); \
  LC_WINIT_FunctionBlock_ANLG(&((p)->LC_VD_ANLG4),0); \
  LC_WINIT_FunctionBlock_ANLG(&((p)->LC_VD_ANLG3),0); \
  LC_WINIT_FunctionBlock_ANLG(&((p)->LC_VD_ANLG1),0); \
  LC_WINIT_FunctionBlock_ANLG(&((p)->LC_VD_ANLG2),0); \
  LC_WINIT_FunctionBlock_IORD(&((p)->LC_VD_IORD5),0); \
  LC_WINIT_FunctionBlock_IORD(&((p)->LC_VD_IORD4),0); \
  LC_WINIT_FunctionBlock_IORD(&((p)->LC_VD_IORD1),0); \
  LC_WINIT_FunctionBlock_DGTIN(&((p)->LC_VD_DGTIN8),0); \
  LC_WINIT_FunctionBlock_DGTIN(&((p)->LC_VD_DGTIN3),0); \
  LC_WINIT_FunctionBlock_DGTIN(&((p)->LC_VD_DGTIN4),0); \
  LC_WINIT_FunctionBlock_IORD(&((p)->LC_VD_IORD2),0); \
  LC_WINIT_FunctionBlock_IORD(&((p)->LC_VD_IORD3),0); \
  LC_WINIT_BOOL(&((p)->LC_VD_IGNITION_KL15),RF); \
  LC_WINIT_FunctionBlock_F_TRIG(&((p)->LC_VD_F_TRIG2),0); \
  LC_WINIT_FunctionBlock_NTC(&((p)->LC_VD_NTC2),0); \
  if (RF==0) (p)->LC_VD_NEW_CHG_CONTACT = LC_EL_true; \
  if (RF==0) (p)->LC_VD_NEW_DCHG_CONTACT = LC_EL_true; \
  LC_WINIT_BOOL(&((p)->LC_VD_NEW_CONTACTFBK1),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_NEW_CONTACTFBK2),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_HKM_DISCHARGECONTACT),RF); \
  LC_WINIT_REAL(&((p)->LC_VD_HKM_DISCHARGEINVOLTAGE),RF); \
  LC_WINIT_REAL(&((p)->LC_VD_DISCHARGEINVOLTAGE),RF); \
  LC_WINIT_UINT(&((p)->LC_VD_NUMBER_OF_MAXCELL),RF); \
  LC_WINIT_USINT(&((p)->LC_VD_NUMBER_OF_MAXCELL2),RF); \
  LC_WINIT_FunctionBlock_ARR2VAL(&((p)->LC_VD_ARR2VAL2),0); \
  if (RF==0) (p)->LC_VD_NEWBMU_RESET = LC_EL_false; \
  LC_WINIT_FunctionBlock_PRECHARGECAN(&((p)->LC_VD_PRECHARGECAN1),0); \
  LC_WINIT_FunctionBlock_TON(&((p)->LC_VD_TON26),0); \
  LC_WINIT_FunctionBlock_TON(&((p)->LC_VD_TON27),0); \
  if (RF==0) \
    { \
    LC_WINIT_ARRAY(&((p)->LC_VD_CHANNELSELECT2),DataType_PLCHANNEL,16,RF); \
    LC_INIT_ARRAY_START(&((p)->LC_VD_CHANNELSELECT2),LC_TD_UDINT);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)1792UL);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)1792UL);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)1792UL);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)1792UL);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)1792UL);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)1792UL);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)1792UL);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)1792UL);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)1792UL);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)1792UL);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)1792UL);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)1792UL);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)1792UL);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)1792UL);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)1792UL);\
    LC_INIT_ARRAY_NEXTVAL((LC_TD_UDINT)1792UL);\
    LC_INIT_ARRAY_END();\
    } \
  LC_WINIT_BOOL(&((p)->LC_VD_ALLCONTACSTENABLE),RF); \
  LC_WINIT_FunctionBlock_GUICFG_INT(&((p)->LC_VD_GUICFG_INT1),0); \

#define LC_WINIT_Program_HEMABATTERY(p,RF) \
{ \
  LC_WINIT_NONDMA_Program_HEMABATTERY(p,RF) \
}

/*                            Prototype                        */
void  lcpu___HEMABATTERY(LC_TD_Program_HEMABATTERY* LC_this, struct _lcoplck_epdb_1_impl* pEPDB);


#endif
