#ifndef LC_PROT_LCDT___BCU_FAULT_TYPES__H
#define LC_PROT_LCDT___BCU_FAULT_TYPES__H

#include <LC3CGBase.h>

/*                            Typedefs                         */
typedef struct _LC_TD_DataType_BCU_FAULT_TYPES
{
  LC_TD_BOOL LC_VD_FAULT_BOARD_AUX_OVER_VOLTAGE;
  LC_TD_BOOL LC_VD_FAULT_BOARD_AUX_UNDER_VOLTAGE;
  LC_TD_BOOL LC_VD_FAULT_BOARD_CHIP;
  LC_TD_BOOL LC_VD_FAULT_BOARD_COMMINICATION;
  LC_TD_BOOL LC_VD_FAULT_BOARD_COMP_OVER_VOLTAGE;
  LC_TD_BOOL LC_VD_FAULT_BOARD_COMP_UNDER_VOLTAGE;
  LC_TD_BOOL LC_VD_FAULT_BOARD_GPI;
  LC_TD_BOOL LC_VD_FAULT_BOARD_OPEN_WIRE_DETECT;
  LC_TD_BOOL LC_VD_FAULT_BOARD_OVER_VOLTAGE;
  LC_TD_BOOL LC_VD_FAULT_BOARD_SYS;
  LC_TD_BOOL LC_VD_FAULT_BOARD_UNDER_VOLTAGE;
  LC_TD_BOOL LC_VD_FAULT_CAN_COMMUNICATION;
  LC_TD_BOOL LC_VD_FAULT_CELL_OVER_TEMP_DANGER;
  LC_TD_BOOL LC_VD_FAULT_CELL_OVER_TEMP_WARNING;
  LC_TD_BOOL LC_VD_FAULT_CELL_OVER_VOLTAGE_DANGER;
  LC_TD_BOOL LC_VD_FAULT_CELL_OVER_VOLTAGE_WARNING;
  LC_TD_BOOL LC_VD_FAULT_CELL_UNDER_TEMP_DANGER;
  LC_TD_BOOL LC_VD_FAULT_CELL_UNDER_TEMP_WARNING;
  LC_TD_BOOL LC_VD_FAULT_CELL_UNDER_VOLTAGE_DANGER;
  LC_TD_BOOL LC_VD_FAULT_CELL_UNDER_VOLTAGE_WARNING;
  LC_TD_BOOL LC_VD_FAULT_DEAD_CELL;
  LC_TD_BOOL LC_VD_FAULT_DMCC_EXCEED;
  LC_TD_BOOL LC_VD_FAULT_DMDC_EXCEED;
  LC_TD_BOOL LC_VD_FAULT_INTERNAL_MEASUREMENT;
  LC_TD_BOOL LC_VD_FAULT_OPEN_WIRE;
  LC_TD_BOOL LC_VD_FAULT_PACK_CONTACTOR;
  LC_TD_BOOL LC_VD_FAULT_PACK_CURRENT_SENSOR;
  LC_TD_BOOL LC_VD_FAULT_PACK_FUSE;
  LC_TD_BOOL LC_VD_FAULT_PACK_HVIL;
  LC_TD_BOOL LC_VD_FAULT_PACK_INT_COMMUNICATION;
  LC_TD_BOOL LC_VD_FAULT_PACK_TEMP_HIGH;
  LC_TD_BOOL LC_VD_FAULT_PACK_TEMP_LOW;
  LC_TD_BOOL LC_VD_FAULT_VOLTAGE_REDUNDANCY;
} LCCG_StructAttrib LC_TD_DataType_BCU_FAULT_TYPES;

/*                   ColdBoot Initialization Macro             */
#define LC_INIT_DataType_BCU_FAULT_TYPES(p) \
{ \
  LC_INIT_BOOL(&((p)->LC_VD_FAULT_PACK_CONTACTOR)); \
  LC_INIT_BOOL(&((p)->LC_VD_FAULT_PACK_HVIL)); \
  LC_INIT_BOOL(&((p)->LC_VD_FAULT_PACK_FUSE)); \
  LC_INIT_BOOL(&((p)->LC_VD_FAULT_BOARD_UNDER_VOLTAGE)); \
  LC_INIT_BOOL(&((p)->LC_VD_FAULT_BOARD_SYS)); \
  LC_INIT_BOOL(&((p)->LC_VD_FAULT_BOARD_OVER_VOLTAGE)); \
  LC_INIT_BOOL(&((p)->LC_VD_FAULT_BOARD_OPEN_WIRE_DETECT)); \
  LC_INIT_BOOL(&((p)->LC_VD_FAULT_BOARD_GPI)); \
  LC_INIT_BOOL(&((p)->LC_VD_FAULT_BOARD_COMP_UNDER_VOLTAGE)); \
  LC_INIT_BOOL(&((p)->LC_VD_FAULT_BOARD_COMP_OVER_VOLTAGE)); \
  LC_INIT_BOOL(&((p)->LC_VD_FAULT_BOARD_COMMINICATION)); \
  LC_INIT_BOOL(&((p)->LC_VD_FAULT_BOARD_CHIP)); \
  LC_INIT_BOOL(&((p)->LC_VD_FAULT_BOARD_AUX_UNDER_VOLTAGE)); \
  LC_INIT_BOOL(&((p)->LC_VD_FAULT_BOARD_AUX_OVER_VOLTAGE)); \
  LC_INIT_BOOL(&((p)->LC_VD_FAULT_PACK_TEMP_HIGH)); \
  LC_INIT_BOOL(&((p)->LC_VD_FAULT_VOLTAGE_REDUNDANCY)); \
  LC_INIT_BOOL(&((p)->LC_VD_FAULT_CELL_UNDER_TEMP_WARNING)); \
  LC_INIT_BOOL(&((p)->LC_VD_FAULT_CELL_UNDER_VOLTAGE_WARNING)); \
  LC_INIT_BOOL(&((p)->LC_VD_FAULT_PACK_INT_COMMUNICATION)); \
  LC_INIT_BOOL(&((p)->LC_VD_FAULT_CELL_OVER_VOLTAGE_WARNING)); \
  LC_INIT_BOOL(&((p)->LC_VD_FAULT_OPEN_WIRE)); \
  LC_INIT_BOOL(&((p)->LC_VD_FAULT_PACK_TEMP_LOW)); \
  LC_INIT_BOOL(&((p)->LC_VD_FAULT_INTERNAL_MEASUREMENT)); \
  LC_INIT_BOOL(&((p)->LC_VD_FAULT_CELL_OVER_TEMP_WARNING)); \
  LC_INIT_BOOL(&((p)->LC_VD_FAULT_DMDC_EXCEED)); \
  LC_INIT_BOOL(&((p)->LC_VD_FAULT_DMCC_EXCEED)); \
  LC_INIT_BOOL(&((p)->LC_VD_FAULT_DEAD_CELL)); \
  LC_INIT_BOOL(&((p)->LC_VD_FAULT_PACK_CURRENT_SENSOR)); \
  LC_INIT_BOOL(&((p)->LC_VD_FAULT_CAN_COMMUNICATION)); \
  LC_INIT_BOOL(&((p)->LC_VD_FAULT_CELL_UNDER_TEMP_DANGER)); \
  LC_INIT_BOOL(&((p)->LC_VD_FAULT_CELL_UNDER_VOLTAGE_DANGER)); \
  LC_INIT_BOOL(&((p)->LC_VD_FAULT_CELL_OVER_TEMP_DANGER)); \
  LC_INIT_BOOL(&((p)->LC_VD_FAULT_CELL_OVER_VOLTAGE_DANGER)); \
}

/*                   WarmBoot Initialization Macro             */
#define LC_WINIT_DataType_BCU_FAULT_TYPES(p,RF) \
{ \
  LC_WINIT_BOOL(&((p)->LC_VD_FAULT_PACK_CONTACTOR),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_FAULT_PACK_HVIL),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_FAULT_PACK_FUSE),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_FAULT_BOARD_UNDER_VOLTAGE),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_FAULT_BOARD_SYS),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_FAULT_BOARD_OVER_VOLTAGE),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_FAULT_BOARD_OPEN_WIRE_DETECT),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_FAULT_BOARD_GPI),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_FAULT_BOARD_COMP_UNDER_VOLTAGE),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_FAULT_BOARD_COMP_OVER_VOLTAGE),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_FAULT_BOARD_COMMINICATION),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_FAULT_BOARD_CHIP),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_FAULT_BOARD_AUX_UNDER_VOLTAGE),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_FAULT_BOARD_AUX_OVER_VOLTAGE),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_FAULT_PACK_TEMP_HIGH),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_FAULT_VOLTAGE_REDUNDANCY),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_FAULT_CELL_UNDER_TEMP_WARNING),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_FAULT_CELL_UNDER_VOLTAGE_WARNING),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_FAULT_PACK_INT_COMMUNICATION),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_FAULT_CELL_OVER_VOLTAGE_WARNING),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_FAULT_OPEN_WIRE),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_FAULT_PACK_TEMP_LOW),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_FAULT_INTERNAL_MEASUREMENT),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_FAULT_CELL_OVER_TEMP_WARNING),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_FAULT_DMDC_EXCEED),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_FAULT_DMCC_EXCEED),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_FAULT_DEAD_CELL),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_FAULT_PACK_CURRENT_SENSOR),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_FAULT_CAN_COMMUNICATION),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_FAULT_CELL_UNDER_TEMP_DANGER),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_FAULT_CELL_UNDER_VOLTAGE_DANGER),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_FAULT_CELL_OVER_TEMP_DANGER),RF); \
  LC_WINIT_BOOL(&((p)->LC_VD_FAULT_CELL_OVER_VOLTAGE_DANGER),RF); \
}

/*                ColdBoot Initialization Macro for Arrays            */
#define LC_INIT_ARRAY_OF_DataType_BCU_FAULT_TYPES(p,ARRAYSIZE) \
{ \
  LC_TD_DataType_BCU_FAULT_TYPES * ptrToElement_ArrayOf_BCU_FAULT_TYPES = (LC_TD_DataType_BCU_FAULT_TYPES*)(p);\
  LC_TD_DataType_BCU_FAULT_TYPES * arrayEnd = ptrToElement_ArrayOf_BCU_FAULT_TYPES+ARRAYSIZE;\
  for (; ptrToElement_ArrayOf_BCU_FAULT_TYPES < arrayEnd; ptrToElement_ArrayOf_BCU_FAULT_TYPES++) \
  { \
    LC_INIT_DataType_BCU_FAULT_TYPES(ptrToElement_ArrayOf_BCU_FAULT_TYPES); \
  } \
}

/*                WarmBoot Initialization Macro for Arrays            */
#define LC_WINIT_ARRAY_OF_DataType_BCU_FAULT_TYPES(p,ARRAYSIZE,RF) \
{ \
  if (RF==0) \
  { \
    LC_INIT_ARRAY_OF_DataType_BCU_FAULT_TYPES(p,ARRAYSIZE); \
  } \
}


#endif
